### ISSUE TITLE
deleting a section messes up saving other sections

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1016]
I deleted the "purpose" section of the Introduction and now anytime I try to add text and save it to any part of chapter 1 I get a saving error (see below).

![image](https://cloud.githubusercontent.com/assets/17408249/21808210/d875023e-d707-11e6-923c-a4eb86ec2a3c.png)

If I go to Chapter 1 (Use Cases), I can edit and save text in those sections.

When I close the document and open it back up, all the sections in Introduction are now gone (red box below)
![image](https://cloud.githubusercontent.com/assets/17408249/21808282/4a9eb9e0-d708-11e6-90c4-40131fd05210.png)

**Comment by Abdelghani90** [comment]
Hi Craig, 
Thank you for reporting this. I have been working on the issue but I still cannot reproduce it. 
I want to know if you tried the drag&drop before deleting the section. 
Also it may be helpful for me to know if it is a new Igdocument ?created from scratch or a copy of an existing igdocument?
Thanks

**Comment by csnewman88** [comment]
It was a brand new document and I didn't do any drag and drop at all.

I had a hard time replicating it myself, I think I've got. Try the following:
1) create a new document
2) enter text in the introduction section but don't save it (this is really important)
3) create a new section by right clicking on Introduction and selecting "Add Section"
4) edit any section and try to save

This should give you the error and then the disappearing subsections when you close and reopen the document. Note that when you close the IG, you'll have "discard" the unsaved changes because trying to save them will cause the error to happen.

**Comment by Abdelghani90** [comment]
Finally fixed(not deployed yet). 
thank you very much this was very very helpful.
