### ISSUE TITLE
conformance statements bleed across Conformance Profiles

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1017]
I added a conformance statement to a QBP profile and then when I move to the RSP profile, the same conformance statement is there too (see below). Other sections (post-test, pre-text, etc) don't seem to be affected)

![image](https://cloud.githubusercontent.com/assets/17408249/21808573/7f4042a8-d709-11e6-905a-289fbaffbfb0.png)

**Comment by csnewman88** [comment]
If you go into the RSP conformance statement editor, the QBP CS isn't listed and if you add a new one, it then shows up in the QBP message rather than the original QBP one.

![image](https://cloud.githubusercontent.com/assets/17408249/21808661/da9faa3a-d709-11e6-985c-7ea876aed57f.png)

**Comment by csnewman88** [comment]
Looks like the conformance statements are exported correctly in Word.

![image](https://cloud.githubusercontent.com/assets/17408249/21818006/d06f4f58-d72b-11e6-9777-078ba3a8f54d.png)

**Comment by Abdelghani90** [comment]
Fixed
