### ISSUE TITLE
When trying to add a segment, Segment options are limited

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1018]
When trying to add a new segment to an existing profile, it looks like the possible values for "Existing Segment" seem to be limited to the segments already in the message profile. When we build out the RSP message for example, we need to be able to add ORC, RXA and RXR, but that doesn't seem possible

![image](https://cloud.githubusercontent.com/assets/17408249/21808777/643e3de2-d70a-11e6-932d-480b6a3af660.png)

**Comment by haffonist** [comment]
The workflow is to add the segment to the IG first and then add the new segment in the message

________________________________

**Comment by csnewman88** [comment]
Makes sense. I forgot that.

**Comment by haffonist** [comment]
ok.
