### ISSUE TITLE
commit versus save

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1021]
when editing a custom value set, I'm not sure what the difference is between the Commit button and the Save button.

![image](https://cloud.githubusercontent.com/assets/17408249/21810058/ddde00e2-d70f-11e6-8e12-3ca73da20019.png)

**Comment by haffonist** [comment]
The commit fix value set and assign it a version. Will you prefer a different wording ?

**Comment by csnewman88** [comment]
I can't think of a better wording. next time we talk, let's discuss it.
