### ISSUE TITLE
uncheck all box doesn't do anything

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1023]
The "check all" box does seem to check all the boxes but the "uncheck all" box doesn't seem to do anything. 

![image](https://cloud.githubusercontent.com/assets/17408249/21810286/c82c604e-d710-11e6-9d5d-e4916a6ad03a.png)

![image](https://cloud.githubusercontent.com/assets/17408249/21810301/dc3edb5c-d710-11e6-9346-c4705432a0a0.png)

**Comment by Jungyubw** [comment]
Fixed
