### ISSUE TITLE
the check all box checks "all" the boxes

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1025]
Not sure if this the right behavior or not, but it wasn't what I expected.

For a large value set (0119 for example) that is spread over multiple pages (see green box below), selecting the "check all" box checks all the boxes on all the pages (and not just on the page being displayed as I would have expected). This could cause trouble because the user may not realize that other pages are also affected. If they want to delete just a page's worth of values, they could end up deleting all the values in the value set by accident.

![image](https://cloud.githubusercontent.com/assets/17408249/21810453/838958a6-d711-11e6-99c3-28d42456a5d6.png)

**Comment by Jungyubw** [comment]
Current logic is "Check All" means to select all of codes including not displayed codes.

We will discuss about this.

Thanks.

**Comment by Jungyubw** [comment]
Done
