### ISSUE TITLE
Cover Picture not included in the Word export

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1027]
I added a cover picture but it doesn't seem to be in the Compact Word export format

![image](https://cloud.githubusercontent.com/assets/17408249/21811054/ce749b6c-d713-11e6-9fc1-60c9000dc44a.png)

![image](https://cloud.githubusercontent.com/assets/17408249/21811079/e306370c-d713-11e6-9edb-f0c4c7766ee6.png)

**Comment by maxence-lefort** [comment]
@haffonist we can close this issue, correct?

**Comment by haffonist** [comment]
no, I am tied up with the data stuff. Can you take care of it ? You can use the handling method of the section image.
