### ISSUE TITLE
Compact Word export has blank pages

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1029]
When I exported my IG to the compact Word format, there are two blank pages between the title page and the first page of content. at least one of these should be removed unless they serve a clear purpose (some documents intentionally include a blank page but they label is "intentionally blank").

**Comment by maxence-lefort** [comment]
@haffonist should we get rid of the blank page between the table of content and the content?

**Comment by haffonist** [comment]
yes.
