### ISSUE TITLE
several formatting options aren't in the Word export

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1030]
Several formatting options aren't exported in Word:
![image](https://cloud.githubusercontent.com/assets/17408249/21811530/9e443144-d715-11e6-89bb-82a4857bfad9.png)
![image](https://cloud.githubusercontent.com/assets/17408249/21811582/d5cd7d8c-d715-11e6-8c0a-b42c5d4b397c.png)

Word:
![image](https://cloud.githubusercontent.com/assets/17408249/21811640/05a93ca8-d716-11e6-8e67-236d2e254084.png)

**Comment by maxence-lefort** [comment]
@olivier-m-mr This should be fixed with your update, correct?
