### ISSUE TITLE
Export sometimes misses a space

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1031]
If an author applies fomatting to part of a line, after the formatting ends, 1 space is removed between the formatted and unformatted text.

In the examples below, if the first word of a line is either bold or italic, the space after the formatting ends is missing in the Word export. Oddly, underlining is not affected.

If the whole line is formatted, then the spacing is just fine.

If multiple spaces are included in the line, it seems like only a single space is lost (not all of them)

This may see a bit obscure, but I use this format in the immunization guide to call attention to a header.

I'm using the "dev" flag, but this is occurring in the production IGAMT too.

![image](https://cloud.githubusercontent.com/assets/17408249/21812041/4fd2b98e-d717-11e6-9076-b846c2538f63.png)

![image](https://cloud.githubusercontent.com/assets/17408249/21812002/33088054-d717-11e6-8f77-8c85ddd083c1.png)

**Comment by olivier-m-mr** [comment]
![ig](https://cloud.githubusercontent.com/assets/7028260/21824831/23c11858-d74f-11e6-9520-3c8989f2606d.png)

html4/html5 issue. Pull request #1055 took care of if
