### ISSUE TITLE
Should MetaData be exported?

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1033]
We should talk about what the various comment, note and text fields are expected to be used for. For conformance profiles, all of the Comment, Usage Note, Pre-Text and Post-Text seem to be exported and there is no were to make author notes (not for publication). I would say at least Comment shouldn't be published. 

![image](https://cloud.githubusercontent.com/assets/17408249/21812708/69026682-d719-11e6-947b-45e7e1133a9f.png)

![image](https://cloud.githubusercontent.com/assets/17408249/21812723/76fb5eba-d719-11e6-86d4-adc4657b91e7.png)

**Comment by haffonist** [comment]
@maxence-lefort let's not export comment anywhere.

**Comment by maxence-lefort** [comment]
@haffonist It's only exported in the conformance profiles, correct?

**Comment by haffonist** [comment]
All comment everywhere (Field, Component, Datatype, Segment, valueSet, Message etc...) should not be exported.
