### ISSUE TITLE
Numbering of segments is off when adding new segment

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#1038]
I edited a group to add PRT segment at position 4. The segment is at the right position in the group, but it is displayed as "10" instead of "4".
![igamt add segment in group](https://cloud.githubusercontent.com/assets/13591511/21817699/08d3d86c-d733-11e6-8c49-a650867e10eb.JPG)

**Comment by IsmailMellouli** [comment]
@carolinerosin  Can you tell me if you still have this problem. I can't reproduce it in my end.
