### ISSUE TITLE
repeating conditional predicate

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1043]
Same issue here as for the conformance statements. The single conditional predicate is repeating multiple times in the  Word export.

As well, the table headers are off (and one short). It seems like they should be "Location", "Usage" and "Description". 

Finally, is there a reason by "predicate" is not capitalized (it is in IGAMT)? similarly, in the section before this one "statement" in "Conformance statement" is not capitalized.

![image](https://cloud.githubusercontent.com/assets/17408249/21818505/b7c60d5a-d72d-11e6-9104-f67fe5d651d4.png)

**Comment by haffonist** [comment]
@maxence-lefort, @Jungyubw  will discuss with you about it.

**Comment by maxence-lefort** [comment]
@csnewman88 The repetition issue is fixed, as well as the header. However, I don't understand the last issue about the predicate that's not capitalized, can you give me more information please? Do you want the title "Conditional Predicates" to be in upper case? Or is it something in the content of the constraints? I'm sorry if this is a simple question, I'm not very familiar with the data.

**Comment by csnewman88** [comment]
Simply that the titles "Conformance Predicate" and "Conformance Statement" with the second word capitalized along with the first one

**Comment by maxence-lefort** [comment]
@csnewman88 Ok, thanks for the clarification, it's done.
