### ISSUE TITLE
inconsistent format when referring to a data type element

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1044]
you are inconsistent in how you refer to a data type element. In just this small space you use a dash (blue arrow), period (green arrow) and nothing (red arrow) between the data type (CWE) and the element number I believe the accepted convention is to use the period for a data type (eg. CWE.4)

![image](https://cloud.githubusercontent.com/assets/17408249/21819838/ee76beb2-d732-11e6-9e7b-7525924ea920.png)

**Comment by haffonist** [comment]
@maxence-lefort 
the location of conditional predicate is wrong, it should be CWE.6 

@csnewman88 
The path in the description are already fixed but we cannot go back to existing data and change the description. At this point can you just change the description by hand ? 
Sorry for the inconvenience

**Comment by csnewman88** [comment]
this is just in a QA IG, so no issue as far as I'm concerned
