### ISSUE TITLE
DTM definition not reflected in the Word Export

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1045]
I used the Date/Time format editor to define the requirements of several DTM flavors, but those requirements aren't part of the Word export

![image](https://cloud.githubusercontent.com/assets/17408249/21820152/3c9abbba-d734-11e6-98d5-e6a6a81cd0f5.png)

![image](https://cloud.githubusercontent.com/assets/17408249/21820171/4c926d6a-d734-11e6-8be3-ce1e87fb466f.png)

**Comment by maxence-lefort** [comment]
DTM is not finished yet, we'll correct the export once it's done.

**Comment by haffonist** [comment]
@maxence-lefort we need to export as it is right now.

**Comment by haffonist** [comment]
@maxence-lefort anything on this ?

**Comment by maxence-lefort** [comment]
@haffonist not yet

**Comment by maxence-lefort** [comment]
@haffonist We need to discuss this issue tomorrow after the stand up (with @Jungyubw)
