### ISSUE TITLE
exporting only custom data type flavors?

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1051]
In verbose mode, is it intentional that only custom data types are exported? If so, why is that logic also not applied to segments and value sets?

![image](https://cloud.githubusercontent.com/assets/17408249/21821969/136ffcbc-d73b-11e6-8bed-1e66107ad79a.png)

**Comment by haffonist** [comment]
It is intentional, I think you requested this as part of you new style, correct ? 
If so we will do the same for segment.

**Comment by maxence-lefort** [comment]
@csnewman88 can you confirm that this is a requirement please?

**Comment by csnewman88** [comment]
Let's talk about it on our weekly call this morning
