### ISSUE TITLE
Can't edit Usage for a Profile Component item

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1053]
It appears that you should be able to edit the usage of an item in a profile component, but when I select a usage, it doesn't get display. I don't know if this is expected or not.

![image](https://cloud.githubusercontent.com/assets/17408249/21822386/94f56b54-d73c-11e6-9ae5-5e690fa6e019.png)

![image](https://cloud.githubusercontent.com/assets/17408249/21822433/be9282ee-d73c-11e6-9326-9ce4c67855a4.png)

**Comment by IsmailMellouli** [comment]
@csnewman88  Can you tell me if you still have this problem. I can't reproduce it in my end.
