### ISSUE TITLE
what is the use of the drop down list in the datatype cross reference view ?

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#1063]
I don't really get the use of the drop down list ?
![igamt cross ref](https://cloud.githubusercontent.com/assets/13591511/21826925/6aa00402-d757-11e6-90ff-71f95f3d31a0.JPG)

**Comment by haffonist** [comment]
@Abdelghani90 we should not allow a selection of datatype for component, we should allow it only for fields.

**Comment by haffonist** [comment]
The drop down should be disabled for components.

**Comment by haffonist** [comment]
@carolinerosin this is other way to change a datatype of a component or field.
