### ISSUE TITLE
apostrophe's not rendering right in Word export

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1102]
I've got some apostrophes in some Definition text that aren't rendering right in the Word export. This wasn't a problem in previous versions of the Word export

![image](https://cloud.githubusercontent.com/assets/17408249/21970649/18891a12-db6e-11e6-816e-ccc115c2d7d9.png)

![image](https://cloud.githubusercontent.com/assets/17408249/21970670/4ed38a26-db6e-11e6-8558-6d2d49a7fad1.png)

**Comment by maxence-lefort** [comment]
Hi @csnewman88 I can't reproduce this issue, either with the apostrophe or single quote characters. Could you please send me the ASCII code of the apostrophe character you're using? Thanks

**Comment by csnewman88** [comment]
how would I determine the ASCII code of the text in IGAMT?

**Comment by maxence-lefort** [comment]
@csnewman88 you can copy/paste in this tool: http://www.asciivalue.com/

**Comment by maxence-lefort** [comment]
@csnewman88  By the way, do you copy/paste this text from another application (Word for example) or do you type it in the tool?

**Comment by csnewman88** [comment]
Here are the ASCII values of your input:

Char	Dec	Hex	Oct
32	20	40
t	116	74	164
h	104	68	150
e	101	65	145
32	20	40
p	112	70	160
a	97	61	141
t	116	74	164
i	105	69	151
e	101	65	145
n	110	6E	156
t	116	74	164
'	39	27	47
s	115	73	163
32	20	40
d	100	64	144
a	97	61	141
t	116	74	164
e	101	65	145

**Comment by maxence-lefort** [comment]
@csnewman88 I can't reproduce the error with the exact same character. Do you take your text from a web page maybe? The HTML editor interprets HTML in the display so maybe in the text you paste, it's **&apos;** (HTML code for the apostrophe character) instead of the **'** character, so you see it as **'** but the content saved is **&apos;**. @haffonist do you have a way to check what's saved in the database maybe?

**Comment by maxence-lefort** [comment]
Here's how it's rendered on my end:
<img width="797" alt="screen shot 2017-01-18 at 3 45 12 pm" src="https://cloud.githubusercontent.com/assets/13853131/22082289/2a2f5a8c-dd95-11e6-9fe1-5ae8c25bc7f1.png">

**Comment by haffo** [comment]
@csnewman88 what is the name of your guide ? we will look in the database to see what are the real characters saved to the base.

**Comment by csnewman88** [comment]
My IG is called:
	HL7 Version 2.8.2 Implementation Guide: Immunization Messaging with enhanced query

The text is Definition Text for PID-7 in PID_IZ_01
![image](https://cloud.githubusercontent.com/assets/17408249/22082757/ac3ceb72-dd8e-11e6-8fa2-0a471f824135.png)

some of the text is cut and paste out of other documents (usually a Word document) and some of the text is direct entered.

**Comment by csnewman88** [comment]
The odd thing is that I outputted the same text (I haven't changed in months) on 11/23 and it rendered just fine.

![image](https://cloud.githubusercontent.com/assets/17408249/22084037/2358c816-dd94-11e6-84a7-923e2555e3ff.png)
