### ISSUE TITLE
Exporting error

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1103]
I am getting this error when I attempt to export the VR IG in word and also HTML

{"text":"internalError","resourceId":null,"manualHandle":"false","skip":false,"date":null,"version":null,"scope":null,"id":null,"type":"danger"}

**Comment by haffonist** [comment]
@maxence-lefort any idea ?

**Comment by maxence-lefort** [comment]
@haffonist I would need to see the logs, there might be a data issue somewhere causing a null pointer exception.
