### ISSUE TITLE
Lengths and Conformance Length of 0 cause confusion

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1126]
We've had several folks ask what lengths and conformance lengths of 0 or 0..0 mean (see below in red). In part, I'm sure this stems from not understanding their usage (not 100% sure I fully understand them), but the export does populate these elements where the base standard does not in either documentation (compare the documentation of the CWE data type in the two screen shots below). I think not populating these cells in the export of data types and segments would be less confusing for readers.

![image](https://cloud.githubusercontent.com/assets/17408249/22215726/0a9d0ee6-e162-11e6-8b0f-2998a2d8c160.png)

![image](https://cloud.githubusercontent.com/assets/17408249/22215842/7455735a-e162-11e6-8749-a91469d6e70d.png)

**Comment by haffonist** [comment]
@csnewman88 how do we know when not to populate ? is it when minLenght=maxLenght=0 ?

**Comment by csnewman88** [comment]
I guess so. How is it represented in Frank's database? does he have the zeros or are they blank?

**Comment by haffonist** [comment]
What hl7 version is it ?

**Comment by haffonist** [comment]
I think it is 2.7, correct ?

**Comment by csnewman88** [comment]
2.8.2 I think

**Comment by haffonist** [comment]
The value are NULL or empty in Frank's DB.

@maxence-lefort, 
Display no value for conflength with value=0 (or value="0") and no value for Lenght with minLength=maxLenght=0.
 
Thanks
