### ISSUE TITLE
data type name format

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1127]
Sorry if this is a duplicate. I feel like we discussed it before.

I think the convention is that data type element identifiers are the data type, a period and then the sequence ID. So the first component of CWE is CWE.1. In the current exports a dash is used rather than a period.

Also note that in the export, there is no space between the data type element name (CWE-1) and the colon separator and the description (Identifier). This makes it a bit difficult to read and Microsoft Word questions it (blue underlining). It would be better if there was more white space (see the second screenshot below to see how it looks in the segment section)

![image](https://cloud.githubusercontent.com/assets/17408249/22216478/dd7b2d00-e164-11e6-9cc8-4b863fad8185.png)

The convention for segment elements is the segment name, a dash and then the element number. So the first field in PID is PID-1. The export use the right bits and pieces, but seems to have extra space between them (PID - 1 as opposed to PID-1).

![image](https://cloud.githubusercontent.com/assets/17408249/22216589/495ed63e-e165-11e6-845d-c92c8cc9d073.png)

**Comment by haffonist** [comment]
@maxence-lefort please fix.
