### ISSUE TITLE
How to handle DR/TS/DTM issue 

### ISSUE THREAD

**Issue by Jungyubw** [haffonist/igamt#1142]
Possible solutions to handle the issue of 5 levels of nesting due to a mistake in some versions of the standard.

We could write code to detect when the 5 level nesting occurs. Assuming it is only for the case of a field with component that has a DT of DR and then a TS (which contains a DTM), we could just substitute DTM for TS. Another solution is to create another DT called TS_FIXED which is a primitive and mirror the specification for DTM.

So after we pull the data from DB we can run a script to detect these locations and perform the substitution.

**Comment by haffonist** [comment]
Adding @robnist for reference.
