### ISSUE TITLE
Create Advanced Export Logic

### ISSUE THREAD

**Issue by haffonist** [haffonist/igamt#1153]

**Comment by haffonist** [comment]
@maxence-lefort @Abdelghani90 please schedule design meeting asap.

**Comment by haffonist** [comment]
![img_4988](https://cloud.githubusercontent.com/assets/13695248/22444327/71cf40ee-e710-11e6-80dd-4af4150c1396.JPG)

**Comment by haffonist** [comment]
**4 Modes:**
- Verbose
- Compact
- Table Definitions Only 
- Delta Only 

For each of this mode, the critiera are the following: 

**Messages:** 
_- Usage:_ 
SegmentRef, Groups: (R,RE,C) or All. This determines which segmentRef or groups we should include in the export.
Segments: (R,RE,C) or All: This determines which segments(MSH, OBX etc...) we should include in the export
_- Columns:_ The different Options(Lenght, Conf Lenght etc..) This determine which optional columns should be included in the export of the messages definition tables

**Segment**
_- Usage:_
      _Fields : (_R,RE,C) or All. This determines which fields should be included in the export 
      _Data types_ (R,RE,C) or All: This determines which datatypes (HD, ST etc...) should be included in the export
_- Columns:_ The Options(Length, Conf Length, Comments etc..) This determine which optional columns should be included in the export of the segments definition tables
_- Flavors:_ ALL, ALL_HL7STANDARD, ALL_BOUNDS, ALL_BOUND_FLAVORS. This determine which segments to include in the export. This filter on segments coming from the messages in previous step

**Data type**
_- Usage:_
_- Components :_ (R,RE,C) or All. This determines which components should be included in the export 
_- Columns:_ The Options(Length, Conf Length, Comments etc..) This determine which optional columns should be included in the export of the segments definition tables
_- Flavors:_ ALL, ALL_HL7STANDARD, ALL_BOUNDS, ALL_BOUND_FLAVORS. This determine which data types to include in the export. This filter on data types coming from the segments in previous step

**Comment by maxence-lefort** [comment]
@haffonist Do you have the specifications from Rob? We can't start the design without it

**Comment by haffonist** [comment]
[ExportReq.pptx](https://github.com/haffonist/igamt/files/745430/ExportReq.pptx)

**Comment by haffonist** [comment]
I am closing this since we create more specific tickets
