### ISSUE TITLE
upon export, some tables have extra white space

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1160]
In some tables (but not all of them apparently), upon export to a Word document, there are extra line breaks which adds white space to the table. For example, compare the table in IGAMT to the table in Word. the red arrows indicate places where there are extra line breaks and white space. It's easy enough to remove, but I'm not sure where they are coming from in the first place.

![image](https://cloud.githubusercontent.com/assets/17408249/22430824/0cdd254c-e6d5-11e6-8edd-2be4a3914959.png)

![image](https://cloud.githubusercontent.com/assets/17408249/22430758/d1c7949c-e6d4-11e6-9500-50515a2b55f9.png)

**Comment by afrold** [comment]
@maxence-lefort did you have a chance to look at this ?

**Comment by maxence-lefort** [comment]
Not yet

**Comment by maxence-lefort** [comment]
@csnewman88 Do you still notice this issue in the Word export? I did some changes since you created this issue and most of the extra white spaces should be gone. Please let me know if some are remaining. Thanks!

**Comment by csnewman88** [comment]
@maxence-lefort 
Looks like there are still a few issues. There is less white space, but still some remaining.

![image](https://cloud.githubusercontent.com/assets/17408249/25092627/2a553086-2354-11e7-8e20-8aa16719efb5.png)

**Comment by maxence-lefort** [comment]
@csnewman88 thanks for the update, I'll have a look at it again.

**Comment by maxence-lefort** [comment]
@csnewman88 I had a look at this issue and it looks like those table were copied/pasted from another source, not created directly in the tool's editor. I did however push a fix to resolve the extra line added in the Word document, it should be available for you to test after the next deployment.
Thanks
