### ISSUE TITLE
No scroll bar for column selection option

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#1170]
I can't scroll down to remove length, conf length, etc.

The search here makes no sense and neither the scroll bar. This should just be a static list in which the user sees all and can select. But as stated in issue 1168 these options should not even exist--that is some of the columns make no sense at this level.

![image](https://cloud.githubusercontent.com/assets/14874904/22468286/b991269c-e795-11e6-9bd6-5a282346b8ba.png)

**Comment by robnist** [comment]
meant to indicate issue 1169 not 1168.

**Comment by haffonist** [comment]
as I answer on issue 1169, the columns are needed for fields and components. Please expand the nodes and you will see what I mean. We will fix the scroll bar and add the confLength to the list.
