### ISSUE TITLE
Analyze which elements should have a value set

### ISSUE THREAD

**Issue by haffonist** [haffonist/igamt#1177]

**Comment by carolinerosin** [comment]
So here's a list of datatypes and elements where we should allow the user to add a value set.

Primitive datatypes : ID and IS
All those complex datatypes : CE, CF, CWE, CNE, HD

Complex datatypes that have elements that should be allowed to have a value set :

![image](https://cloud.githubusercontent.com/assets/13591511/22667258/08c4e674-ec8a-11e6-8c30-78e4f258be63.png)

**Comment by carolinerosin** [comment]
we may add or remove some elements, but that is a starting point

**Comment by Jungyubw** [comment]
Okay I will make a kind of configuration to update the list.

Thanks.


Jungyub


On Feb 6, 2017, at 4:46 PM, Caroline Rosin <notifications@github.com<mailto:notifications@github.com>> wrote:


we may add or remove some elements, but that is a starting point

**Comment by Jungyubw** [comment]
@carolinerosin 

Could you clarify options of Binding location for code able complex DTs?

For example, CE, CWE, CNE are 
1
4
1 or 4
right?

What about HD and CF?

Thanks.

**Comment by Jungyubw** [comment]
Done

**Comment by carolinerosin** [comment]
For clarification and documentation purposes
1. List of datatypes where user should be able to add a value set: 
Primitive: ID, IS 
Complex, binding location "1","4", "1 or 4" : CE, CF, CWE, CNE, 
Complex, binding location "2" ,"5"," 2 or 5" : CSU
Complex, binding location "1" :  HD

2. List of elements (components or subcomponents) that are ST or NM and where the user should be able to add value set (at the element's level):
![image](https://user-images.githubusercontent.com/13591511/32747884-43566abc-c888-11e7-86ef-5c471f67394e.png)

**Comment by carolinerosin** [comment]
For clarification and documentation purposes:

3. List of fields that are ST or NM and where the user should be able to add value set 
PID-23 (Birth Place) (ST)
