### ISSUE TITLE
Tables in Definition Text isn't exported well

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1181]
If an author puts a table in a Definition Text, when it's exported to a Word document, the borders of the table are not included. Nor is the header row formatting. It's a table and the borders can be added manually in Word, but Tables in Definition Text and in the normal text boxes export differently.

![image](https://cloud.githubusercontent.com/assets/17408249/22475189/c6e37abc-e7a3-11e6-812d-d1f49fb74c36.png)

![image](https://cloud.githubusercontent.com/assets/17408249/22475271/0dfb693c-e7a4-11e6-8dea-a1bea87ccafd.png)

**Comment by haffonist** [comment]
@maxence-lefort why are we having this old issue again ?

**Comment by haffonist** [comment]
@maxence-lefort it is not an issue from the froal styling since this happens only for definition text of component and field. So I think it has do to with the processing of those fields. 
Please take a look at this.
