### ISSUE TITLE
CP out of order

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1183]
When list the condition predicates, I think it makes sense to list them in the order of their location. I'm not sure how the order is determined today, but it's not by location in either IGAMT or the Word export. Listing them by location will make it easier for readers to find them.

![image](https://cloud.githubusercontent.com/assets/17408249/22475628/2db716b2-e7a5-11e6-9c0d-d1a00f97a944.png)

![image](https://cloud.githubusercontent.com/assets/17408249/22475685/5d5fec04-e7a5-11e6-9e7b-4c482497954c.png)

**Comment by haffonist** [comment]
@Jungyubw order by location in IGAMT
@maxence-lefort order by location as well in the export(html +word)

**Comment by maxence-lefort** [comment]
@Jungyubw any update on this issue?

**Comment by Jungyubw** [comment]
Not yet, will do

**Comment by Jungyubw** [comment]
Done
