### ISSUE TITLE
extra white space in the data type section of the Word Export

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1186]
In the Word export, there is a lot of extra whitespace between the sections. I think at most, a single line of space between any two sections is probably sufficient.

![image](https://cloud.githubusercontent.com/assets/17408249/22476461/1f256e20-e7a8-11e6-925a-bca46427af73.png)

**Comment by haffonist** [comment]
@maxence-lefort did you see this ? 
Thanks

**Comment by afrold** [comment]
@maxence-lefort did you have a chance to look at this ?

**Comment by maxence-lefort** [comment]
Not yet

**Comment by maxence-lefort** [comment]
@csnewman88 Do you still notice this issue in the Word export? I did some changes since you created this issue and most of the extra white spaces should be gone. Please let me know if some are remaining. Thanks!
