### ISSUE TITLE
Complex CS

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1189]
I am creating a complex constraint, the tool does not prevent the user from creating the following type constraint.  Should the tool only allow the "is" and "is not" verbs for the IF statement? is this statement processable?

IF [The value of MSH-1(Field Separator) **SHALL be** 'xxx'.] THEN [The value of MSH.2 (Encoding Characters) SHALL be 'xxxx'.]

**Comment by Jungyubw** [comment]
Fixed.

Predicate Verb is "is" or "is not" only. 

In the Conformance Statement, the verb will be automatically changed to "is" or "is not" when it is used for complex IF statement.
