### ISSUE TITLE
Complex CS vs temporary constraints

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1202]
To build the complex conformance statements the user must create  temporary constraints. I assume most of the time these constraints are not going to be reused. They are temporary and after construction of the complex CS the user remove them.  If these are not removed it can create confusion, currently the are included in the list of completed CSs.  A suggestion is to create a "Temporary Constraints"and give the user the option of removing it when finished. Just a suggestion for consideration.

**Comment by Jungyubw** [comment]
Fixed
