### ISSUE TITLE
Saving data types in a data type library

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1233]
I created a user data type library and created a couple of data type flavors. I edited one but when I went to save it, I noticed that even though I changed some usages and added Pre-Text, the Save button didn't light up. It looks like I could Publish it, but I'm not sure I'm ready to do that. 

What would a user have to do in order to get the Save button to light up?

![image](https://cloud.githubusercontent.com/assets/17408249/22896481/e2a1057a-f1e5-11e6-9ae3-5b1d57f1113e.png)

**Comment by csnewman88** [comment]
Note that this seems to be a problem in the IG editor too. The Save button doesn't light up when changes are made. If you try and navigate away from the data type, it does give you the option to save and move on. The changes do appear to be saved.

**Comment by Abdelghani90** [comment]
we will fix that ASAP. Thanks for reporting

**Comment by Abdelghani90** [comment]
@haffo This is fixed

**Comment by haffonist** [comment]
Thanks Abdel. next time please move to QA Testing.
