### ISSUE TITLE
Question: I don't understand Segment # dropdown

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#1234]
What is this for?

![image](https://cloud.githubusercontent.com/assets/14874904/22896531/8640988c-f1ee-11e6-9287-71a73886f81b.png)

**Comment by haffonist** [comment]
position.

**Comment by robnist** [comment]
Yeah, but what is it for? Change the segment position from what was 4 to 23? Doesn't make any sense.

**Comment by haffonist** [comment]
You agreed on this sometime ago to allow this change. You also wanted at one point to restrict it to Query/Response messages.

**Comment by robnist** [comment]
YEs.

Only allow for QBp, RSP, QVR.

**Comment by robnist** [comment]
New ticket created
