### ISSUE TITLE
should it be possible to delete a published data type?

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1235]
It seems odd that you can delete a published data type. Is this only allowed if the data type isn't used in any document?

![image](https://cloud.githubusercontent.com/assets/17408249/22896558/4106660a-f1e6-11e6-87ea-a58299a1fbea.png)

Also note that even after the data type is deleted, the main panel still shows the data from the deleted data type (note the red box). It's even possible to navigate between the different tabs (Data Type Definition, Version History, etc) even though the data type doesn't exist any more. Presumably, once a data type is deleted, all the data in the Edit Area should be reset.

![image](https://cloud.githubusercontent.com/assets/17408249/22896701/ae2e16ba-f1e6-11e6-83f6-7637e7528423.png)

**Comment by afrold** [comment]
Yes for now.
