### ISSUE TITLE
Add Library Data Types to an IG

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1238]
Adding a data type from a User Library to an IG is confusing me.

I can create an publish a data type in my User data type library
![image](https://cloud.githubusercontent.com/assets/17408249/22897072/e0c0a22c-f1e7-11e6-9410-8116d09b4793.png)

But in the when I add the User Library data type, the ID changes (CX_331 versus CX_622) and it doesn't give any indicate that it is a shared library data type. Plus it looks like it's possible (or required??) to publish it again.
![image](https://cloud.githubusercontent.com/assets/17408249/22896997/a06b8958-f1e7-11e6-9be8-63b03ddf4c41.png)

How do you envision users adding data types from libraries to an IG?

**Comment by Abdelghani90** [comment]
I think you made the choice to add this datatype as a flavor, for this reason you have another extension.

**Comment by csnewman88** [comment]
That makes sense. I tried adding "as is" and it behaves as I expected. Thanks.
