### ISSUE TITLE
Can't add Conformance Statement to PC

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#1239]
I want to add a CS at these locations--how do I do it?

![image](https://cloud.githubusercontent.com/assets/14874904/22897457/a0795538-f1f1-11e6-9701-6ada64047376.png)

**Comment by robnist** [comment]
This is for a profile component.

**Comment by haffonist** [comment]
We do not support that yet. It will be next.

**Comment by Jungyubw** [comment]
Done
