### ISSUE TITLE
what data types should be OK to use in other data types?

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1242]
In my user library I created or imported 3 different ST data types (2.7 version, 2.8.2 version and custom version based on the 2.7 version (see red arrows below). But when I went to edit a data type using the ST data type and tried to change the ST data type only 2 of the 3 ST flavors showed up (see green box). What I found odd was that even though the EI data type flavor I was editing was based on version 2.7, the versino 2.7 ST was not an option although I could use the version 2.8.2 ST. It seems like if the data type list is going to be limited, you might want to limit it to data types ultimately derived from the same data type. How do you decide what data types are available to use?

![image](https://cloud.githubusercontent.com/assets/17408249/22898275/3c49ecda-f1ec-11e6-8198-be157c451eaa.png)

**Comment by haffonist** [comment]
Correct. Will be fixed.
