### ISSUE TITLE
selecting the blank option for a data type

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1243]
When I edit the data type of a data type component, there is a blank option. I don't understand what this is supposed to represent.

In this example, the data type starts out as the default ST (although note, that the version of the ST data type is not shown)
![image](https://cloud.githubusercontent.com/assets/17408249/22898655/b4d342fe-f1ed-11e6-85dd-0e3363fe0dba.png)

But if the user selects the blank option:
![image](https://cloud.githubusercontent.com/assets/17408249/22898674/c92590fe-f1ed-11e6-8252-5b821aae1adf.png)

The data type changes:
![image](https://cloud.githubusercontent.com/assets/17408249/22898737/fef56c0e-f1ed-11e6-8d23-b36a924803b9.png)

I would expect that if the blank option is selectable, that it would maintain the status quo, but it doesn't seem to. What is the intent of this blank option?

**Comment by haffonist** [comment]
@IsmailMellouli please fix.
