### ISSUE TITLE
Action column in a published value set

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1245]
When a published value set is imported as part of a data type, there is an Action column in the Value Set Definition display. What is this intended for? If there is no action a user could take on a published value set (I don't know what sort of action should be allowed), then this column doesn't really do much and should be removed.

![image](https://cloud.githubusercontent.com/assets/17408249/22900084/b981ddce-f1f2-11e6-951a-88f45d3c72e9.png)

**Comment by haffonist** [comment]
I agree. @Abdelghani90 please remove for published value set.
