### ISSUE TITLE
add functionality to upgrade to a new version

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1247]
This warning is nice, but long term is there a plan to introduce a way to easily upgrade to the new version? Something that would automatically replace all instances of the old data type version with the new one? At the version least, will there be a way to make this header go away after it's been acknowledged?

![image](https://cloud.githubusercontent.com/assets/17408249/22902695/8607fae2-f1fb-11e6-8aec-3e6caea7bd6b.png)

**Comment by Abdelghani90** [comment]
if you open the "Version History", you can compare your versions, move from a version to another, import a new version if you don't have it in your IG.

**Comment by csnewman88** [comment]
A note in the header to visit the "version history" tab would be a nice reminder.

One other suggestion would be that when you click the "upgrade" button to move from an older version to a newer version, having a list of the elements that will change would be helpful (and maybe allow the user to select the ones they want). The current wording is that "all" instances will change, but that's not exactly true if the data type is part of another published data type (ie ST is used in EI). In this case, the complex data types are not updated (which makes sense but is inconsistent with the description of what will happen).

**Comment by afrold** [comment]
Done.
