### ISSUE TITLE
add scroll bar to data type evolution box

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1260]
It would be nice if the Data Type Evolution by HL7 Version box in the data type library section had its own scroll bars. It starts out OK but as soon as you scroll the window down to see data types lower in the list, you lose the column headers and it's hard to remember which version a column corresponds with.

![image](https://cloud.githubusercontent.com/assets/17408249/22984558/5b484610-f36b-11e6-8427-c80f36e77132.png)

![image](https://cloud.githubusercontent.com/assets/17408249/22984670/bebf7402-f36b-11e6-93a5-fef88dca51ec.png)

**Comment by Abdelghani90** [comment]
Thanks for reporting, we are going to fix this.
