### ISSUE TITLE
version indicator for published value sets

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1266]
In the data type library activity, when a data type is published the version number is shown in the Table of Contents (purple arrow) to indicate that it's been published. However, when a custom value set is published (green arrow), the version icon does not show up in the Table of Contents (red arrow). Is there a reason for that difference? If not, I think adding the version to the value set makes sense.

![image](https://cloud.githubusercontent.com/assets/17408249/22992293/de6a40ca-f384-11e6-86db-3c64d07c5430.png)

**Comment by Abdelghani90** [comment]
You are right, it should appear, I will fix it

**Comment by Abdelghani90** [comment]
the value sets will not be displayed in the master datatype library anymore
