### ISSUE TITLE
version when adding a master library data type to an IG

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1268]
When adding a data type to an IG from a master library, how is the version (purple box) choosen? In this case, the data type is compatible with multiple versions. My IG is based on 2.8.2, so I'd prefer that the version (if it even needs to be selected or shown anywhere) match as close to my IG as possible

![image](https://cloud.githubusercontent.com/assets/17408249/22993610/32ce8424-f389-11e6-8b03-18d8de962c6f.png)

After I add the data type, it looks out of sync with the rest of the data types in my IG because it's version 2.7 rather than 2.8.2
![image](https://cloud.githubusercontent.com/assets/17408249/22993731/b480f9d4-f389-11e6-9a6a-c85fbe3dfa32.png)

**Comment by Abdelghani90** [comment]
You are right. Thanks for reporting it is fixed now and will be deployed ASAP
