### ISSUE TITLE
Missing Usage Note in master type library

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1269]
In the Master Library activity, when defining a new data type, there is a spot for a Usage Note, but the text box to enter a usage note is not there, it's just blank white space.

![image](https://cloud.githubusercontent.com/assets/17408249/22994557/f45b71b2-f38c-11e6-88f8-c367a82f9f86.png)

**Comment by Abdelghani90** [comment]
will be fixed ASAP
