### ISSUE TITLE
how are extensions assigned?

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1272]
When adding data types to a master data type library, how are the extensions initially determined? Most of them are "1" but there are a handful of 2's and 3's as well. I added most of the data types at once, so I'm not sure why they should vary. I expect most author's will edit them anyway, but I was wondering where they came from.

![image](https://cloud.githubusercontent.com/assets/17408249/23029240/6dfb35a0-f42f-11e6-8169-e17efc6769d9.png)

**Comment by Abdelghani90** [comment]
the extension is auto-incremented. if there is a master datatype X_1 for the versions [2.5 ..2.7], the next time if we want to create a new master datatype for the same set of versions,  the provided extension  will be X_2. A master user can always change those names.
