### ISSUE TITLE
Definition Post-Text doesn't work for master data type libraries

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1273]
When you click on the Definition Post-Text, you don't get the box to enter in your text.

![image](https://cloud.githubusercontent.com/assets/17408249/23030965/f9ec0774-f434-11e6-8005-550d7821e184.png)

**Comment by csnewman88** [comment]
Definition Pre-Text doesn't work either

**Comment by Abdelghani90** [comment]
Thank you for reporting I will fix it
