### ISSUE TITLE
Possible error in the underlying data base

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1293]
When I imported the DR data type from version 2.5.1 into a data type library, the two components has the DTM data type.

![image](https://cloud.githubusercontent.com/assets/17408249/23075010/78254ad0-f500-11e6-843c-a7fd0dab90b0.png)

But if you look at the 2.5.1 base document (chapter 02A), the components have the TS data type.
![image](https://cloud.githubusercontent.com/assets/17408249/23075051/a18cb782-f500-11e6-8371-05e3f134510b.png)

Because there are limits on how dramatically a user can change the data type, it's not possible to correct this issue in IGAMT manually.

**Comment by haffonist** [comment]
Yes, this is a know issue and fix is ready for deployment.

**Comment by haffonist** [comment]
After o

**Comment by haffonist** [comment]
I need to close since it is a duplicate.
