### ISSUE TITLE
Conformance statement IDs don't appear to update immediately

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1305]
In the Data Type library activity, if you edit a conformance statement ID, it doesn't appear to immediately update. This can cause confusion for users as it appears that they changes were lost.

If we start like this:
![image](https://cloud.githubusercontent.com/assets/17408249/23184055/cdea506e-f843-11e6-9f06-ff64cb488bf3.png)

And then make this change:
![image](https://cloud.githubusercontent.com/assets/17408249/23184090/f7f06ee8-f843-11e6-9dd3-1f2508cff631.png)

After clicking "Save" in the CS editor, it still looks like this:
![image](https://cloud.githubusercontent.com/assets/17408249/23184113/145e63e6-f844-11e6-8024-4472331d3b07.png)

But if you go to a different data type (forcing another save of the data type) and come back, the changes are visible:
![image](https://cloud.githubusercontent.com/assets/17408249/23184154/43c1e996-f844-11e6-8469-e0ca4bdc6532.png)

**Comment by Jungyubw** [comment]
Fixed
