### ISSUE TITLE
Error when I try to display my conformance profile

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#1310]
Here's a screen shot of the error, not sure what happened. Conformance profile does not display
![igamt error](https://cloud.githubusercontent.com/assets/13591511/23186549/89ae0e10-f855-11e6-96e1-7b1a7cf29250.JPG)

**Comment by haffonist** [comment]
This should be during our deployment tonight.

**Comment by carolinerosin** [comment]
Not sure if this is supposed to be fixed, but I am still getting the issue. Is there something I should do ?

**Comment by haffonist** [comment]
Caroline, 
Right click on "Datatypes" and add "ST" data type to your ig document and it should work.

**Comment by carolinerosin** [comment]
it works, thanks !
