### ISSUE TITLE
Data issue for HL7 2.5.1, ORU_R01 structure

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#1314]
I created an IG document with the ORU_R01 message structure from version 2.5.1.
The message structure in IGAMT seems wrong : all the groups are required (R) with a cardinality of [1..1]

IGAMT structure:
![igamt oru structure](https://cloud.githubusercontent.com/assets/13591511/23223296/a9ba63d6-f8f8-11e6-91d2-5ae18f7c04ca.JPG)

HL7 v2.5.1 ORU R01 structure (from chapter 7)
![hl7 oru 1](https://cloud.githubusercontent.com/assets/13591511/23223380/e965ddd0-f8f8-11e6-87ad-6c7807ddd70e.JPG)
![hl7 oru 2](https://cloud.githubusercontent.com/assets/13591511/23223385/ebcc87a4-f8f8-11e6-9996-314c7d4da7f2.JPG)

**Comment by haffonist** [comment]
Ok, this is fixed and will be redeployed tonight. 
Thanks

**Comment by haffonist** [comment]
Should be fixed now.
