### ISSUE TITLE
Not able to export the Vital Records IG

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1317]
I am still not able to export the VR IG.

**Comment by Jungyubw** [comment]
I will check it again.



On Feb 22, 2017, at 5:42 PM, smartinez290 <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #1317<https://github.com/haffonist/igamt/issues/1317> to @Jungyubw<https://github.com/Jungyubw>.

**Comment by Jungyubw** [comment]
Done.

@smartinez290 Please wait for next deployment or You can manually change your title with using AlphaNumeric.

Thanks.
