### ISSUE TITLE
Per Mead Walker - Export  is generating errors 

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1322]
There are three styles, the IG style seems the one for me.    I think it crashed.   Here what I get:

{"text":"internalError","resourceId":null,"manualHandle":"false","skip":false,"version":null,"date":null,"scope":null,"id":null,"type":"danger"}

This sits in the following tab: https://hl7v2.igamt.nist.gov/igamt/api/igdocuments/5898caa884ae9be46ff21abc/export/docx/IgDocument

So I tried profile style – the same.

Table style took longer, and looks like it did download. 

I am attaching a copy.  Note, I only put in some of the profiles.  It looks OK, but has none of the introductory text sections.

[Birth-Death-Report-IG-5898caa884ae9be46ff21abc_20170224_140730.docx](https://github.com/haffonist/igamt/files/800273/Birth-Death-Report-IG-5898caa884ae9be46ff21abc_20170224_140730.docx)

**Comment by haffonist** [comment]
This should be fixed now in the current deployed version of the tool.
