### ISSUE TITLE
Mechanism for Dynamic Mapping no longer available

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1331]
I am looking at the IG Mead Walker is developing and I do no see a mechanism to enter dynamic mapping in OBX-5. It was there before.

![dyn](https://cloud.githubusercontent.com/assets/14842422/23481771/a7bfe202-fe9a-11e6-911a-ecf92eea2d22.png)

**Comment by Jungyubw** [comment]
@smartinez290 Fixed. wait for next deployment.

Thanks.
