### ISSUE TITLE
Sorting mechanism missing

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1332]
Per Rob and Mead -- Please add sorting mechanism for the co-constraint table, conformance constraints and profile components. Anywhere a bunch of things are added, the user needs to be able to change the ordering.

**Comment by afrold** [comment]
Sorting is already implemented for profile component.

**Comment by afrold** [comment]
@Jungyubw is sorting implemented for co-constraint ?

**Comment by Jungyubw** [comment]
No. I will do later.

**Comment by Jungyubw** [comment]
Sorting (By ID) is already implemented for Conformance Statements.
Sorting (By Location) is already implemented for Predicate.

I am working for Sorting (By If-value) for Co-Constraints.

**Comment by smartinez290** [comment]
Was this implemented? I am not sure how to test it.

**Comment by Jungyubw** [comment]
I will show you.

**Comment by smartinez290** [comment]
The icon for sorting is not visible at first. It only becomes visible when I click on it.

**Comment by smartinez290** [comment]
The sorting is there, but the minor issue of not seeing the icon for sorting is still there and the drag-gable icon in the co-constraint table is still white, per Rob request it should be black to keep consistency.
