### ISSUE TITLE
Create Example Document JSON from Profile

### ISSUE THREAD

**Issue by Jungyubw** [haffonist/igamt#134]

**Comment by Jungyubw** [comment]
Done,

All, please review this IG Document Json.


[IGDocument.json.zip](https://github.com/haffonist/igamt/files/87856/IGDocument.json.zip)

**Comment by haffonist** [comment]
Thanks Woo,
See my comments below:

"profile" : {
        "_id" : ObjectId("5668a21c3004b6719c64af1f"),
        "scope" : "USER",
        "metaData" : {
            "name" : "VXU V04 Implementation Guide",
            "identifier" : "CDC IG_VXU_V04 Release 1.5",
            "subTitle" : "NIST",
            "version" : "1.0",
            "orgName" : "NIST",
            "status" : "",
            "topics" : "",
            "type" : "Constrainable",
            "hl7Version" : "2.5.1",
            "schemaVersion" : "",
            "date" : "2015/12/09 16:50:19",
            "ext" : "",
            "encodings" : [
                "XML",
                "ER7"
            ]
        },


1) Things in orange should not be there but instead under the document.
2) the accountId should stay a Long (0)
3) rename documentMetaData to metaData.

Harold


________________________________

**Comment by Jungyubw** [comment]
Harold, what are the things in orange? I cannot see the color.

**Comment by haffonist** [comment]
I sent from my email and github removed the orange color. I just send it to your email.


________________________________
