### ISSUE TITLE
Export: Diagrams too big

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1340]
The diagram is being blown up too big, so it does not fit on the page.   
![diag](https://cloud.githubusercontent.com/assets/14842422/23526651/d877c312-ff60-11e6-9d4b-3912800a7b1d.png)

**Comment by haffonist** [comment]
@maxence-lefort any idea, I know rob agree that the user should go to the document and edit things such as this, but may be we can do something about it ??

**Comment by maxence-lefort** [comment]
@haffonist I think @olivier-m-mr found a solution for this?

**Comment by maxence-lefort** [comment]
@smartinez290 @csnewman88 This has been an issue for a long time but we finally found a way to resize the images. Please test again after the next deployment and let me know if you still have oversized images.
