### ISSUE TITLE
Export: Segment Metadata - Comment - missing from export

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1341]
The Segment Metadata tab includes a place – Comment – to enter descriptive text for the segment or segment flavor.   However, this does not appear within the Word export.  It should.

**Comment by maxence-lefort** [comment]
@haffonist Should we add again the comments at all the levels? Rob told us to get rid of it in the export as this is supposed to be a comment for the author only to put notes for himself

**Comment by afrold** [comment]
No the comment at that level is a metadata so does not go to the export. Use pre def or post def if you want it to be exported.
