### ISSUE TITLE
Can't Export the Vital Records Death Reporting IG in Word

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1357]
I am getting this error:
{"text":"internalError","manualHandle":"false","resourceId":null,"skip":false,"date":null,"version":null,"scope":null,"id":null,"type":"danger"}

**Comment by maxence-lefort** [comment]
@smartinez290 can you please send me and e-mail with the url it tries to reach when you export?
It looks like https://hl7v2.igamt.nist.gov/igamt/api/igdocuments/76t7834bchrebhvc/export/docx/IgDocument

**Comment by smartinez290** [comment]
https://hl7v2.igamt.nist.gov/igamt/api/igdocuments/57450d2ad4c6f57e697ab7e3/export/docx/IgDocument
