### ISSUE TITLE
Changing usage of field crashes the tool

### ISSUE THREAD

**Issue by ncrouzier-nist** [haffonist/igamt#1397]
When I change the usage of a field (from R to C or O for example) the tool freezes and the tab is unresponsive until it is killed. Changes are not saved as well.
Occurs on both Chrome and Firefox (on Mac OS)

Seems to happen only on newly created segment flavors.

**Comment by ncrouzier-nist** [comment]
This now seems to work...

**Comment by haffonist** [comment]
I think it is related to the tool becoming slow after some time. We will improve performance in two or three iterations.
