### ISSUE TITLE
Exporting Value Set meta data

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1409]
Per Rob: The user should be given the option of including the Value set meta data in the value set table.
Also, the description in the meta data should not be included next to the value set name. 

![valuesetmetadataexport](https://cloud.githubusercontent.com/assets/14842422/24013183/f82c4fa6-0a56-11e7-9af1-6046e9091b87.png)

**Comment by haffonist** [comment]
what about the datatype, segment, message, we are doing the same everywhere.  For consistency we should keep the same everywhere. 
@robnist what do you say ?

**Comment by haffonist** [comment]
We are adding the metadata options for next iteration.
