### ISSUE TITLE
enhanced data type export configurations

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1410]
The export configurations for data types could probably still use some tweaking. 

In the example below I've configured things to export all data types and you can see there are a lot (as expected).
![image](https://cloud.githubusercontent.com/assets/17408249/24013276/df09c240-0a4e-11e7-9694-74cc896d875e.png)

In the example below, I've restricted the export to just R/RE/C data types (excluding O/X - see red box). While many data types that were exported in the first example are not exported here (AUI, CP, CQ, etc) several non-custom data types were exported that I didn't expect. In my IG, any R, RE or C element was updated to use a custom data type, so I expected only custom data elements to be exported but that wasn't the case (see arrows). 
![image](https://cloud.githubusercontent.com/assets/17408249/24013258/ce3fb74e-0a4e-11e7-9146-460c699d8e65.png)

I'm assuming that the CWE data type (and others I checked) was exported because it is used in several R fields (see red box below). The problem is that these required fields are either in segments which are themselves optional (DG1) or not used at all (I've cloned QPD to create a custom segment (QPD_IZ) which I use instead).
![image](https://cloud.githubusercontent.com/assets/17408249/24013386/365e4f70-0a4f-11e7-868b-fd893c91b512.png)

It kind of feels like we should have a configuration that indicates whether or not the segment Usage is considered when filtering data types.

**Comment by haffonist** [comment]
We will fix this.
