### ISSUE TITLE
Captions for figures and table

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1419]
HL7 implementation guides typically have an index of figures and an index of table. However this doesn't seem to be possible with IGAMT because the exports don't contain captions for the tables and figures. I manually added in captions into the Word document and created the indices, but this is going to be a source of errors for authors if it has to be done for every export.  I added captions to the tables in the Conformance Profiles section but didn't add them to the Data Type or Value Set sections.

Not sure if this is even possible using the text editor you are using.

![image](https://cloud.githubusercontent.com/assets/17408249/24050746/d7902f7c-0afd-11e7-8631-cf18b0ba16a2.png)

![image](https://cloud.githubusercontent.com/assets/17408249/24050822/21be89cc-0afe-11e7-897e-432d5a9e713f.png)

![image](https://cloud.githubusercontent.com/assets/17408249/24050884/4a1a4dc0-0afe-11e7-81e0-ed9fe2cae003.png)

**Comment by afrold** [comment]
This is fixed.
