### ISSUE TITLE
Usage Note placement

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1423]
This may be more of a "best practice" than a fix. 

Currently, the profile Usage Note is being exported after the message structure and conformance statement tables. I think it makes more sense to have the usage note at the start so that readers have a context for the technical data. Presumably we could accomplish this by using the Definition Pre-Text rather than the Usage Note, but that leads to questions about how to use the Usage Note (and more generally about what is internal documentation and metadata versus what is publishable information.

![image](https://cloud.githubusercontent.com/assets/17408249/24051446/156da9b2-0b00-11e7-83c2-d90fc53ff9c6.png)

**Comment by maxence-lefort** [comment]
@robnist Rob, any input?

**Comment by robnist** [comment]
How much effort would it take to give the user the option:

Somehting like Usage note Export options:
1. Before Message Definition
2. After Message Definition
3. After Conformance Statement

**Comment by afrold** [comment]
usage note is now internal. So this is closed.
