### ISSUE TITLE
"optional" value sets being exported

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1425]
Even when the value set export configurations are as stripped down as the can get (only the default R, RE and C value sets), many extraneous value sets are still in the export (a few are highlighted with the red arrows below). These are just value sets the author will have to manually remove. 

![image](https://cloud.githubusercontent.com/assets/17408249/24054204/6eeda7cc-0b09-11e7-8e5d-c67cae402747.png)

It seems like the value sets are included because they have a usage of R, RE or C somewhere, even if the place they are used are itself optional. For example, value set 0004 is required in PV1-2 even though that segment is in an optional (patient visit) segment group (although PV1 is R within that optional segment group).
![image](https://cloud.githubusercontent.com/assets/17408249/24054363/ebbe0d6e-0b09-11e7-9085-4562ad4c5de4.png)

Similarly, value set 0051 is required in a totally optional segment (DG1) 
![image](https://cloud.githubusercontent.com/assets/17408249/24054405/10a61c3e-0b0a-11e7-8455-c815c644deb4.png)

I'm assuming table 0113 is included in the export because it is required in one of the places it's used (the DLD data type)
![image](https://cloud.githubusercontent.com/assets/17408249/24054069/f4ac03fa-0b08-11e7-808e-b2bc1e4191ac.png)

Interestingly, the DLD data type is only optional everywhere it's used:
![image](https://cloud.githubusercontent.com/assets/17408249/24054017/c8f1f30a-0b08-11e7-917b-e46f8913f6ec.png)

Overall, the export is still including value sets that are in some way, shape or form optional everywhere they are used. In my IG, I'm letting the document be silent on any element that is ultimately optional (keeps the size of the document manageable) and having these extra value sets is just more manual work that needs to be done.

I'm not sure what the solution here is. It may be to add a configuration to filter out value sets that are only used in data types/fields which are ultimately optional (this could be rather complex given how the building blocks of the HL7 message are put together) or it could be just an option to only export custom data types and filter out all HL7 base value sets (although this only works if we have a best practice to always use a custom value set anywhere that a value set is bound).

This topic probably warrants more discussion on a call.

**Comment by maxence-lefort** [comment]
@csnewman88 I fixed a similar issue concerning the value sets, can you please check that you're still having this issue in the latest development release?
Thanks
