### ISSUE TITLE
Issue with Toc in the Datatype Library export word

### ISSUE THREAD

**Issue by haffonist** [haffonist/igamt#144]

**Comment by haffonist** [comment]
Issue with Toc.

**Comment by maxence-lefort** [comment]
Waiting for Olivier's changes to use only one xsl file for both html and word.

**Comment by maxence-lefort** [comment]
Fixed. See commit #753. @haffonist should we do another ticket for the refactoring of the xsl?

**Comment by haffonist** [comment]
No. There should be no ticket for refactoring.
