### ISSUE TITLE
Bug when adding optional segment to message structure

### ISSUE THREAD

**Issue by ncrouzier-nist** [haffonist/igamt#1450]
When adding an optional segment to a message structure, the cardinality is not set right and the segment can not be save until the user select another usage and revert back to O after that.

<img width="1526" alt="screen shot 2017-03-24 at 10 19 21 am" src="https://cloud.githubusercontent.com/assets/14352180/24298177/97de649c-107b-11e7-954e-83ee8f8283c9.png">

**Comment by afrold** [comment]
Not sure, I understand, an optional segment min cardinality is 0. I am stop by to see this in action.

**Comment by ncrouzier-nist** [comment]
Nevermind. I thought the "Max" field was disabled here (gray font) and couldn't be changed.
