### ISSUE TITLE
Order value set list and provide title for identifier

### ISSUE THREAD

**Issue by haffonist** [haffonist/igamt#152]
The list of value set identifiers in the drop down list for conformance statements is unordered ( or ordered in a non-obvious way)  Any reason for that?  Also, it would be more useful to have the titles of the value set identifiers so you know what they are without having to refer to another document.  So the first one in the list is 0441.  Is this HL70441 (Immunization Registry status)?

**Comment by Jungyubw** [comment]
fixed
