### ISSUE TITLE
Bad grammar and misalignment in conf and predicates

### ISSUE THREAD

**Issue by haffonist** [haffonist/igamt#153]
I am playing and went to add a conformance statement to a data type. There is some misalignment of the dropdown boxes and some bad grammar.  I know these are not big deals, but just wanted to point them out.  See attached screen shot.

**Comment by haffonist** [comment]
[conformance CNE.tiff](https://files.zenhub.io/56c5e4a25d3a5c4e4bb3e24d)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by Jungyubw** [comment]
fixed
