### ISSUE TITLE
error during export on the dev site

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1532]
I tried to export an IG (both profile style and IG style) in the Dev site and get this error:

{"date":null,"version":null,"text":"internalError","resourceId":null,"manualHandle":"false","skip":false,"scope":null,"id":null,"type":"danger"}

**Comment by csnewman88** [comment]
This error seems to occur as soon as you add an item to a profile component. You can create the initial Profile Component and the export works, but as soon as you add an item, you can't export anymore.

**Comment by afrold** [comment]
@csnewman88 This was already fixed. we will redeploy soon.

**Comment by csnewman88** [comment]
Can you double check that the export works for Profile Style? I ran into a similar issue with exporting in Profile Style even though the IG didn't have any component profiles in it. Thanks
