### ISSUE TITLE
wonky export order in the value set binding table

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1540]
when I bound value sets to multiple locations in a single segment, when I exported them, they showed up in an unexpected order. In the example below, the bindings for ERR-3 (green box) came out below the bindings for ERR-4 and ERR-5 (red box). They should be in the order in which they appear in the segment.

![image](https://cloud.githubusercontent.com/assets/17408249/24815038/5eccf8d4-1b99-11e7-89df-ec0d5bf30354.png)

**Comment by afrold** [comment]
@maxence-lefort please fix
