### ISSUE TITLE
what are those columns for??

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1541]
In the Value Set Bindings table, what are the Code Value and Code System columns used for? I haven't seen them populated and can't think of what would go in them. If they aren't useful, they should be removed from the export

![image](https://cloud.githubusercontent.com/assets/17408249/24815204/089c3302-1b9a-11e7-83bc-96f0a809b7d7.png)

**Comment by maxence-lefort** [comment]
@csnewman88 Those columns are for the single code bindings, see example below.

<img width="1149" alt="screen shot 2017-04-07 at 11 46 51 pm" src="https://cloud.githubusercontent.com/assets/13853131/24825440/89faf062-1bec-11e7-8726-253191c55b97.png">
<img width="1185" alt="screen shot 2017-04-07 at 11 45 50 pm" src="https://cloud.githubusercontent.com/assets/13853131/24825441/89fb12d6-1bec-11e7-97a7-e3c1d2398644.png">

**Comment by csnewman88** [comment]
Can they be labeled as such then. that makes sense once it's explained but even when populated, it's not intuitive what it means.

**Comment by maxence-lefort** [comment]
@csnewman88 I can change the name to "Single Code Value" and "Single Code System", would that work for you?

**Comment by csnewman88** [comment]
I think that would be fine.

**Comment by afrold** [comment]
@maxence-lefort did you have a chance to look at this ?

**Comment by maxence-lefort** [comment]
@haffonist yes, it will be fixed by the end of this iteration
