### ISSUE TITLE
inconsistent way to close a window

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1544]
Minor consistency issue..

Some places,to get out of an activity, there is a button at the bottom (see red arrow below), but in other places it's an "x" in the upper right (see green arrow below). In yet other places, it a button in the top right. It would be nice if these were consistent. I would lean to towards having buttons at the top to avoid scrolling but don't really care that much as long as it's consistent.

There is similar inconsistency (in both location and labeling) in the "create" "save", "add", "submit" button placement in some of the examples below.

![image](https://cloud.githubusercontent.com/assets/17408249/24817115/d61afbfa-1ba0-11e7-8a44-97edeb7697c5.png)

![image](https://cloud.githubusercontent.com/assets/17408249/24817130/ed044eca-1ba0-11e7-9044-8fce04fd10f2.png)

![image](https://cloud.githubusercontent.com/assets/17408249/24817186/0eb82ab4-1ba1-11e7-9f64-12a6ce3de377.png)

**Comment by afrold** [comment]
@Jungyubw @Abdelghani90 @IsmailMellouli @maxence-lefort please make sure we are consistent accross the tool. We should all use the second case.
