### ISSUE TITLE
change to a library can be lost

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1549]
Make a change in a data type library but then, without saving, go back to the Data Type Library List using the button in the upper left hand corner (green box below)
![image](https://cloud.githubusercontent.com/assets/17408249/24863416/5333d540-1dc6-11e7-8bd0-1706057ce6d6.png)

And then open a different data type library
![image](https://cloud.githubusercontent.com/assets/17408249/24863459/8a28751a-1dc6-11e7-899a-389d604e4c2b.png)

And then go back to the original data type library and the change will not be there.
![image](https://cloud.githubusercontent.com/assets/17408249/24863491/acfb3776-1dc6-11e7-807d-52123d73d23f.png)

The easiest solution is probably to add the standard "save changes" pop up that you get other places when you go back to the Data Type Library List
![image](https://cloud.githubusercontent.com/assets/17408249/24863551/e485e380-1dc6-11e7-99b1-695d9152efba.png)

Note that you can do a similar workflow in the IG document activity. The system responses similarly other than when you go to open the second document you get that confirmation popup so that the changes are not lost. that is a good thing, but I think it would be better if that popup showed up as you're changing to the IG document list (so earlier than it is now) and not when going to a new document (at which point there is no context for the author to decided which change is being referred to.

**Comment by afrold** [comment]
@Abdelghani90 have you fixed this yet ?
