### ISSUE TITLE
Occurrence (?) notation not needed for data type CP or CS

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1551]
I'm not sure I recall exactly what the square brackets in a conditional predicate or conformance statement means, but I think it's related to a repetition. if that is the case, I think they can (and should be) safely removed from the data type activity. Given that within a data type elements can't repeat, having "[1]" just causes confusion for a reader. Assuming there is no important information being conveyed, I would remove the [1].

Currently is like this:
If CNN.1[1] (ID Number) is valued

Would be easier to read if it were this:
If CNN.1 (ID Number) is valued

![image](https://cloud.githubusercontent.com/assets/17408249/24864151/e36b0bf4-1dc8-11e7-9940-4db9206d8667.png)

![image](https://cloud.githubusercontent.com/assets/17408249/24864216/1d83b854-1dc9-11e7-9372-112420fcf734.png)

**Comment by Jungyubw** [comment]
@csnewman88  I agree, I will update this to be automatically omitted.
Please do manually modify your CS or CP description until when I do this.

Thanks.

**Comment by Jungyubw** [comment]
Done
