### ISSUE TITLE
Add Predicate button doesn't seem to work

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1552]
It doesn't look like the "Add Predicate" button works in the data type editor. I'm not sure that is wrong as I thought the Predicates were only added in the Data Type Definition. I'm not sure it should even be here. But one way or the other, it should either be removed or it should do something.

![image](https://cloud.githubusercontent.com/assets/17408249/24865399/c0b9509e-1dcc-11e7-87d9-182d0d8db044.png)

**Comment by Jungyubw** [comment]
Done
