### ISSUE TITLE
New CS pattern

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1553]
I still can't find a pattern to use to accomplish the following Conformance Statement:

CNN.10 (Assigning Authority - Universal ID) SHALL be valued with an ISO-compliant OID.

Presumably this isn't testable but do we want a pattern for this or should authors just use a free text conformance statement? If free text is the right answer, then we should document that as a best practice.

**Comment by Jungyubw** [comment]
Constraint Pattern is 'Formatted Value'.
Value is : ISO-compliant OID


![image](https://cloud.githubusercontent.com/assets/13385213/24867240/959d85b6-1dda-11e7-892a-b651cfc17af6.png)

**Comment by csnewman88** [comment]
thanks
