### ISSUE TITLE
Editor header corrections

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#156]
The headers for the segment and data type editors could use a few changes.

- HL7 spells "Data Type" as two words, not a single word "Datatype". IGAMT should do the same everywhere (as is done for Value Set)
- "ConfLength" should be spelled out as "Conformance Length" as is done for "Conformance Statement"
- "Def.Text" should be spelled out as ??? (not sure what this is Definition Text? Default Text?)

**Comment by haffonist** [comment]
@olivier-m-mr just for reference
