### ISSUE TITLE
Complex CS ID is not displayed

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1578]
I created a complex CS with a specific ID (red box below)

![image](https://cloud.githubusercontent.com/assets/17408249/25051226/2bc324cc-2111-11e7-8f76-085ac3017711.png)

But when I added it, the ID was replaced by a description of the make up of the complex CS (purple box).
![image](https://cloud.githubusercontent.com/assets/17408249/25051238/3d0da978-2111-11e7-9fc5-aec87bc499c4.png)

This issue persists even in the data type itself
![image](https://cloud.githubusercontent.com/assets/17408249/25051250/5053fdf2-2111-11e7-807c-58a39b98ea88.png)

Having the description of the content isn't bad (it may be helpful in the editor (at least until the component CS are deleted)) but the author entered ID needs to used.

**Comment by Jungyubw** [comment]
Done
