### ISSUE TITLE
IGAMT co-constraints and GVT export

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1638]
The constraint statement created from the co-constraints in IGAMT  is not expressing the co-constraints correctly.

 [CoConstraint-13-2]If the value of OBX-3[1] (CWE) should be '69443-0','then the value of OBX-5[1] (varies) should be one of codes in PHVS_ContributoryTobaccoUse_NCHS' .

**Comment by Jungyubw** [comment]
Do you mean that should be “is”, not “Should be”?

Anything else?

[CoConstraint-13-2]If the value of OBX-3[1] (CWE) is '69443-0','then the value of OBX-5[1] (varies) should be one of codes in PHVS_ContributoryTobaccoUse_NCH

On Apr 26, 2017, at 2:33 PM, smartinez290 <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #1638<https://github.com/haffonist/igamt/issues/1638> to @Jungyubw<https://github.com/Jungyubw>.

**Comment by Jungyubw** [comment]
Fixed
