### ISSUE TITLE
Missing data type in GVT Profile Viewer

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1642]
It looks like the data type flavors assigned in the co-constraints table are not accounted as been referenced.

**Comment by Jungyubw** [comment]
It is too old.

Sandra is looking for this actual errors.

**Comment by smartinez290** [comment]
Woo -- I am closing this issue and open another one related to missing missing DTs with conditional usage in the profile viewer. Harold will take care of it.
