### ISSUE TITLE
wrong list of libraries sometimes showing

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1648]
It appears that IGAMT remembers which library I was looking at last time I was logged in. If I am looking at my user data type libraries and then log out, when I log back in and go to the Data Type Libraries activity, it highlights "master data type libraries" (purple arrow) but the library list show is actually the user data type libraries.

![image](https://cloud.githubusercontent.com/assets/17408249/25500446/acdea980-2b54-11e7-8bcb-3b9854a8b1d3.png)

You can confirm this by moving to the user library list and then back to the master library list and you'll see the right list of master libraries (green arrow)

![image](https://cloud.githubusercontent.com/assets/17408249/25500545/069cc146-2b55-11e7-89eb-77dddf9f6892.png)

**Comment by Abdelghani90** [comment]
fixed
