### ISSUE TITLE
Clean up Message Infrastructure MetaData

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#165]
Not sure what is relevant metadata for the infrastructure section
-Seems like HL7 Version is IG metadata. Is it fair to say that all profiles in a given IG should be the same HL7 version?
-I don't know what Schema Version, Type or Encodings mean
-Personally I lean to having the Metadata at the IG level and getting rid of this section

**Comment by haffonist** [comment]
@robnist any thought on this ?
