### ISSUE TITLE
Exported profile component not displaying changed value.

### ISSUE THREAD

**Issue by afrold** [haffonist/igamt#1655]
Exported profile component not displaying changed value.
<img width="596" alt="screen shot 2017-04-28 at 9 38 07 am" src="https://cloud.githubusercontent.com/assets/13695248/25531125/b1148446-2bf6-11e7-9689-d384f6435b4f.png">
<img width="935" alt="screen shot 2017-04-28 at 9 38 43 am" src="https://cloud.githubusercontent.com/assets/13695248/25531126/b122bbce-2bf6-11e7-8530-ffab533df6b3.png">

**Comment by maxence-lefort** [comment]
@haffonist you have to check the "Length" attribute in the configuration, it's not exported by default.
