### ISSUE TITLE
Make the order of the profiles customizable

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#166]
What determines the order of the profiles listed in the table of contents? It's not the order in which they were selected, alphabetical or workflow related?

It would be best to allow the author to drag and drop them to put them in the desired order.

**Comment by haffonist** [comment]
yes you are right, we are working on this feature.

**Comment by haffonist** [comment]
@gcr-nist what is the impediment ?

**Comment by csnewman88** [comment]
If you rearrange the order of the profiles, once you log out and log back in, the order you selected is lost.

**Comment by haffonist** [comment]
Thanks Craig for the clarification. This issue is in the pending pipeline which mean the developer is having some impediment to fix this issue. So I was asking @gcr-nist (the developer) what the impediment was to fix that issue. 

Thanks
