### ISSUE TITLE
Can't export cloned IG to GVT

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1665]
Getting the following profile errors. Cloned VRDR IG trying to export the CREI profile to GVT. See attachment. 
![cloningig](https://cloud.githubusercontent.com/assets/14842422/25544657/6bdb495e-2c29-11e7-9a60-7fe8d0d894e2.png)

**Comment by afrold** [comment]
@Jungyubw this seems to happen when cloning an ig doc.

**Comment by Jungyubw** [comment]
Fixed

**Comment by Jungyubw** [comment]
IGDoc XML has some error for 

"HL7 Version 2.6 Implementation Guide-Vital Records Death Reporting, Release 1 - US Realm- New"

**Comment by Jungyubw** [comment]
Fixed. we are waiting for deployment.
