### ISSUE TITLE
Profile Component - IGAMT Dev

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1680]
•	Created a MSH flavor called MSH_TX
–	MSH-3 cardinality is [1..1], datatype HD_TX
–	MSH-5 usage R, dT =  HD
•	Created a profile component call PC1
–	Added the element "MSH-5" from segment level
•	change the datatype to the "HD_TX" flavor.    **not able to select a data type**
•	Change usage to “RE” 
•	Create a composite profile using PC1
–	Checked the  “Definition” to see the MSH-5 update.  **MSH-5 usage shows as “R” instead of “RE”**

**Comment by afrold** [comment]
This should be fixed at next deployment today.
