### ISSUE TITLE
Clean up the profile table columns

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#169]
I don't see how Length, ConfLength, Datatype or Value Set would be used in a message definition. Predicate Conformance Statement, DefText and Comment may or may not be used depending on the IG and how they are used (DefText and Comment specifically)

![image](https://cloud.githubusercontent.com/assets/17408249/13324054/b7a25e38-dba1-11e5-9f57-3504cfaea297.png)

**Comment by haffonist** [comment]
As discussed, those columns are needed for the field and components.
