### ISSUE TITLE
Sync up Usage and Cardinality  for segments and fields

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#171]
Is it possible to autopopulate the minimum cardinality based on the Usage for both segments and fields? (R would set a minimum cardinality of 1, RE or O would set a minimum cardinality of 0) As it is, it's possible to manually edit the usage or cardinality and create conflicts.

If it can't be autopopulated, it should be validated to make sure there are no errors. This is one of the fundamental sort of errors we are trying to avoid with a tool like this

![image](https://cloud.githubusercontent.com/assets/17408249/13324349/e6e9f8ee-dba2-11e5-8ba9-84a74d94879a.png)

**Comment by haffonist** [comment]
Fixed
