### ISSUE TITLE
Adding predicate or conformance statement for segments

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#172]
Why do only segment groups have the option to add a predicate or conformance statement? Even when the Usage is set to C, there is no option to set a predicate

![image](https://cloud.githubusercontent.com/assets/17408249/13324409/3af899b8-dba3-11e5-9225-c7574e0a927c.png)

**Comment by Jungyubw** [comment]
We know this issue and I am working on it.

**Comment by Jungyubw** [comment]
Done, now user can add message level predicate and conformance statement at any location.

It will apply on next deployment.
