### ISSUE TITLE
Reported issue - Dynamic mapping

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1726]
Dynamic mapping is not working for CWE but it is working for the DT type. No sure if this is a validation or IGAMT issue. Please investigate and redirect to Hossam if it is a validation issue.

**Comment by Jungyubw** [comment]
It happened from old copied IGDocuments.
We fixed this issues but this copy was generated before we fixed. 

So please remove missing value sets (Just Icons is showing) in the CoConstraint tables.

**Comment by smartinez290** [comment]
Exported the IG but I am getting an unresolved field error. Opened a validation ticket for Hossam. I sent email about it yesterday.
