### ISSUE TITLE
Reported issue - Missing DT from drop down list

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1727]
While working with the IZ Ballot IG noticed that the data type ID_IZ01 used in OBX_IZ_03 and OBX_IZ_02 co-constraints is not showing in the DT drop down of the co-constraint table. See attachment or stop by to show you.
![id](https://cloud.githubusercontent.com/assets/14842422/26072354/2aaf1d54-3979-11e7-81d0-613987054261.png)

**Comment by Jungyubw** [comment]
ID datatype is missing because OBX-2 value set does not have "ID" code.

Please update value set of OBX-2.

If everything is working well, please close this ticket.
