### ISSUE TITLE
All coconstraint values sets are gone

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1731]
I entered a large number of co-constraints for 3 different OBX segment flavors and now they are all gone. 

This is the current screen shot. Note the lack of values anywhere in the OBX-5 or OBX-17 columns
![image](https://cloud.githubusercontent.com/assets/17408249/26171888/25e0a538-3b0c-11e7-8ad8-a2ee98b881ba.png)

 And here is what it looked like last time I exported the document. Note the presence of value sets in those same columns.
![image](https://cloud.githubusercontent.com/assets/17408249/26171943/50802f20-3b0c-11e7-94ea-6f7eb114c80d.png)

Please restore my value sets. 

Now that we've produced two documents that have gone for HL7 ballot it's absolutely critical that issues like this don't come up. If I hadn't noticed this, we could have published a final document that was missing significant content relative to the balloted version.

**Comment by csnewman88** [comment]
Looks like the data may still be there as it seems to be in an export. Maybe it's just not displaying in IGAMT.

![image](https://cloud.githubusercontent.com/assets/17408249/26172701/f2f4761a-3b0e-11e7-8d96-c174d95c1a59.png)

**Comment by smartinez290** [comment]
They were gone from the ballot you shared with me. I believe is due to the new co-constraint functionality Woo implemented. They need to be entered again. I did in my copy to continue validation testing. @Jungyubw please confirm or maybe you have a way to get them back.
