### ISSUE TITLE
Binding Location is missing

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1734]
PID-10 has a binding location = 1 but the tool is generating a "binding location is missing" alert. 

Per Hossam,
I confirm it’s an IGAMT issue, the PID-10 Field is the following :

<Field Name="Race" Usage="R" Datatype="CWE_2-6" MinLength="0" MaxLength="705" ConfLength="NA" Binding="0005_TX_2-6" BindingStrength="R" Min="1" Max="*" ItemNo="00113"/>

“BindingLocation” is missing.

**Comment by Jungyubw** [comment]
PID_TXT in ADT^A08^ADT_A01 Testing_Seg-DT_VS_Flavor

**Comment by Jungyubw** [comment]
Fixed

**Comment by Jungyubw** [comment]
Fixed and waiting for Deployment
