### ISSUE TITLE
exporting to GVT - Duplicate key value error

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1750]
I am getting this error when exporting to GVT:
cvc-identity-constraint.4.2.2: Duplicate key value [DTM_S_2-6] declared for identity constraint "DatatypeKey" of element "ConformanceProfile".

In this profile dynamic mapping included mapping to a DT with many flavors. Not, if this is the cause of the problem or how this gets resolved.

**Comment by Jungyubw** [comment]
same error with #1665
