### ISSUE TITLE
Support for OBX sequencing for more than one group

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1751]
I was told there is validation support available, but that IGAMT must provide a mechanism, for example a check box under the OBX, to required validation support for continuous sequencing  when there is more than one Order group in a message.
ORC|
RXA|RXR|
OBX|1|
OBX|2|
ORC|
RXA|RXR|
OBX|3|
OBX|4|

**Comment by smartinez290** [comment]
Discuss for solution is needed.  
Per Rob: 
The pattern we want to support is 

OBR 1
OBX 1
OBX 2
OBX 3
OBR 2
OBX 1
OBX 2


Not continuing with OBX 4 and 5.

This is a special case for immunization and we need to treat it as a special case.

**Comment by Jungyubw** [comment]
@smartinez290 Sorry for delaying. I will do this after performance improvement.
