### ISSUE TITLE
Expecting to get an error because when value is excluded.

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1752]
I ran a test using the the Immunization ballot profile. In this profile the code 1002-5 in CDCREC-01 is excluded. PID-10 is binded to CDCREC-01 with binding strength “R” and Binding location “1”
In the test message I included this code in PID-10.1. 

I am expecting to get an error because that value is excluded. But the tool does not generate an error. 

In this profile the binding location is in the xml file.

**Comment by Jungyubw** [comment]
Sent email to Hossam

**Comment by Jungyubw** [comment]
@smartinez290 I think this is fixed, right?
