### ISSUE TITLE
 Profile component at the message level

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1754]
IGAMT allows to create a profile component at the message level. The only mod the user is allowed to make is to add a predicate, but I do not understand why or how to add a predicate at the message level. This requirement and implementation needs to be reviewed.

**Comment by afrold** [comment]
Should be fixed at next deployment today

**Comment by smartinez290** [comment]
I see that now the only constraint that a user is to allowed to enter is a Conformance Statement at the message level. When I try to build the CS, the only draggable nodes are segments, the fields can't be dragged. Is this the expected behaviour?

**Comment by smartinez290** [comment]
@haffo is this issue ready for QA?
