### ISSUE TITLE
restrict where value sets can be added

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#179]
Initially, everything has the "edit" pencil icon in the Value Set column so it is possible to add a value set to any field regardless of data type. Is this appropriate? Here I added a random value set to an ST element, is this desirable?
![image](https://cloud.githubusercontent.com/assets/17408249/13325319/ecc53b8a-dba6-11e5-947c-472f894a68a8.png)

**Comment by csnewman88** [comment]
Once the "delete" X icon is clicked, then the behavior changes based on the data type. Sometimes, an "add" + icon appears such as for OBX-3 in the screen shot above (IS, CE, TS, etc) but other times, the cell is just empty such as for OBX-1 above. 
-Is there a difference between the pencil and + icons?
-Can the ability to add a value set be restricted in all views to just a subset of data types? I'd hate to see a TS element have a value set.

**Comment by Jungyubw** [comment]
@robnist 

As you know, we are just allowing to set the ValueSet for:
- Complex Datatypes
- IS, ID datatypes

In this example, ST Datatype is not allowed to have valueSet but preloaded profile has already valueset. I think we need to allow all kinds of DT could have valueset. What do you think of?

**Comment by Jungyubw** [comment]
@csnewman88 

- pencil is to edit the binding and + icone is to add new 
- If you define the binding of valueset on the component of Datatype, you don't need to see the valueset on the field of the Segment or message view.

**Comment by haffonist** [comment]
@Jungyubw  will discuss with @robnist  about this.

**Comment by Jungyubw** [comment]
Done
