### ISSUE TITLE
Code System long name

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1791]
![codesys](https://cloud.githubusercontent.com/assets/14842422/26604025/face10f6-4556-11e7-8a73-8e32c743909b.png)
Per Rob: When exporting and validating to GVT automatically I discovered this issue.

Code System is not LOINC but LN. In IGAMT we may need to list as what is expected from table 0396 and the dropdown should be from this table.

When the XML profile is being generated it is including LOINC, which is correct and the validation is catching the error LOINC ßà LN which is correct. 

So IGAMT has to do better in ensuring this and helping the user. Maybe we consider Code System long name, but not on this panel, maybe in meta data.

**Comment by Jungyubw** [comment]
@smartinez290 @robnist 
At first, I modified to use "LN" instead of "LOINC".
I will implement CodeSystem logic that all code sys come from HL70396 Tables.

**Comment by smartinez290** [comment]
@robnist can you verify this one?
