### ISSUE TITLE
 Adding, removing code system on meta data tab 

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1793]
Per Rob: Adding, removing code system on meta data tab for value set is poor.
![vs](https://cloud.githubusercontent.com/assets/14842422/26604368/22bafb0a-4558-11e7-9443-06d499e02f3c.png)

Also, should select from table 0396.

**Comment by smartinez290** [comment]
Not addressed in the latest release (june 22)

**Comment by smartinez290** [comment]
Not addressed yet. (July 10)

**Comment by Jungyubw** [comment]
Duplicated Ticket #1794
