### ISSUE TITLE
Poor UI to select code system 

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1794]
Per Rob: nI try to select the arrow to see the dropdown but nothing happens, I have to select somewhere to get something that looks like a dropdown but really isn’t
![codesysuipoor](https://cloud.githubusercontent.com/assets/14842422/26604569/be9a6ff6-4558-11e7-9c84-afa7e395d6c8.png)

Would be nice to assigned to all 

 

Would be nice to add to drop down from this tab—otherwise user has to know to go to meta data tab,

**Comment by Jungyubw** [comment]
#New Requirements
Need CodeSystem comes from HL70396

**Comment by smartinez290** [comment]
@robnist Could you review this one? I am not sure what you were asking.

**Comment by Jungyubw** [comment]
@robnist @smartinez290 @haffonist  

UI has been updated (Need deployment)
** METADATA just shows list of codeSystem. No edit.
** You can add new CodeSystem at code definition.

1. To add new CodeSystem, select "New CodeSystem"
<img width="1258" alt="screen shot 2017-07-11 at 3 49 14 am" src="https://user-images.githubusercontent.com/13385213/28056858-751000e4-65ec-11e7-81e9-df3a99f701be.png">
2. Now you can type the codeSystem in inputbox, then click "+" button.
<img width="1260" alt="screen shot 2017-07-11 at 3 49 44 am" src="https://user-images.githubusercontent.com/13385213/28056860-75108d02-65ec-11e7-8249-b8bb478ce974.png">
3. The new CodeSystem is registered in the select List.
<img width="1272" alt="screen shot 2017-07-11 at 3 49 54 am" src="https://user-images.githubusercontent.com/13385213/28056859-75108a46-65ec-11e7-8d4a-8fe9a12f789e.png">

Additionally I implemented "APPLY ALL" for Codes System.
<img width="1258" alt="screen shot 2017-07-11 at 3 50 12 am" src="https://user-images.githubusercontent.com/13385213/28056861-75117230-65ec-11e7-9aa1-59d83113404e.png">

**Comment by Jungyubw** [comment]
Done
