### ISSUE TITLE
Profile viewe: OBX-5 Length

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1795]
Length needs to be tied to the data type selected.
![obx5](https://cloud.githubusercontent.com/assets/14842422/26633356/1e06be4e-45e1-11e7-9da1-baba84e8201a.png)

**Comment by smartinez290** [comment]
I can't review this one until GVT issue is solved.

**Comment by Jungyubw** [comment]
I don't understand this logic. How can we know the what DT is selected for OBX-2?
