### ISSUE TITLE
track where segments, data types or value sets are used

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#180]
I know for the Data Type Flavor Library, we don't want to catalog which IGs are using a data type (which I'm OK with), but within an IG in IGAMT, it would be very useful to know where a particular segment, data type or value set is being used so that as those things are edited, the author knows what parts of the document are being affected by the changes

**Comment by haffonist** [comment]
@haffonist for reference

**Comment by haffonist** [comment]
Duplicates Issue.
