### ISSUE TITLE
complex CS ID is wrong

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1813]
Pretty sure we've seen this one before, but when creating a conformance statement, the ID that gets saved and displayed reflects the construction of the CS and not the ID specified by the author

![image](https://cloud.githubusercontent.com/assets/17408249/26833867/48e454c0-4a99-11e7-83b3-254c188df849.png)

If you open up the editor again and delete the incorrect ID and replace it with a new one, that new one is saved in the editor but the construction is still displayed in the segment activity.

**Comment by Jungyubw** [comment]
Fixed
