### ISSUE TITLE
Conditionnal usage and predicate issue

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#1840]
I created a datatype in the user datatype library
I set some of the usage to C, created the predicates.

Once I hit "SAVE" to save my datatype, I see two usages in some of the elements I changed and the predicate disappeared from the Predicate column

![image](https://user-images.githubusercontent.com/13591511/27092328-deb4d0fa-5030-11e7-9b78-c003f7cf13f6.png)

**Comment by carolinerosin** [comment]
it's probably just a display issue because when I select "C" instead of "O", I can see the predicate I entered.

**Comment by afrold** [comment]
This is fixed now.
