### ISSUE TITLE
DTM sub-element usage changes automatically to R 

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#1841]
I see some weird behavior with DTM datatpe. First screen shot is my starting point, YYYY is R, MM is O then all are C, until ZZZZ which is O
![image](https://user-images.githubusercontent.com/13591511/27097385-11202fa6-5042-11e7-9ff1-efebaba00f81.png)

I only changed the usage of DD to O and for some reason the usage of MM is automatically changed to R 

![image](https://user-images.githubusercontent.com/13591511/27097407-26bf3302-5042-11e7-935e-e9fc5150f788.png)

**Comment by afrold** [comment]
@Jungyubw any idea ?
