### ISSUE TITLE
What does the "classification" drive

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#185]
In the conformance statement and predicate editors, what is the intended use of "classification"? What does it drive?

**Comment by Jungyubw** [comment]
@csnewman88 
The "classification' is intend to describe validation result classification. 
We have 3 types of this: error, warning, alert. 

If one conformance statement is 'warning', the validation tool will produce the 'warning' tagged report when this constraint is failure.

**Comment by csnewman88** [comment]
So should all "required" conformance statements and predicates have a classification of "error"? Is there ever a time when a predicate shouldn't be an error?
