### ISSUE TITLE
Changing "root" of datatype isn't available anymore

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#1852]
I remember we had a functionality that allowed the user to change a datatype to another one, but I can't find it anymore. I believe it was "change datatype root".

Example:
I create a segment flavor for PID.
PID-10 (Race) is datatype "CE" (from HL7 v2.5.1). I need to be able to change the datatype to a flavor of "CWE" that I created.

**Comment by carolinerosin** [comment]
@robnist can you have a look at this issue, how do you want that to be handled in IGAMT ? I believe in a previous version it was possible to change the datatype of a field. There are some rules in HL7 that allow to change the datatype of a field.

**Comment by robnist** [comment]
Yes, we need to allow and yes I thought it was still available. Not sure what happened to it. Harold?

________________________________
On: 21 June 2017 10:14, "Caroline Rosin" <notifications@github.com> wrote:

@robnist<https://github.com/robnist> can you have a look at this issue, how do you want that to be handled in IGAMT ? I believe in a previous version it was possible to change the datatype of a field. There are some rules in HL7 that allow to change the datatype of a field.

**Comment by Abdelghani90** [comment]
It still available in the production version. I will fix it before the next deployment. This was my fault
Thanks for reporting

**Comment by carolinerosin** [comment]
it's back and working, thank you
