### ISSUE TITLE
Dynamic mapping & profile component : list is not in sync after update to OBX dynamic mapping

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#1871]
Some of the datatypes (reference value column) are missing from the dynamic mapping table in the profile component. Here's what I did

1. create dynamic mapping under the OBX segment flavor, save.
2. go to profile component, add Item OBX (from the message tab)
3. check the dynamic mapping table, I notice I had forgotten some values, save
4.  go back to OBX segment flavor, edit dynamic mapping to add the missing values, save
5. go back to my profile component, edit dynamic mapping associated with my "OBX item": the values I added in #4 are not in the list

If I want to have the updated dynamic mapping table in my profile component, I need to delete the OBX entry there and re-add it.

**Comment by Jungyubw** [comment]
@haffo Profile Component Dynamic Constraint and Constraint UI are old.

**Comment by Jungyubw** [comment]
At first we need to update UI at first for profile component and then check the issues.

**Comment by carolinerosin** [comment]
do you still want me to test and submit tickets with what I found ? or do you prefer me to wait until the UI is updated ?

**Comment by Jungyubw** [comment]
Please wait for us to update Profile Component.

**Comment by harold** [comment]
> @harold Profile Component Dynamic Constraint and Constraint UI are old.

@Jungyubw, I don't think I'm the @harold you were aiming at. I have no connection to this project (I think) :smile: Maybe you want to re-mention the correct individual.

gl.

**Comment by afrold** [comment]
@Jungyubw  is this fixed ?
