### ISSUE TITLE
Complex predicate editor is not inutitive

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#188]
I had a hard time figuring out to use the complex predicate editor (I'm still not sure I fully get how to use it). I don't have any specific suggestions for it now, but I think we may want to spend some time on this functionality.

**Comment by Jungyubw** [comment]
I totally agreed with.....

**Comment by Jungyubw** [comment]
1st Constraint ( composite type: AND, OR, IF) 2nd Constraints

**Comment by Jungyubw** [comment]
Done
