### ISSUE TITLE
Cross-reference should also check for any reference in profile components

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#1883]
It would be nice to also check if an element is referenced in a profile component.

**Comment by carolinerosin** [comment]
The items from the profile component are present in the cross-reference, I just get an error message saying "Cannot find the datatype specified" when I clic on the "path". Can we fix that to go to the profile component ?

**Comment by Abdelghani90** [comment]
OK I'll do it thanks.

**Comment by carolinerosin** [comment]
So I see now the items from the profile components in the cross reference, but when I click on the "path" I get "cannot find the datatype specified". I would either not allow the user to "navigate" or fix and navigate to the profile component.

**Comment by Abdelghani90** [comment]
Sorry I will fix that Thanks
