### ISSUE TITLE
Complex conformance statement id is not what I entered

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#1885]
I entered "LRI-7" but it was changed into "OR(LRI-7-a, LRI-7-b)"

![image](https://user-images.githubusercontent.com/13591511/27453260-d20c00aa-5763-11e7-94ac-4543edfbfc70.png)

**Comment by afrold** [comment]
@Jungyubw please fix for this deployment. 
Thanks

**Comment by Jungyubw** [comment]
Fixed
