### ISSUE TITLE
Dynamic Mapping List and "Status" column

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1892]
I think there should be some type of explanation or guidance on the purpose of the  "Dynamic Mapping List"  and the "Status" column in the "Defalult Dynamic Mapping ValueSet"

**Comment by Jungyubw** [comment]
I will do this after Performance issue done.

**Comment by Jungyubw** [comment]
Done

**Comment by afrold** [comment]
Put in gray the referenced row.
