### ISSUE TITLE
Profile Component - Adding a Predicate fields out of order

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1894]
See screen shot. The MSH fields are completely out of order. 

![image](https://user-images.githubusercontent.com/14842422/27480891-16689374-57e8-11e7-89c2-7d0ad5571fe9.png)

**Comment by afrold** [comment]
FYI This is not a profile component.

**Comment by Jungyubw** [comment]
@smartinez290 Could you show me where you find this issue?

**Comment by smartinez290** [comment]
@Jungyubw I was in the profile component adding a predicate to a field. I just did it again and it is not happening.
