### ISSUE TITLE
Can't save the Definition Text in Segment Panel

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1898]
There is no way to save and the text entered is gone when closing the  window..

**Comment by smartinez290** [comment]
Ok!! it looks like it was saved. I can go back an edit, but is was not intuitive.

**Comment by smartinez290** [comment]
The comment Column has the save button.

**Comment by smartinez290** [comment]
Not fixed yet.

**Comment by smartinez290** [comment]
Not fixed yet

**Comment by afrold** [comment]
Need to close this since it is not applicable anymore. Def Text will replace comment who already have this function.
