### ISSUE TITLE
enforce unique conformance statement IDs

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#192]
In the conformance statement editor, there doesn't seem to be any checking that the ID is unique within the IG. Is this something that the tool can generate? Presumably we'd need IG level metadata for an "abbreviation" (IZ for immunization, LRI for lab results, etc). Given that best practice is to not re-use Conformance Statement IDs, this would be a good way to ensure that.

**Comment by Jungyubw** [comment]
Merged to #291
