### ISSUE TITLE
sharing conformance statements?

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#193]
Are Conformance Statement ever expected to be shared either within an IG or between IGs (LOI and LRI for example)? Do we need a way to apply an existing Conformance Statement to a field?

**Comment by Jungyubw** [comment]
@csnewman88,

I think the Conformance statement and predicate should be shared with Datatype or Segment because they are tightly coupled message structure. 

For now we are working on the Datatype Library and its sharing. The CS and CP will be shared with Datatype sharing. Segment will be next.
