### ISSUE TITLE
A draggable icon in the wrong element location

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1935]
I am adding a CS to a segment. There is a draggable icon next to the segment, but the segment can not be dragged.  

![image](https://user-images.githubusercontent.com/14842422/27553721-1ab89390-5a7a-11e7-88fc-7f55612e6c56.png)

**Comment by afrold** [comment]
@Jungyubw any update on this ?

**Comment by smartinez290** [comment]
No fixed yet.

**Comment by Jungyubw** [comment]
Fixed now
