### ISSUE TITLE
Adding a Predicate at the message Level

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1937]
I can't select a group as a context. Also, when I select the message as the context I get a notice that the message was selected, when I unselect the message this notice is still displayed. 

![image](https://user-images.githubusercontent.com/14842422/27556732-bdb55e70-5a84-11e7-8861-9d18bf6a1863.png)

**Comment by carolinerosin** [comment]
@smartinez290 it seems to work in my IG (LRI), I can select a group as a context.
What is the element that is conditional in your example ?

![image](https://user-images.githubusercontent.com/13591511/27557922-6a9e787a-5a89-11e7-87b1-c59001c49cf7.png)

**Comment by smartinez290** [comment]
The element was MSH, that is why was not allowing to select a group, so is fine. Woo looking at second issue.

**Comment by Jungyubw** [comment]
Fixed

**Comment by smartinez290** [comment]
The second issue is solved. But, now I can select a group in the message tree.

**Comment by smartinez290** [comment]
Ok! the element was not within the group. A little confusing, maybe changing the message to just "Select Context" will do.
