### ISSUE TITLE
XML constraint file issues

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#1940]
I created a composite profile and exported as XML. I see a few issues:
- I have two MSH segment contexts in my constraint file (the one from the composite profile and the one from the original conformance profile)
- there is a conformance statement missing from my composite MSH (id = MSH_GU_FRU_1_2-5-1)

IGAMT screenshot of the "original" MSH
![image](https://user-images.githubusercontent.com/13591511/27559161-8a1a6c96-5a8d-11e7-8a54-d1c97e7e8ffa.png)

The LRI-6 conformance statement is missing from the constraints associated with "MSH_GU_FRU_1_2-5-1"

[LRI-CompositeProfile_20170626_162024.zip](https://github.com/haffonist/igamt/files/1103440/LRI-CompositeProfile_20170626_162024.zip)

**Comment by afrold** [comment]
@carolinerosin still having this on hit-dev ?

**Comment by carolinerosin** [comment]
yes, I just checked and I still have the issue. I didn't re-create a new IG, I just checked in my existing IG. I exported the XML composite profiles and still have the conformance statement missing from the "composite" MSH

**Comment by carolinerosin** [comment]
I also found another conformance statement that I have in my IG, but is not in my XML file (the "OR")
![image](https://user-images.githubusercontent.com/13591511/28183375-3d88fbe2-67dd-11e7-96d8-b2374ee1634e.png)

![image](https://user-images.githubusercontent.com/13591511/28183440-76aaa5e2-67dd-11e7-8752-1d58786b7527.png)
