### ISSUE TITLE
Profile component no applied on certain segments

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#1941]
I defined several items in my profile component for the "OBR" segment (OBR_LRI flavor)
![image](https://user-images.githubusercontent.com/13591511/27559605-1a4ed63e-5a8f-11e7-8b8e-8f7ba5536429.png)

Here's what I get in my composite profile:
![image](https://user-images.githubusercontent.com/13591511/27559686-7a6e4c84-5a8f-11e7-8c3a-926f9a675ac6.png)
![image](https://user-images.githubusercontent.com/13591511/27559701-8aa9ed92-5a8f-11e7-8255-90c2d8409d8a.png)

**Comment by carolinerosin** [comment]
I was able to recreate the bug that way:
- create an IG based on ORU^R01 v2.5.1
- create a flavor of ORC (ORC_LRI) - no need to change anything
- create a flavor of OBR (OBR_LRI) - no need to change anuthing
- I imported a datatype from my user library (EI_GU)
- created a profile component (GU), added the items ORC_LRI.2 and ORC_LRI.3. Ichanged the datatype to EI_GU for both
- I added OBR_LRI.2 and OBR_LRI.3 to my GU profile component, changed the datatype to EI_GU for both
- changed the flavor of ORC to ORC_LRI in my message structure
- changed the flavor of OBR to OBR_LRI in my message structure
- created the composite profile by selecting my ORU^R01 profile and the GU profile component.

ORC_LRI becomes ORC_GU_1 (which is correct); OBR_LRI stays the same, instead of being replace by a "GU" flavor

**Comment by carolinerosin** [comment]
It has something to do with the order of my elements in the profile component.
when I add in that order OBR_LRI.2, OBR_LRI.3 , ORC_LRI.2, ORC_LRI.3 no issues, OBR and ORC have a "GU" flavor created

when I add my items in that order:  ORC_LRI.2, ORC_LRI.3,OBR_LRI.2, OBR_LRI.3, only ORC has a GU flavor created

you can also test by creating an ig with ORU R01, v2.5.1. Just create a "EI" datatype flavor, create an OBR flavor, create an ORC flavor. Change OC and OBR under ORU_R01.ORDER_OBSERVATION group to the flavor you created. Then create a profile components where you try to change the datatype of your ORC.2, ORC.3, OBR.2, OBR.3 to the datatype flavor you created. Then create the composite profile

**Comment by carolinerosin** [comment]
same behavior issue if I only test with ORC.2 and OBR.2, but only when the ORC item is before the OBR item in my profile component

**Comment by Abdelghani90** [comment]
Thank you Caroline.I can produce it. @haffo  I am working on this
