### ISSUE TITLE
Can't add a segment

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1945]
This functionality is confusing. I click on "Add Segment" and the "CREATE SEGMENT" pop up looks like only lets the user add a field in an existing segment. But still if I try to add the field,  it does not let me add it.

Am I missing something?

**Comment by afrold** [comment]
Fix dialog width 
use new select input form material 
Fix input text

**Comment by smartinez290** [comment]
This issue is still there. Also, the icon to add the segment is not clear. I click o n +ADD, nothing happened. I needed to click a drop down next to the +ADD.
