### ISSUE TITLE
Missing buttons in dialog to delete datatype from library

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#1957]
we can't confirm because the buttons are missing

![image](https://user-images.githubusercontent.com/13591511/27919104-cf6eb168-623e-11e7-954e-6290486c9446.png)

**Comment by Abdelghani90** [comment]
Thanks for reporting. It will be fixed today.

**Comment by carolinerosin** [comment]
seems to be working now, thanks !
