### ISSUE TITLE
Missing some datatype flavors from "change datatype root"

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#1962]
I don't see all my datatype flavor in the dropdown menu (I can't find the "CWE_GEN" flavor in the dropdown). Also the dialog box is too small.

![image](https://user-images.githubusercontent.com/13591511/27971458-c4c81168-6320-11e7-95fd-207afccea883.png)

![image](https://user-images.githubusercontent.com/13591511/27971481-d71d19f8-6320-11e7-8d6e-f16ac3596d71.png)

![image](https://user-images.githubusercontent.com/13591511/27971490-e35a4060-6320-11e7-851e-9a50cbfea311.png)

**Comment by Abdelghani90** [comment]
will be fixed ASAP

**Comment by carolinerosin** [comment]
seems to be ok now, thanks !
