### ISSUE TITLE
Update home page

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#1970]
Add in “black” before the note in RED. 

“IGAMT is a tool used to create HL7 v2.x implementation guides that contain one or more conformance profiles. The tool provides capabilities to create both narrative text (akin to a word processing program) and messaging requirements in a structured environment. IGAMT contains a model of all the message events for every version of the HL7 v2 standard. Users begin by selecting the version of the HL7 v2 standard and the message events they want to include and refine (constrain) in their implementation guide.”

Leave a space between the black and red text.

Fix as noted before deployment to production..

![image](https://user-images.githubusercontent.com/14874904/28028173-a9aa658e-6569-11e7-905f-d70119dfc99b.png)

**Comment by afrold** [comment]
Done. Available in next deployment
