### ISSUE TITLE
Co-constraints UI scrollbar not working

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#1972]
I can't scroll down to see the other expandable tab/dropdowns, e.g., I can't access dynamic mapping.

![image](https://user-images.githubusercontent.com/14874904/28028672-535733a4-656b-11e7-851f-b2135f87e183.png)

**Comment by robnist** [comment]
Also, there is extra white space below the bottom scroll bar. Would be nice to give the user that extra working space.

**Comment by afrold** [comment]
@Abdelghani90  related issue, right ?
