### ISSUE TITLE
Table 0125 and probably all tables

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#1975]
Why aren't the code is alphabetic order like in standard and also the TEXT in the table title is meshed together.

![image](https://user-images.githubusercontent.com/14874904/28029324-ab59bbb0-656d-11e7-866f-d11f1135199a.png)

![image](https://user-images.githubusercontent.com/14874904/28029307-969ff4b4-656d-11e7-85e0-1474b577774a.png)

**Comment by Jungyubw** [comment]
fixed
