### ISSUE TITLE
Why the profile ID in the value set ID?

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#1976]
Why is the profile ID in the value set ID? Value sets are not bound to a single profile, they can be bound to many profiles.

![image](https://user-images.githubusercontent.com/14874904/28029591-8d5769fe-656e-11e7-9e87-1d663b437ef1.png)

**Comment by Jungyubw** [comment]
By current Logic to make Value Set flavor, the new mapping identifier is “Original ID” + “_” + “Extension” + “_” + random number.

So in this case “ORU” is come from this IG Document Extension.


On Jul 10, 2017, at 12:53 PM, Rob <notifications@github.com<mailto:notifications@github.com>> wrote:


Why is the profile ID in the value set ID? Value sets are not bound to a single profile, they can be bound to many profiles.

[image]<https://user-images.githubusercontent.com/14874904/28029591-8d5769fe-656e-11e7-9e87-1d663b437ef1.png>

**Comment by afrold** [comment]
I will close this. Please open if the issue persists.

**Comment by robnist** [comment]
OK. I forgot I created that extension for the IG. I still don't think we should use this logic. Should be same as for DT or SEGMENT. Why for value set is it different?

**Comment by Jungyubw** [comment]
Okay I will fix the new binding ID just have random number.

**Comment by Jungyubw** [comment]
Done
