### ISSUE TITLE
Fix PhinVads Value Sets Dialog

### ISSUE THREAD

**Issue by afrold** [haffonist/igamt#1985]

**Comment by afrold** [comment]
Add View Selection and Filter by text and view

**Comment by afrold** [comment]
@Jungyubw  did you fix this ?

**Comment by Jungyubw** [comment]
@haffonist Rob said it is not included for this Prod deployment. Do you think I should?

**Comment by Jungyubw** [comment]
Anyway I will do this by Thursday

**Comment by afrold** [comment]
ok

**Comment by Jungyubw** [comment]
Done
