### ISSUE TITLE
Improve CP dialog

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#2000]
Would be good to put in node what you actually get.

instead of 1[1] which is probably ambigious to most user, show CE_CN.1 in this example.

![image](https://user-images.githubusercontent.com/14874904/28071389-c4c2cda2-661d-11e7-96c1-6c7eae3fdf39.png)

**Comment by Jungyubw** [comment]
Will do

**Comment by Jungyubw** [comment]
fixed
