### ISSUE TITLE
What happened to conf. len?

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#2004]
![image](https://user-images.githubusercontent.com/14874904/28074490-b1847dc2-6626-11e7-90aa-d9dd5845af5e.png)

**Comment by Abdelghani90** [comment]
@robnist  @haffo  We hide the conformance Length for version <=2.5.1.

**Comment by robnist** [comment]
Why?

We are using the latest conformance model regardless of the version. Although conformance length did not exist in version prior to 2.6 it is a construct that can still be used. Much like min. length which was not introduced until version 2.7.
