### ISSUE TITLE
table search results don't make sense

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#202]
The search function for the table mapping activity returns unexpected results when searching with a number. In the example below, only one table number contains the number 96 which was the search term (by the way where is table 0396?). Using a name search returns similarly odd results. Try searching with "ty" and see what you get back (I got Discharge Disposition for example)
![image](https://cloud.githubusercontent.com/assets/17408249/13329811/9e268118-dbbb-11e5-8681-b9ad751b24f0.png)

**Comment by Jungyubw** [comment]
fixed
