### ISSUE TITLE
select table button arrangement

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#203]
In the table mapping activity, I would rather see the "select this table" button down in the lower right so that it's more obvious that you need to select the table by clicking the button. Given that clicking this button closes the window, it makes sense to have next to the "close" button. Also, I think "cancel" would be better than "close", your options really are "select the table and close the window" or "just close the window"
![image](https://cloud.githubusercontent.com/assets/17408249/13329832/c228e79a-dbbb-11e5-9eda-54a16f7fb194.png)

**Comment by Jungyubw** [comment]
Done
