### ISSUE TITLE
not enough work space

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2040]
On a 14 inch laptop screen, roughly 75% of the vertical space is initially not given over to content. I think this could be a lot more compact.

![image](https://user-images.githubusercontent.com/17408249/28318937-12a64886-6b92-11e7-8389-236f3c005f8f.png)

It is possible to scroll down to the content, but given that there are two vertical scroll bars, it's very easy for a user to accidentally scroll all the way to the top of the screen and have all this stuff reappear.

A few adjustments makes more room for the important stuff
![image](https://user-images.githubusercontent.com/17408249/28319345-3c2fa9ee-6b93-11e7-8136-a1d5e4ecf259.png)

The content of the yellow bar (which is used less frequently) could be housed in a new drop down menu

![image](https://user-images.githubusercontent.com/17408249/28331128-97758acc-6bb5-11e7-82b0-ba77eadf2203.png)

**Comment by Abdelghani90** [comment]
Hi Craig, 
Thanks for your propositions. I agree with you. I will discuss this with the team and start implement ASAP. Please feel free to give us any other idea to make the tool looks better.
