### ISSUE TITLE
selecting the CP context 

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2047]
When I try to assign a usage of C to a segment in a message and then add a condition predicate, it looks like the only context I can select is the whole message level. If that is the case, why even bother have the user select a context? If I do something different, are other contexts available? If there is no decision to make, then just use the only context. It makes it easier for users.

![image](https://user-images.githubusercontent.com/17408249/28382433-ab02d03a-6c83-11e7-9136-55347eb4f603.png)

**Comment by Abdelghani90** [comment]
If the segment is inside a group then you have a choice to select its parent group or the message.

**Comment by robnist** [comment]
Reviewed and answered at NIST meeting.
