### ISSUE TITLE
minor changes in data type library data type selector

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2048]
When adding a new data type in a data type library, there are several changes that should be made:

- Elsewhere you use "Data Type" but here (green arrow) you say "Datatype". You should be consistent
- Is "USER"  (orange arrow) the right word when creating a master data type library? Do you even need to say anything other than "Add Data Type"?
- Typo (black arrow) - "Extesion" should be "Extension" - missing an "n"
- The red type on a blue background (yellow boxes) is hard to read. White (or even yellow if you want a different color) would be easier to read

![image](https://user-images.githubusercontent.com/17408249/28418705-50ebd2be-6d22-11e7-9b12-62a56182eac2.png)

**Comment by Abdelghani90** [comment]
Thanks I will fix this.
