### ISSUE TITLE
drag and drop in CS editor doesn't work in all cases

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2049]
When I work on my laptop, if the node in the context tree is high up in the tree (so high that the whole constructor box isn't visible at the bottom of the window), then it's not possible to drag and drop it into the node section. 
![image](https://user-images.githubusercontent.com/17408249/28423420-959de1a0-6d30-11e7-9288-bda1832fe0a6.png)

When I try and to drag and drop the node, nothing fills in at the bottom (I can't reveal the place where I have to drag the node to:
![image](https://user-images.githubusercontent.com/17408249/28423215-10ce71f6-6d30-11e7-89fe-e2bccaaa681c.png)

**Comment by robnist** [comment]
Agreed. I have a similar comment in 2046 I think.

My suggestion is to either remove the drag/drop feature and just select in the node in the tree.
And/or move the "CP builder" to the right side of the panel where there is a lot of real estate and I really don't even know what the purpose of the right side information is supposed to be telling me.

Also, the tree should by default be expanded.

So I think the drag and drop can remain if the "builder" is move to the right side panel.
