### ISSUE TITLE
Configuration - Preference (Co-constraint table in Export)

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2054]
Currently, the exported Co-constraints table is not showing the OBX-2 value when  a flavor is not assigned in the co-constraint table. But, when a flavor is assigned in the OBX-2 (DM_Flavor) column, the export shows both columns. Rob, will like to see a "Preference" choice to be added to the Export configuration.  See attached figure. Please, discussed with Rob for final approval. For now, when a flavor is not assigned the export could grey out the OBX-2 flavor column. 

![config](https://user-images.githubusercontent.com/14842422/28543024-6c93313e-708c-11e7-8761-46d341c64e5f.png)

**Comment by smartinez290** [comment]
Sorry, Copied the wrong image.

![config](https://user-images.githubusercontent.com/14842422/28543261-393bd3d0-708d-11e7-9f06-dd09e80029bf.png)

**Comment by afrold** [comment]
We should display all references in co-constraint, dynamic mapping. They are all considered required.

**Comment by afrold** [comment]
@maxence-lefort don't forget that one. See my previous comment.

**Comment by smartinez290** [comment]
@maxence-lefort I am having issues with this one. The export is not behaving correctly. I  selected in the configuration: "Duplicate OBX datatype value when no flavor has been selected" the data type was not duplicated.

**Comment by maxence-lefort** [comment]
@smartinez290 I just tried and it works. Are you testing with an OBX datatype?

**Comment by maxence-lefort** [comment]
What's displayed in the UI:
<img width="1162" alt="screen shot 2017-09-01 at 10 22 03 am" src="https://user-images.githubusercontent.com/13853131/29974005-7c71d416-8eff-11e7-8de1-1f75df8d19ab.png">
Configuration enabled:
<img width="1179" alt="screen shot 2017-09-01 at 10 21 30 am" src="https://user-images.githubusercontent.com/13853131/29974026-8e901c16-8eff-11e7-88a7-bfd6c77a7a6a.png">
Configuration disabled:
<img width="1175" alt="screen shot 2017-09-01 at 10 21 38 am" src="https://user-images.githubusercontent.com/13853131/29974030-956395ea-8eff-11e7-8d82-8aa701a6e6a4.png">

**Comment by smartinez290** [comment]
@maxence-lefort  it is working I understood the opposite from the description of the configuration.
