### ISSUE TITLE
DTM predicate builder

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2055]
There is no button to save my predicate or to close the dialog box
![image](https://user-images.githubusercontent.com/13591511/28543099-aebcff72-708c-11e7-8fd5-6bef0419e3be.png)

I also got a message asking my if I really wanted to change cardinality from 0..1 to 0..0, but I never set any cardinality ?

**Comment by Abdelghani90** [comment]
it is not a dialog i think. you should only save a datatype.

**Comment by carolinerosin** [comment]
maybe add a button or something just to close the dialog box when the user is done with the predicate ?

**Comment by Abdelghani90** [comment]
OK I will fix it
