### ISSUE TITLE
Enable to define predicate in profile component

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2056]
I am able to change the usage to C, but nothing happens when I want to add the predicate

![image](https://user-images.githubusercontent.com/13591511/28544595-c3833656-7091-11e7-9479-2e64742ddcf0.png)

**Comment by Abdelghani90** [comment]
you click on "Need Predicate"?

**Comment by carolinerosin** [comment]
so I tried again this morning and now it seems to work. Yes I was clicking on "need predicate" and the dialog wasn't showing up yesterday. Hard to tell what's going on, since it is working know. I'll close the ticket and will re-open if I run into the same problem again

**Comment by carolinerosin** [comment]
ok so I am having the same issue right now with "add conf.statement" button : I click, but nothing happens. I tried to refresh, log out. log in, use a different browser, same issue every time.
