### ISSUE TITLE
Composite Profile - IG Style Export 

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2062]
I created a composite profile using a profile components with an item (MSH_1) selected at the message level. Added a comment to the field. The output is showing the comment in various places in the composite profile definition and it also appears in the MSH-1 field . See image. 

![image](https://user-images.githubusercontent.com/14842422/28683331-30f68b64-72ce-11e7-897e-9c294193b54c.png)

**Comment by afrold** [comment]
Need in[put from @Jungyubw
