### ISSUE TITLE
GVT - Constraint failure on OBX segments

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2065]
The value of OBX-1 is correct.. Why the tool is generation this constraint error?
  | IZ-20 - The value of OBX-1 (Set ID - OBX) SHALL be valued sequentially starting with the value '1'.
-- | --

OBX|1|CE|64994-7^Vaccine funding program eligibility category^LN|1|V05^VFC eligible - Federally Qualified Health Center Patient (under-insured)^HL70064||||||F|||20120701|||VXC40^Eligibility captured at the immunization level^CDCPHINVS
OBX|2|CE|30956-7^vaccine type^LN|2|88^Influenza, unspecified formulation^CVX||||||F
OBX|3|TS|29768-9^Date vaccine information statement published^LN|2|20120702||||||F
OBX|4|TS|29769-7^Date vaccine information statement presented^LN|2|20120814||||||F

**Comment by smartinez290** [comment]
@Jungyubw per Hossam:
The context of SetID constraint should be the VXU_V04.ORDER.OBSERVATION group and not the OBX segment since it’s the group that is repeating and not the segment.

 

<Constraint ID="IZ-20" Target="1[1]">

<Description>

The value of OBX-1(Set ID - OBX) SHALL be valued sequentially starting with the value '1'.

</Description>

<Assertion>

<SetID Path="1[1]"/>

</Assertion>

</Constraint>

**Comment by smartinez290** [comment]
@Jungyubw and @HossamT I moved the constraint to the observation group, the error is gone, but the constraint error is not triggered when I alter the order, were it supposed to get an error.

**Comment by HossamT** [comment]
I need to see the actual generated constraint to debug it.

**Comment by smartinez290** [comment]
This is working now.
