### ISSUE TITLE
Delta functionality - 

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2073]
Notice how the IG title overlays the Data type column

![image](https://user-images.githubusercontent.com/14842422/28935367-5409ffd0-7852-11e7-9a59-107cf60170cf.png)

**Comment by smartinez290** [comment]
@Abdelghani90 notice that now I can even select the IG

![delta](https://user-images.githubusercontent.com/14842422/29840790-2f196128-8cd1-11e7-80ce-f44495038540.png)

**Comment by Abdelghani90** [comment]
please check if you have an IG with version selected
