### ISSUE TITLE
Can't add data type from Master Library

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2074]
I created a master data type library, but in the IG editor, I can't add values from it. I am able to select the library, but none of the data types are available to be selected. 

![image](https://user-images.githubusercontent.com/17408249/28935861-760d91ca-784b-11e7-989b-86d298936182.png)

**Comment by Abdelghani90** [comment]
you cannot import the data type if it is not published.
if your data type is published. you can see it only if the version of the igdocument is compatible with the datatype.

**Comment by csnewman88** [comment]
OK. thanks
