### ISSUE TITLE
what is a "shared data type"?

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2075]
I see an option in the IG editor to add a shared data type, but I'm not sure what that is and when I try to do it, there doesn't seem to be anything to add. This will be confusing to users.

![image](https://user-images.githubusercontent.com/17408249/28935927-ac2e82e6-784b-11e7-82af-db2d7beadcd9.png)

**Comment by Abdelghani90** [comment]
here you can import the data type shared with you.
