### ISSUE TITLE
Error on server when trying to work on value sets

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2081]
I get the error every time I select a value set from the menu on the left.
![image](https://user-images.githubusercontent.com/13591511/29032114-509a2bb8-7b5e-11e7-986c-6843d8e81f6c.png)

**Comment by Abdelghani90** [comment]
@carolinerosin Please check if the problem is resolved

**Comment by carolinerosin** [comment]
did you update on production as well or should I just check on dev ?

**Comment by Abdelghani90** [comment]
check the production please

**Comment by carolinerosin** [comment]
looks like I still have the issue on production
