### ISSUE TITLE
Duplicate value sets ?

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2082]
I am not sure where the duplicates come from ?
The cross reference feature does not seem to work, so I can't check if they are all in use in my IG
![image](https://user-images.githubusercontent.com/13591511/29032233-b52dd458-7b5e-11e7-8d53-b25b49a371a9.png)

**Comment by Jungyubw** [comment]
@carolinerosin please share your Ig with my account (tcamt).

Thanks.

**Comment by carolinerosin** [comment]
shared (LRI R2 IG)
