### ISSUE TITLE
Cannot find datatype error

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2083]
I started to get that error message again today (I didn't for a while, but now it's back)
It happens when I try to select the conformance profile in the left menu. 

![image](https://user-images.githubusercontent.com/13591511/29032480-82375b2c-7b5f-11e7-9989-fe947869e2a9.png)

**Comment by Abdelghani90** [comment]
@carolinerosin  please re-import the missing data types (if I remember ST 2.8.2 ,TX 2.8.2 and NM 2.8.2 ) close and re-open and let me know if the problem is resolved
