### ISSUE TITLE
GVT export not working (null pointer exception)

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2084]
![image](https://user-images.githubusercontent.com/13591511/29036234-9bdccaa0-7b6c-11e7-93a7-b7f42020dd59.png)

**Comment by afrold** [comment]
@carolinerosin please share your ig document with @maxence-lefort.

**Comment by Jungyubw** [comment]
@carolinerosin please share your Ig with tcamt account (it's my test id)

I will look at it.

**Comment by carolinerosin** [comment]
shared (eDOS and LRI R2)
