### ISSUE TITLE
XML export not working

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2085]
I get a page with this: 

{"text":"internalError","skip":false,"resourceId":null,"manualHandle":"false","version":null,"scope":null,"date":null,"id":null,"type":"danger"}

**Comment by Jungyubw** [comment]
fixed

**Comment by carolinerosin** [comment]
was it fixed on production as well ?

**Comment by afrold** [comment]
We are planning production deployment on tuesday.
