### ISSUE TITLE
Change datatype root in datatypes as well

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2098]
I don't remember if that was already reported, but we need to add "change datatype root" feature in the datatypes as well (not only segments).

**Comment by carolinerosin** [comment]
A few more thoughts about that. I think we decided to not allow that to prevent users from creating elements that have more that fields/components/subcomponents level that allowed in HL7. @robnist we'll need your input on that issue.

In the Labs IG, sometimes I can "get around" by importing a datatype from a future version, because the folks writing the IG's intent was to pre-adopt (with saying it). This is the example from eDOS IG:
![image](https://user-images.githubusercontent.com/13591511/29075246-cd44a7bc-7c1f-11e7-9276-b56614d45742.png)
No mention of pre-adoption in the current pdf IG

If I look at CQ v 2.5.1, component 2 is "CE"
![image](https://user-images.githubusercontent.com/13591511/29075303-ee4be3da-7c1f-11e7-9832-4b018f918175.png)
I cannot change that CE to a CWE in IGAMT

I can import CQ from 2.6, where component 2 is "CWE"
![image](https://user-images.githubusercontent.com/13591511/29075359-18e851fa-7c20-11e7-9d6d-6aefbc4bdde3.png)

Then create my flavor by changing the flavor of component 2
![image](https://user-images.githubusercontent.com/13591511/29075385-36cc680a-7c20-11e7-948b-46faf21a58c7.png)

So in that case, I can find a workaround.

In other cases I can't.

RFR datatype definition in the eDOS pdf IG 
![image](https://user-images.githubusercontent.com/13591511/29075450-69916646-7c20-11e7-9a7b-8a6a3ca2fc66.png)

I cannot find an HL7 version where component 6 is a "CWE", so there is no way for me to create the datatype flavor as described in the current eDOS IG.

**Comment by afrold** [comment]
@robnist any thought on this ?

**Comment by carolinerosin** [comment]
Implemented and working
