### ISSUE TITLE
Usage column for segment in profile component

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2102]
I don't think the usage for a standalone segment in profile component makes sense ?

![image](https://user-images.githubusercontent.com/13591511/29086323-35bdab66-7c40-11e7-8fea-859354212fe1.png)

**Comment by afrold** [comment]
Probably, The idea is to apply set the usage everywhere this segment is used.  @robnist ?

**Comment by carolinerosin** [comment]
I see - I don't see a use case for that on the top of my head, but maybe Rob does. I find it more clear to add the segment from the message tree, and change the usage there.
If we leave it, I would remove the * because it looks like it is required to select a value.

The use case that I would see and now realize is missing is changing a segment flavor with a profile component.
For example, in my base profile I use "MSH" (from HL7), but I'd like to create a composite profile that uses "MSH_GU" and a composite profile that uses "MSH_NG" for example.

**Comment by afrold** [comment]
ok, created the following ticket to select flavor: https://github.com/haffonist/igamt/issues/2104

**Comment by robnist** [comment]
This is an illogically place to put this type of feature (it is mixing apples and oranges). The better way to accomplish this is by selecting the segment usage under the Message structure at the locations in the message where you want to change it.
Decision is to disable the usage and cardinality columns.
