### ISSUE TITLE
Profile Component- adding OBX segment flavor and modifying co-constraints

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2105]
the functionality is there, but I can't make any modifications to the co-constraint table.

**Comment by smartinez290** [comment]
@Abdelghani90 have you worked on this issue? I am in the dev server, I am able to edit the co-constraint table, but I can't save the update.

**Comment by Abdelghani90** [comment]
No I did not work on it. I will fix it by Tomorrow.
 Thanks
