### ISSUE TITLE
duplicate checking with multiple code systems

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#211]
What is the plan for duplicate values where the Code System is different? For value sets used in complex data types (CWE, CNE, etc), this is OK but not for value sets used in simple data types (IS, ID). The value set editor seems to flag them based on value alone, but will still save the value set.
![image](https://cloud.githubusercontent.com/assets/17408249/13330175/34f1914a-dbbd-11e5-8fe1-9d0535d2a519.png)

**Comment by Jungyubw** [comment]
Done
