### ISSUE TITLE
Composite profile co-constraint is wrong

### ISSUE THREAD

**Issue by afrold** [haffonist/igamt#2110]
Created a profile component on OBX from message tab 
Created a co-constraint 

The generated co-constraint on the composite profile looks like: 
![coconstraint](https://user-images.githubusercontent.com/13695248/29130164-058efa3c-7cf7-11e7-9c6b-02f3f9e21945.png)

**Comment by afrold** [comment]
Please fix ASAP.

**Comment by Abdelghani90** [comment]
I will do it
