### ISSUE TITLE
CP edit pencil is a delete??

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#2113]
I clicked on this to edit because it has the "O" and "C" and it wants to delete, I just want to edit. IF I can't edit then this need to be a delete. We need to discuss this workflow....

![image](https://user-images.githubusercontent.com/14874904/29133742-74866c3a-7d02-11e7-8da5-9a35eb5bd388.png)

**Comment by afrold** [comment]
ok, for now I add both edit and delete pencil. 
Please wait for next deployment today.
