### ISSUE TITLE
Remove columns in profile view

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#2132]
These will always be empty so get rid of them.

![image](https://user-images.githubusercontent.com/14874904/29173957-ddaeb4c8-7db2-11e7-84ff-24386d115f77.png)

**Comment by afrold** [comment]
The fields and component need those columns.

**Comment by afrold** [comment]
I am closing this. Please reopen if it is applicable

**Comment by robnist** [comment]
This is a generic solution (and I get that) but for this view it doesn’t make sense. For this view can you set the default columns to exclude those at the message level. This way you can keep the generic component and use it the way that makes sense for this view.
