### ISSUE TITLE
Next button doesn't do anything

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2169]
We creating a new IG, the pop-up box includes a "Next" button, but clicking it doesn't do anything. You have to directly click on "Message Events" to switch screens (I assume that is what "Next" should do). I suggest you either enable the button or remove it completely (I don't have a strong preference which one you do although the "Message Events" is pretty easy to miss)

![image](https://user-images.githubusercontent.com/17408249/29285384-f5893408-80f3-11e7-89f2-ef489342f740.png)

**Comment by csnewman88** [comment]
Once you get to the Message Events screen, the "Back" button does work there.

**Comment by Abdelghani90** [comment]
@haffo the extension is required ? because if you have the extension it works
