### ISSUE TITLE
data type rending issues

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#225]
Some odd stuff is in some of the Data Type value sets in the PDF output (see red boxes below)
Also, I think it would look better if the first column merged some cells when a component has multiple lines (compare the green boxes below)

![image](https://cloud.githubusercontent.com/assets/17408249/13330596/22828b8e-dbbf-11e5-8e86-696eab610d58.png)

**Comment by olivier-m-mr** [comment]
Constraints now appears in a separate subsection.
