### ISSUE TITLE
bullet points not showing up in the output

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#226]
The PDF output include bullet points when they are used in text. Also note that text between lists of bullet points does not appear at all (highlighted in the screenshot)

From the tool:
![image](https://cloud.githubusercontent.com/assets/17408249/13333936/fce3fa6a-dbce-11e5-9a05-996b9480a4c8.png)

From the PDF output:
![image](https://cloud.githubusercontent.com/assets/17408249/13333887/da03f680-dbce-11e5-9ef6-e4f427386b73.png)

**Comment by haffonist** [comment]
Word is fixed
