### ISSUE TITLE
Word export freezing

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2279]
Per Mead, "when  I try to get the document out of protected mode so I can navigate, Word freezes and then refuses to go on.    This may be related to the fact that the document appears to have field values that are linked to other files.  That is something that I urge the IGAMT team to remove"

**Comment by afrold** [comment]
@maxence-lefort please fix this.

**Comment by maxence-lefort** [comment]
@haffonist Word issue, not export issue. Sandra sent me the document and I have no problem modifying it.

**Comment by smartinez290** [comment]
@haffonist I will send it if he has the issue again. I think he already took care of it.
