### ISSUE TITLE
Values missing from sizeable value set is causing validation error

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2288]
The value set PHVS_CauseOfDeath_ICD-10_CDC is too big. GVT validation is failing due to missing values in the table.

**Comment by Jungyubw** [comment]
fixed but need to QA 

@smartinez290 please share your Ig with my account (tcamt).

Thanks.

**Comment by smartinez290** [comment]
@Jungyubw I just shared the IG.

**Comment by smartinez290** [comment]
@Jungyubw and @HossamT GVT validation is not issuing an alert on the ICD-10 value set, that is to be excluded from validation. Need to add all the value sets that are excluded from validation.
