### ISSUE TITLE
Types within Types_ B missing from export

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2290]
Per Mead: One thing I am looking for is to be able to define data type flavors for components within a data type.   These do not seem to come through on the export.

I am attaching my most recent.   Look for HD_BR_AA, and SAD_BR.   Both are declared within the tool, used within data types – you can see the references in the export, but not actually exported.   I had thought this was a feature to be included.  Am I mistaken there?
[HL7-Version-2.6-Implementation-Guide--Vital-Records-Birth--Fetal-Death-Reporting-Release-1---US-Realm-5898caa884ae9be46ff21abc_20170817_155419.docx](https://github.com/haffonist/igamt/files/1235534/HL7-Version-2.6-Implementation-Guide--Vital-Records-Birth--Fetal-Death-Reporting-Release-1---US-Realm-5898caa884ae9be46ff21abc_20170817_155419.docx)

**Comment by maxence-lefort** [comment]
Fix in PR #2337

**Comment by smartinez290** [comment]
@maxence-lefort is this this one fixed in next deployment also?

**Comment by maxence-lefort** [comment]
@smartinez290 yes, everything that is in the "Waiting for QA" pipeline is fixed.
