### ISSUE TITLE
V/S Missing from Export

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2293]
Per Mead: " I am looking for the value set PHVS_BirthAndFetalDeathFinancialClass_NCHS.  It is cited multiple times within the IG text, is included within the value set list for the tool, but does not appear within the export.  Can you see the reason why?"  This is on the HL7 Version 2.6 Implementation Guide: Vital Records Birth & Fetal Death Reporting Release 1  IG.

**Comment by smartinez290** [comment]
Per Mead:
PHVS_BirthReportingMessageType
PHVS_BirthReportingEventType
PHVS_BirthReportingMessageStructure

He also mentioned this one:
PHVS_BirthReportingAssociatedPartyIDType_NCHS

All are cited within the data type MSG_BR, none make it through exit.

When you record the ticket, can you also ask for some estimate of when this is likely to be delivered.  This is a feature that I promised to the WG, but it will also want me to publish in a timely fashion.

**Comment by smartinez290** [comment]
PHVS_CityPlaces
PHVS_StatesTerritoriesProvinces
These also
PHVS_Country_GEC
PHVS_BirthReportingAddressType
PHVS_County_FIPS_6-4

**Comment by smartinez290** [comment]
There is also PHVS_ProcessingID_HL7_2x..  It is cited in PT_BR.

**Comment by smartinez290** [comment]
@maxence-lefort was this issue resolved?

**Comment by maxence-lefort** [comment]
@smartinez290 yes, it's going to be fixed in the next deployment.

**Comment by smartinez290** [comment]
@maxence-lefort doing the QA, Harold told me the tool was deployed yesterday. I still see the same issue. The v/s are not included in the export.
