### ISSUE TITLE
Conformance Statement ID generation

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2302]
I used the new "constant value" option in the segment definition (red box below)

![image](https://user-images.githubusercontent.com/17408249/29533000-7403553a-8675-11e7-8e7d-2532b7a8d8f7.png)

And it generated Conformance Statements, but it auto-generates the Conformance Statement ID which are then different than the format I used elsewhere. I like the idea of specifying it in the segment definition table but I don't want to have different ID formats. 

![image](https://user-images.githubusercontent.com/17408249/29533155-40a06a10-8676-11e7-8eaa-0829aa9be02b.png)

We should talk about CS ID generation. Should they all be manual or all be automatic?

**Comment by Abdelghani90** [comment]
@Jungyubw Are you working on this ?

**Comment by Jungyubw** [comment]
Not yet, but I will.

We discussed this issue with Rob.

**Comment by Jungyubw** [comment]
Please check #2351 .
We decided "Constant value" and "Single Value" will not be included into Conformance statements.
