### ISSUE TITLE
Add value set description

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2305]
There is room for a Description when selecting a value set to bind but it's not populated. It would be helpful if it was populated with the value set name, especially where there are different flavors of value set based on the same HL7 table.

![image](https://user-images.githubusercontent.com/17408249/29567109-d1366944-8711-11e7-8130-95f66d5e3cdd.png)

**Comment by Abdelghani90** [comment]
@Jungyubw ll take this
