### ISSUE TITLE
duplicate value set export

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2306]
Sorry if this is a duplicate to a previously reported issue, it seems vaguely familiar.

Some value sets are being exported multiple times. I suspect that it may be because they are listed in co-constraints in multiple OBX segments.

![image](https://user-images.githubusercontent.com/17408249/29567890-2daaa2ce-8714-11e7-986b-d6aec4852f76.png)

![image](https://user-images.githubusercontent.com/17408249/29567966-781b6ec4-8714-11e7-8560-0c7e28bb5b99.png)

**Comment by Abdelghani90** [comment]
@csnewman88  Please provide me the name of your IGdocument

**Comment by maxence-lefort** [comment]
@csnewman88 this should be fixed in the next deployment. Thanks
