### ISSUE TITLE
missing value set cross reference

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2307]
When the single value binding is used, even if a value set is used as a source of the value, that linkage doesn't show up in the Cross Reference tab in the value set. Given that a value from the value set is bound, it seems like it should show up in the Cross Reference list.

![image](https://user-images.githubusercontent.com/17408249/29569313-be53bb54-8718-11e7-915f-c0e4b36c7a49.png)

![image](https://user-images.githubusercontent.com/17408249/29569232-7f49d510-8718-11e7-9956-606700f91775.png)

**Comment by Abdelghani90** [comment]
We don't need to. there is no relationship between the single code we create and the old value set.
