### ISSUE TITLE
Cross Reference binding location incorrect

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2308]
The Binding Location in the value set Cross Reference tab seems to be incorrect. They seem to change but I've definitely seen them be wrong (see example below)

![image](https://user-images.githubusercontent.com/17408249/29569498-4e3ee55e-8719-11e7-9e0a-2cae3c9dbee5.png)

This one is bound to XTN.2 not XTN.3
![image](https://user-images.githubusercontent.com/17408249/29569582-87e6b232-8719-11e7-8b6e-63e4f7bb60dc.png)

**Comment by Abdelghani90** [comment]
@csnewman88 I can't produce this issue. Please give me the name of the IG document.
