### ISSUE TITLE
search for codes when doing a single value binding

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2326]
When creating a single code binding, after the value set is selected, it would be nice to have a way to search the codes in the value set. Many value sets are small, but some like Order Control Code or ID Type are large and finding the right code may take a lot of clicking and scrolling.

![image](https://user-images.githubusercontent.com/17408249/29675885-1ece4bd0-88bc-11e7-853c-667395977a3e.png)

**Comment by Jungyubw** [comment]
Done
