### ISSUE TITLE
Verification of table 0125 and Data type in IGAMT IG

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#2353]
There are cases where table 0125 reference a data type that is not in the IG. this causes issues in the validation so we need to include these into the XML. We need to verify that these match and if not provide feedback to the user to create a flavor of table 0125 and remove codes not used (suggested) or to have them import the missing data types if they want these data types supported in OBXs (observations).

Currently we decided to take the value set version and import the missing data types into the XML (but not into the IG). This needs to be documented as an IGAMT implementation decision.

**Comment by Jungyubw** [comment]
fixed
