### ISSUE TITLE
Cloning a co-constraint row 

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2362]
I am trying to change the DT in OBx-2 column after cloning a row in the co-constraint table. The tool adds the DT, does not replaced the existing one. 
![coconstraintclone](https://user-images.githubusercontent.com/14842422/29879230-8259bfd0-8d72-11e7-988d-0740a944cfad.png)

**Comment by smartinez290** [comment]
Check the export. It is displaing NM in the OBX-2 col. and in the flavor is using CWE_BR.

![image](https://user-images.githubusercontent.com/14842422/29879630-9bb27458-8d73-11e7-832a-239a26a0f2fb.png)

**Comment by Jungyubw** [comment]
I guess this issue was related with previous CoCon Issue.
@smartinez290 Please check this issue after deployment.

I put this ticket for QA

**Comment by smartinez290** [comment]
A wrong warning message in the OBX-2 after cloning a row.

![image](https://user-images.githubusercontent.com/14842422/30293802-b8e4415c-9708-11e7-97f1-546aec72ce92.png)

**Comment by smartinez290** [comment]
Sorry! I miss understood the message.
