### ISSUE TITLE
Co-constraint dependency verification needs to be added

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2363]
In the co-constraint table,  OBX-2 must be provided  if OBX-3 and OBX-5 are provided.

**Comment by Jungyubw** [comment]
I have implemented to show warning when any coConstraint data is wrong.
However, the segment could be saved even if coConstraint data is something wrong. 

If you think we need to allow "save" just valid CoConstraint Segment, let me know. (or make another ticket).

**Comment by afrold** [comment]
only if co constraint is valid, rigth ? user should now save a segment with wrong co-constraint.
