### ISSUE TITLE
PlainText/Presence constraints in Constraints.xml export

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2375]
I noticed when I export my IG that predicates/conformance statements "PlainText" rules are not combined with "Presence" checks.
Example: 
![image](https://user-images.githubusercontent.com/13591511/30072828-8a69b894-9239-11e7-969b-0bbfa38a38d8.png)
The way "PlainText" currently work, it will succeed (return true) if the path is not populated in the message.
So in my example, non-presence of OBR-11 will make the if statement succeed (evaluation of the condition will return 'true'); usage will be set to "R".

If the element is not present, "PlainText" evaluation would return "true". So combined with a "not", the condition evaluation will now return "false".

Example:
![image](https://user-images.githubusercontent.com/13591511/30073103-992aa82e-923a-11e7-84f0-9c503afc8961.png)
In that case, the if statement will fail (the condition evaluation will return false); usage would be set to "RE".

In my hand written profiles, I always combine <PlainText> with <Presence> to avoid having this issue. 
If think it would be confusing to the user that in one case a field not being present would make the if statement pass and in the other case it would fail.

Another solution could be to change the result of the evaluation of PlainText to "inconclusive" (instead of success) if the element is not present. but that would require changes in the validation (and making sure it doesn't break anything).

This is how I implement that when I write it by hand
![image](https://user-images.githubusercontent.com/13591511/30073976-b464888c-923d-11e7-9362-58934b39ca79.png)

**Comment by Jungyubw** [comment]
I agree. I will add presence check. 

Do you think that this one should be just for PlainText? what about the other?

**Comment by carolinerosin** [comment]
I'll check how the others expressions are implemented in the validation and will let you know

**Comment by carolinerosin** [comment]
Based on the specification Salifou wrote (maybe we should check with @HossamT that these specifications are still accurate), I would add presence check for the following expressions (if used in IGAMT) for **predicates only** (not conformance statements):
PlainText
Format
NumberList
StringList
SimpleValue

I am not sure how we want to handle ValueSet expression, I have never seen it used in a predicate condition.

Also I am unsure if we want to do that for conformance statements as well. It may make sense in the <IMPLY> expression (the condition), but it does not seem right to add it to a simple <PlainText> for example. Maybe we should wait for Hossam to come back and see what he thinks.

**Comment by Jungyubw** [comment]
Fixed.

But ...

@carolinerosin  what do you think of "NOT"?

![image](https://user-images.githubusercontent.com/13385213/30182320-653212a4-93e4-11e7-94bb-fb45223de433.png)


I think it is okay but need your thought.

**Comment by Jungyubw** [comment]
![image](https://user-images.githubusercontent.com/13385213/30182298-55040aea-93e4-11e7-8dad-08a86f2a2ba6.png)

**Comment by carolinerosin** [comment]
I think it is fine.

Without Presence assertion, we would have something like that
<NOT> <PlainText Path="1[1]" Text="dsdsd" IgnoreCase="false"/></NOT>
So if OBX-1 is not present, PlainText returns "true", and NOT(true) -> false
So in that case our assertion fails when OBX-1 is not present

With Presence assertion we have
NOT(AND(Presence,PlainText). Presence returns false, PlainText returns true. So we end up with NOT(AND(false,true)) -> NOT (false) -> true
Our assertion will pass, which I think is the expected behavior in that case (the starting assertion is "The value of OBX-1 SHALL not be 'dsdsd'", so if the value is not present, this assertion shouldn't fail).

Maybe the best solution would be to change, in the validation, what is returned when an element is not present. That would avoid confusion.
My issue with the way it is implemented now is that PlainText and Not(PlainText) should have the same result for an element that is not present (and currently they have not - hence the Presence assertion that is added). Let's keep that topic open to discuss with the group once Hossam is back.
