### ISSUE TITLE
Export to GVT fails

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2376]
Working with the LRI R2 IG. I am trying to export the base Conformance profile only (did not try with composite yet).
![image](https://user-images.githubusercontent.com/13591511/30078488-61b01364-924b-11e7-9df6-b14846fbe516.png)

**Comment by Jungyubw** [comment]
@carolinerosin Please share your LRI R2 IG for me (TCAMT)

**Comment by carolinerosin** [comment]
I think you already have it

**Comment by Jungyubw** [comment]
@carolinerosin Yes I got it. I have tried to export XML scripts and all of them are valid by schema.

**Comment by carolinerosin** [comment]
yes, xml export works, but I can't get them in GVT. 
If I try to import the xml in GVT, here's what I got

![image](https://user-images.githubusercontent.com/13591511/30079442-2c0e00ce-924e-11e7-8dbc-5a1767aa3a07.png)

**Comment by Jungyubw** [comment]
I have checked DR_2-5-1 but it was there.

<Datatype ID="DR_2-5-1" Name="DR" Label="DR" Description="Date/Time Range">
            <Component Name="Range Start Date/Time" Usage="O" Datatype="TS_2-5-1" MinLength="0"
                MaxLength="26" ConfLength="NA"/>
            <Component Name="Range End Date/Time" Usage="O" Datatype="TS_2-5-1" MinLength="0"
                MaxLength="26" ConfLength="NA"/>
        </Datatype>

**Comment by Jungyubw** [comment]
<Datatype ID="DR_2-5-1" Name="DR" Label="DR" Description="Date/Time Range">
            <Component Name="Range Start Date/Time" Usage="O" Datatype="TS_2-5-1" MinLength="0"
                MaxLength="26" ConfLength="NA"/>
            <Component Name="Range End Date/Time" Usage="O" Datatype="TS_2-5-1" MinLength="0"
                MaxLength="26" ConfLength="NA"/>
        </Datatype>

**Comment by Jungyubw** [comment]
![image](https://user-images.githubusercontent.com/13385213/30079548-8bbb4c2a-924e-11e7-9679-865802e0ea7a.png)

**Comment by carolinerosin** [comment]
There must be something else then, because GVT does not load the profile

**Comment by Jungyubw** [comment]
Hi Nicolas.

Could you check this issue on GVT?

XML scripts looks okay.



On Sep 5, 2017, at 3:23 PM, Caroline Rosin <notifications@github.com<mailto:notifications@github.com>> wrote:


yes, xml export works, but I can't get them in GVT.
If I try to import the xml in GVT, here's what I got

[image]<https://user-images.githubusercontent.com/13591511/30079442-2c0e00ce-924e-11e7-8dbc-5a1767aa3a07.png>

**Comment by carolinerosin** [comment]
We found the issue. For some reason, the DR datatype was style used in flavors of datatypes I created (instead of DR_DTM). I changed to DR_DTM in my flavors and that fixed the issue. What I suspect is that I created the flavors before is was fixed in the standard database, so my flavor still had the issue related to DR.
