### ISSUE TITLE
Constraints.xml unique key violation (ByID)

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2377]
There are duplicates in the constraints file that are not allowed.
![image](https://user-images.githubusercontent.com/13591511/30082436-c748628c-9258-11e7-945a-41d5e3d3a5c1.png)

Files come from my LRI IG, exporting Composite profiles (I selected all of them).

[LRI-R2-CompositeProfile_20170905_160708.zip](https://github.com/haffonist/igamt/files/1278852/LRI-R2-CompositeProfile_20170905_160708.zip)

**Comment by Jungyubw** [comment]
fixed
