### ISSUE TITLE
Length is exported as NA if not available

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2406]
The basic approach of the Immunization IG is that we are silent on Optional fields. I went into IGAMT and removed all the Length and Conformance Length values for optional fields. 
![image](https://user-images.githubusercontent.com/17408249/30220023-8962f248-9483-11e7-8741-7485c84b8fdf.png)
But when I export it, the export contains NA rather than just being blank for the Length. Note that the Conformance Length seems OK.
![image](https://user-images.githubusercontent.com/17408249/30220060-abddd090-9483-11e7-979d-42a70daa0420.png)

Unless it's bad practice to remove the lengths in IGAMT, if they are removed, they shouldn't show up in the export.

**Comment by afrold** [comment]
This applies to confLength as well.
