### ISSUE TITLE
Message Infrastructure no longer has a text editor

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#243]
Most high level sections (introduction, Use Case, etc) have a text editor available to enter content ahead of the subsections that make up that section. Message Infrastructure use to have this ability, but it no longer seems to. Please add this back.

**Comment by haffonist** [comment]
Check the current state

**Comment by haffonist** [comment]
@gcr-nist 
was is this in pending ? what is the impediment ?

**Comment by haffonist** [comment]
@gcr-nist  This is fixed ?
