### ISSUE TITLE
DTM flavors are not been exported

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2434]
Here a screen shot of IGAMT showing the DTM flavors:

![image](https://user-images.githubusercontent.com/14842422/30490459-037a8aee-9a08-11e7-99af-e415d80806b2.png)

Here a screen shot of the export -- not showing the DTM flavors
![image](https://user-images.githubusercontent.com/14842422/30490424-e1966128-9a07-11e7-81fa-098a176f20dc.png)

**Comment by maxence-lefort** [comment]
@smartinez290 are those used in an exported field/dt ?

**Comment by smartinez290** [comment]
I tried to recreate this one again and it is fine. I am not sure what happened. I will close the ticket, if I get it again I will show you.
