### ISSUE TITLE
Composite Profile - single value selected not displayed in GVT

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2437]
I selected a single value from a value set when creating a Profile component. 
![image](https://user-images.githubusercontent.com/14842422/30498466-dd2058f2-9a24-11e7-82ca-6fd8055ad3e1.png)

But, the GVT is showing the following. 

![image](https://user-images.githubusercontent.com/14842422/30498450-cd0eac66-9a24-11e7-9482-eb301f88f7b3.png)

**Comment by smartinez290** [comment]
@Jungyubw where are you on this issue?

**Comment by Jungyubw** [comment]
I think this is okay because Single code binding will create conformance statement. You can see the binding at conformance statement list.
