### ISSUE TITLE
publication issues with fancy text

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#244]
The text editor includes a lot of different formatting options, some of which don't render correctly in all publication formats.
From the editor:
![image](https://cloud.githubusercontent.com/assets/17408249/13708593/20a171c4-e775-11e5-8e2a-c6ae777df64d.png)

From the PDF format:
![image](https://cloud.githubusercontent.com/assets/17408249/13708605/30130f78-e775-11e5-9d27-71a74c601534.png)

From the HTML format:
![image](https://cloud.githubusercontent.com/assets/17408249/13708682/97e328ea-e775-11e5-827d-25af1fd3ad6d.png)

From the Word format:
![image](https://cloud.githubusercontent.com/assets/17408249/13708809/292eb9cc-e776-11e5-8418-91e56190d98b.png)

**Comment by haffonist** [comment]
@csnewman88 please confirm fixes.

**Comment by csnewman88** [comment]
A few formatting issues still exist. There are even some issues in IGAMT. Note the red box which shows that the various fonts and font sizes don't seem to work. Neither do the coloring options in the "ink drop" icon.

![image](https://cloud.githubusercontent.com/assets/17408249/18389087/e1227fc8-7669-11e6-9930-fc442c361ae2.png)
![image](https://cloud.githubusercontent.com/assets/17408249/18389029/84ff44ec-7669-11e6-8dfa-076ba3832366.png)
![image](https://cloud.githubusercontent.com/assets/17408249/18389041/91844a64-7669-11e6-8f83-e813c8debd16.png)
![image](https://cloud.githubusercontent.com/assets/17408249/18389046/9e13888a-7669-11e6-94e7-59e3539ca35c.png)

**Comment by haffonist** [comment]
@olivier-m-mr this is still not fixed.

**Comment by csnewman88** [comment]
Now, this is what the Word export of the text in the previous comment looks like.

- strike through super script doesn't render right (red arrow)

- the font, font color and font size issues in the IGAMT display aren't any better in the export (blue box)

- no emoticons (pink arrow) - no big loss in my mind
- no gray text (purple arrow)
- no bordered text (blue arrow)
- no spaced text (green arrow)
- no upper case (black arrow)
-no box around the code (brown arrow)
-no images (either .gif or .png)
- no table alternate line background (purple box)

![image](https://cloud.githubusercontent.com/assets/17408249/18389255/cb9c09ac-766a-11e6-9ecd-37f0451e08ce.png)
![image](https://cloud.githubusercontent.com/assets/17408249/18389365/405de760-766b-11e6-9318-a71da5d19386.png)
![image](https://cloud.githubusercontent.com/assets/17408249/18389425/875315e6-766b-11e6-8d72-18cda3de68f2.png)

**Comment by csnewman88** [comment]
Many of the same issues (but not all of them) are in the HTML export too.

![image](https://cloud.githubusercontent.com/assets/17408249/18389618/57743c28-766c-11e6-8411-a64de1473bb9.png)
![image](https://cloud.githubusercontent.com/assets/17408249/18389633/6fb83b68-766c-11e6-8d02-7db7e6a12b07.png)
![image](https://cloud.githubusercontent.com/assets/17408249/18389645/85956974-766c-11e6-93ff-406f67bead7b.png)
![image](https://cloud.githubusercontent.com/assets/17408249/18389659/9676d16a-766c-11e6-9c70-984f789a1a20.png)

**Comment by haffonist** [comment]
@olivier-m-mr This is clearly not fixed. Any updates ?

**Comment by haffonist** [comment]
@olivier-m-mr Any updates ?
