### ISSUE TITLE
"unlicensed Froala Editor" box gets in the way

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#245]
All of the text editors have the red box saying "Unlicensed Froala Editor". Normally that isn't a problem, but if you are working the lower left corner of the editor, it seems to overlay some things. For example in the image below, some of the table editing tools are not availablle.

![image](https://cloud.githubusercontent.com/assets/17408249/13708857/66ea00a0-e776-11e5-8d6f-c3aa0efe900c.png)

**Comment by csnewman88** [comment]
It even displays over top of the predicate editor

![image](https://cloud.githubusercontent.com/assets/17408249/13711991/e8b3bd96-e786-11e5-9941-9f5cde02e6da.png)

**Comment by haffonist** [comment]
fixed
