### ISSUE TITLE
Can't save the comment in the co-constraint table

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2458]
Per Mead - "I get a blue headed box with the description, and I can change it.   However, there is no way to get IGAMT to accept the change.   I think there is a place to indicate save in the box, but it extends off the right side of my screen, so I cannot get to it."

He is correct. I tried to do it and I can't save. See image.

![image](https://user-images.githubusercontent.com/14842422/30612203-cd2acf92-9d51-11e7-987b-f6a9b9abdc79.png)

**Comment by Jungyubw** [comment]
Fixed
