### ISSUE TITLE
don't leave "notifications" visible indefinitely

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#246]
the colored "notification" bars at top are nice to let you know a document was saved or an error occured, but they don't need to stick around indefinitely (or require a user click to remove). If they should up for 5 or 10 seconds and then disappear, that will ensure that screen real estate is used efficiently.

![image](https://cloud.githubusercontent.com/assets/17408249/13709092/b8dff7ec-e777-11e5-860a-0536fd98e9a6.png)

**Comment by haffonist** [comment]
fixed
