### ISSUE TITLE
table render has some issues

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#247]
Some of the fancier table formatting options don't render well.

From IGAMT:
![image](https://cloud.githubusercontent.com/assets/17408249/13709744/211c484e-e77b-11e5-82b1-9d37ba191033.png)

From the PDF:
![image](https://cloud.githubusercontent.com/assets/17408249/13709767/38339eba-e77b-11e5-8e60-139434d42b57.png)

From the HTML:
![image](https://cloud.githubusercontent.com/assets/17408249/13709789/5487e56c-e77b-11e5-8099-f81e3268424d.png)

From the Word document:
![image](https://cloud.githubusercontent.com/assets/17408249/13709826/89304264-e77b-11e5-86eb-001105bf05d5.png)

**Comment by olivier-m-mr** [comment]
This is fixed in the html export. 
We're looking for a solution for the other export.

**Comment by haffonist** [comment]
Word is fixed

**Comment by haffonist** [comment]
@maxence-lefort @Abdelghani90 any update on this ?

**Comment by haffonist** [comment]
@olivier-m-mr update on this ?

**Comment by haffonist** [comment]
Fixed. Will deploy soon.
