### ISSUE TITLE
I can't edit a conformance predicate

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2481]
The tool still does not allow to edit a conformance predicate. I will have to delete and then add it, the capability to edit is there, but the predicate is not even displayed to edit it.

**Comment by Jungyubw** [comment]
Let's discuss about this UI at Monday meeting

**Comment by smartinez290** [comment]
No

**Comment by Jungyubw** [comment]
The edit function will be implemented new version IGAMT.
