### ISSUE TITLE
Unable to clone the VRDR IG

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2482]
I was able to clone other IGs, but not the "HL7 Version 2.6 Implementation Guide-Vital Records Death Reporting, Release 1 - US Realm". It looks like the issue is with the IG. Could this be also the reason why we can't push the TP to GVT from TCAMT?
@Jungyubw I had already shared this IG with you via IGAMT.

**Comment by Jungyubw** [comment]
I will check it. Hossam is checking for GVT issue.

**Comment by Jungyubw** [comment]
Cloning is fixed
