### ISSUE TITLE
single coded element binding for simple and complex coded elements

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#2484]
Currently we have a single value element coded binding for simple elements. We want to add this feature for complex coded elements.

Currently we have the tab "Single Code" for value set binding with one pattern and it is only active for simple coded elements. We need to make it active for both Simple and Complex. 

That is for elements (mostly fields) that are a complex coded element (e.g., CWE, CE, etc.). In this case we will use a different pattern, e.g., QBP.1 (Query Identifier) SHALL be valued **‘Z54’** AND QBP.3 (Coding System) SHALL be valued  **'PHINVS'**.

We also need to consider the binding location. However, I think we will hold off on that for now. I think in most cases when it is a constant there won't be alternatives. We will see if users agree or not.

**Comment by Jungyubw** [comment]
@haffonist 
Can I apply this logic for new angular UI?

**Comment by afrold** [comment]
No but in angualrjs

**Comment by Jungyubw** [comment]
Done
