### ISSUE TITLE
"Discard Changes"  and "Save and Continue" not functioning

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2488]
See inspection. I can recreate if you like. 

![image](https://user-images.githubusercontent.com/14842422/30972108-a9dc3278-a437-11e7-8dd9-06627471f46b.png)

**Comment by afrold** [comment]
Thanks Sandra, Unfortunately we couldn't reproduce and the logs are not helpful. Please let me know next time you have it.
