### ISSUE TITLE
Value Set Bindings Location needs to use segment name

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2505]
When exporting in Word, in the message section, the Value Set Bindings table doesn't use the segment name in the Location column. So rather then seeing the much more useful "MSH", you just see a number representing the segment number (1 in this case). See the red arrow below. The segment name has to be used. I don't think that you need to repeat the message type (ACK^Varies^ACK in this case) but can just go with the segment and field (MSH-15). 

As well, the table should be organized by location. MSH-3 should be above MSH-15 and MSH-16.

![image](https://user-images.githubusercontent.com/17408249/31033459-be674d56-a525-11e7-9413-03c3296aca66.png)

**Comment by afrold** [comment]
@maxence-lefort what about this one ?
