### ISSUE TITLE
output of comments has issues

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#251]
The treatment of comments seems a little off.

I entered a Metadata comment for the IDS data type and it showed up in the PDF in a couple of places (purple boxes)
![image](https://cloud.githubusercontent.com/assets/17408249/13710414/fba93c44-e77e-11e5-89cc-67994c5460d0.png)

I then added a Metadata comment, and a Defin.Text and Comment for JCC.1 but only two of them show up in the PDF
![image](https://cloud.githubusercontent.com/assets/17408249/13710552/c03d01b2-e77f-11e5-9adc-5bae810fdaa7.png)

PDF output:
![image](https://cloud.githubusercontent.com/assets/17408249/13710211/b127053a-e77d-11e5-8b2b-db438a6203ec.png)

**Comment by haffonist** [comment]
QA
