### ISSUE TITLE
documenting base data types

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#252]
Doesn't look like it's possible to document any of the basic data types (IS, ID, TX, etc). While many things like Data type and Predicate probably won't be needed, it does seem like a conformance statement or comment may need to be added. How would we do that?

**Comment by Jungyubw** [comment]
Harold, I think this issue related with datatype viewer not constraint viewer

**Comment by haffonist** [comment]
Craig wants to be able to add conformance statement and comment to the datatype. we don't support the conformance statement of a datatype at of now but we should.

Harold

**Comment by haffonist** [comment]
So I am assigning back to you.

**Comment by Jungyubw** [comment]
Done
