### ISSUE TITLE
Adding a comment to a segment flavor at the message level

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2525]
The comment was intended for MSH_TXT. The comment box indicates that the comment is for the MSH.

![image](https://user-images.githubusercontent.com/14842422/31180162-e3ae58d8-a8eb-11e7-9047-f504311ff26d.png)

In the Export there is no indication that the comment is for the MSH_TXT segment. 

![image](https://user-images.githubusercontent.com/14842422/31180262-2c20d8f2-a8ec-11e7-8f0b-3ae50ffdaabd.png)

**Comment by afrold** [comment]
@maxence-lefort this issue is for you.  Path should be as in the dialog.
