### ISSUE TITLE
Export allows errors in the IG if a verify is not performed

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2526]
If the user does not run a verify and there are errors, for example carnality errors, the exported IG will include erroneous carnality. Is this the intention or should an automatic verify  be performed during the export and alert the user or don't allow the user to proceed with the export until these errors are fixed?

**Comment by afrold** [comment]
It is left to the user to ensure they are creating valid data. The verification is only providing warnings at this point.
