### ISSUE TITLE
"Apply Code System for Selected Code" tab not highlighted when a code is selected

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2530]
When a code is selected, the "Delete Codes" and the "R P E" tabs are highlighted, but the "Apply Code System for Selected Code" is not, it should also be highlighted. 

![image](https://user-images.githubusercontent.com/14842422/31188160-050998f6-a902-11e7-9ffa-fc6c1a99d3e0.png)

**Comment by Abdelghani90** [comment]
if you can use it it means that it is activated. it is a different component than the buttons.
