### ISSUE TITLE
Add Value Set form CSV is not working

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2536]
I can't save after choosing the CSV file. 

![image](https://user-images.githubusercontent.com/14842422/31235929-b18c5794-a9c0-11e7-9985-3aa22453c71d.png)

**Comment by Jungyubw** [comment]
@smartinez290 
CSV file is working at my side. Please send your CSV file. I think some issues are there.

**Comment by smartinez290** [comment]
@Jungyubw I could not load the file here I will send via email.
