### ISSUE TITLE
Co-constraint validation on CWE with conditionals

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2545]
The co-constraint generated does not take into consideration a presence check, it only check that OBX-5.1 have a code in the value set provided. It fails to perform correct validation when CWE is defined as followed:

Woo is looking into it and will apply a solution after a discussion on Monday.

![image](https://user-images.githubusercontent.com/14842422/31458822-36f10f7e-ae8f-11e7-9a38-14076144211b.png)

**Comment by Jungyubw** [comment]
fixed

**Comment by smartinez290** [comment]
I was trying to test this issue, but could not export to GVT, is not showing any errors. Maybe related with the big value set issue?

![image](https://user-images.githubusercontent.com/14842422/31909217-575b55b8-b807-11e7-9b05-76f8eba8f22f.png)

**Comment by smartinez290** [comment]
I can't QA this one until the CS drag and drop issue is solved.

**Comment by smartinez290** [comment]
Woo,
I am getting the following error.  It is coming from the co-constraint table. This issue was solved, but it is back. 

![image](https://user-images.githubusercontent.com/14842422/32628503-1f47be18-c564-11e7-8104-3e7b19c6896b.png)

This is how the segment looks like:

OBX|25|CWE|21844-6^Industry^LN||^^^^^^^^Academic||||||F

Also, see the CWE definition above.

**Comment by smartinez290** [comment]
@Jungyubw I am testing also from IGAMT (pushing to GVT) and I am getting the same error.
