### ISSUE TITLE
Bound DT don't show up correctly in Segment element

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2552]
This used to work. -- Rob

![image](https://user-images.githubusercontent.com/14842422/31564324-6a608554-b030-11e7-9d3a-695c2db131fd.png)

![image](https://user-images.githubusercontent.com/14842422/31564330-6f075ac4-b030-11e7-973f-0639cb2d78c3.png)

**Comment by afrold** [comment]
Any idea Woo ?



Harold Affo

--------------------------------------------------------------------
The contents of this e-mail and any attachments are intended solely for the use
of the named addressee(s) and may contain confidential and/or privileged
information. Any unauthorized use, copying, disclosure, or distribution of the
contents of this e-mail is strictly prohibited. If you are not the intended
recipient, please notify the sender immediately and delete this email. Thank you.


________________________________
