### ISSUE TITLE
changes to the conformance statement editor

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#256]
A few changes would be helpful for the generation of Conformance Statements.
1) particularly where a field can't repeat (but in general too), not having the occurrence number in the conformance statement would make it easier to read (red arrow)
2) A conformance ID should be required before saving a conformance statement (just having [null] in the final statement isn't all that helpful (especially given there is no way to go back and edit the statement to give it one). (green arrow)
3) the segment name or data type name should be included in the statement so that it can be read more easily and out of context (blue arrow)

![image](https://cloud.githubusercontent.com/assets/17408249/13714788/53c83364-e796-11e5-9399-26eaf7e240cb.png)

**Comment by Jungyubw** [comment]
fixed
