### ISSUE TITLE
Can't add a code to a new Value Set - 2.0.0-beta7

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2575]
![image](https://user-images.githubusercontent.com/14842422/31829241-b534633e-b58a-11e7-9f6d-3d381c168f1e.png)

**Comment by smartinez290** [comment]
fixed

**Comment by smartinez290** [comment]
I can't close this issue. I am able to add but now I can save. The save button is disable.

![image](https://user-images.githubusercontent.com/14842422/31946868-fbe2d982-b8a0-11e7-8851-e32a0b5cc5b1.png)

**Comment by Abdelghani90** [comment]
Please Check if your value set is valid. the new code cannot be empty and the name of the value set cannot be duplicated to perform the save
