### ISSUE TITLE
Value set Flavor -- missing original code system (2.0.0-beta7)

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2577]
The original HL70007 value set had a code system in each code.

![image](https://user-images.githubusercontent.com/14842422/31832705-fd8a1bbe-b595-11e7-8515-f0632ae7537a.png)

**Comment by smartinez290** [comment]
I can't add a code system and assign either.

**Comment by smartinez290** [comment]
This not fixed yet

**Comment by Abdelghani90** [comment]
Please try to copy again, if the copy was there before the deployment.
