### ISSUE TITLE
Noticed extra characters after the pre-text statement

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2592]
IGAMT
pre-text
![image](https://user-images.githubusercontent.com/14842422/31949127-8c5e1ada-b8a6-11e7-883d-71d6bbe05a6a.png)

Export:

![image](https://user-images.githubusercontent.com/14842422/31949061-6605e192-b8a6-11e7-98da-52ddc0b74277.png)

**Comment by maxence-lefort** [comment]
@smartinez290 did you copy/paste this text from somewhere else? It looks like you have some unprintables characters in there.

**Comment by smartinez290** [comment]
@maxence-lefort where are the unprintable characters? in the pre-text. I think this was a cut and paste, from the IG document.

**Comment by afrold** [comment]
@maxence-lefort, any input ?
