### ISSUE TITLE
Can't Export Testing_IG (Testing in hitdev) 

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2593]
![image](https://user-images.githubusercontent.com/14842422/31951389-f9625df8-b8ab-11e7-9e3a-b67d79c38274.png)

I am able to export other profiles. @maxence-lefort Could you check why I can't export this one?

**Comment by afrold** [comment]
Check your co-constraint. Make sure you provided all values. Something might be missing.


Harold Affo

--------------------------------------------------------------------
The contents of this e-mail and any attachments are intended solely for the use
of the named addressee(s) and may contain confidential and/or privileged
information. Any unauthorized use, copying, disclosure, or distribution of the
contents of this e-mail is strictly prohibited. If you are not the intended
recipient, please notify the sender immediately and delete this email. Thank you.


________________________________
