### ISSUE TITLE
2.0.0-beta8-production: Save is not working in the Conformance Profile section 

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2600]

**Comment by Abdelghani90** [comment]
@smartinez290 Please check if you still have this issue. Check if you have a message with the same name.

**Comment by smartinez290** [comment]
@Abdelghani90 what do you mean, if I have a message with the same name?

**Comment by Abdelghani90** [comment]
you cannot save the message if you have another one with the same Identifier.
