### ISSUE TITLE
GVT export issue

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2602]
I get an error when trying to export one of my edos composite profile to GVT
![image](https://user-images.githubusercontent.com/13591511/32122145-5fa66824-bb2d-11e7-9d54-b91ba85cdfcd.png)

**Comment by afrold** [comment]
@carolinerosin Do you  have two constraint with same id ?

**Comment by carolinerosin** [comment]
I don't think so. I wanted to export the xml to double check, but it doesn't look like it's working either (nothing is happening)

**Comment by carolinerosin** [comment]
looks similar to a previous issue #2377

**Comment by HossamT** [comment]
I can't help if I don't have the XML file, that's an IGAMT issue.

**Comment by Jungyubw** [comment]
@haffonist Does this issue come from cloned Profile?

**Comment by Jungyubw** [comment]
@carolinerosin could you share your edos IG to me (id: tcamt)?

**Comment by carolinerosin** [comment]
I think it is already shared with you @Jungyubw 
I suspect something is wrong when constraint file is generated. it is not a cloned profile

**Comment by Jungyubw** [comment]
Sorry I forgot my password for Jungyubw

In “tcamt” account, there is no edos shared. Could you share your IG with “tcamt”?

Thanks.
On Nov 7, 2017, at 11:43 AM, Caroline Rosin <notifications@github.com<mailto:notifications@github.com>> wrote:


I think it is already shared with you @Jungyubw<https://github.com/jungyubw>
I suspect something is wrong when constraint file is generated. it is not a cloned profile

**Comment by carolinerosin** [comment]
is it that one ? 
![image](https://user-images.githubusercontent.com/13591511/32508852-a71f9aa6-c3b9-11e7-8ea2-72a45cd7fbd7.png)

I just re-shared it

**Comment by Jungyubw** [comment]
@carolinerosin Fixed! need deployment.

**Comment by carolinerosin** [comment]
great, thank you
