### ISSUE TITLE
Cannot save after modification to message structure

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2603]
I changes the flavor of some segments in my Conformance profile, but the save button is disabled.

![image](https://user-images.githubusercontent.com/13591511/32122559-b984aaa8-bb2e-11e7-9b5d-d74a512d7120.png)
![image](https://user-images.githubusercontent.com/13591511/32122571-c58c588c-bb2e-11e7-97ef-0aec96bb4a98.png)

**Comment by Abdelghani90** [comment]
Please check if you have another profile with the same name.

**Comment by carolinerosin** [comment]
Great thanks, the issue was the Identifier that was already in use !
