### ISSUE TITLE
Value set export -- no working properly

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2623]
Using Testing IG. in dev server.
Value set configuration setting:
![image](https://user-images.githubusercontent.com/14842422/32233087-f9a8c638-be2f-11e7-896a-5325191c3708.png)

Se "Enable configuration" and selected 3 value sets
![image](https://user-images.githubusercontent.com/14842422/32233130-0e79f82a-be30-11e7-937e-79b127d6c47e.png)

This is the export, notice that 0002_TXT is there twice, and is exporting value set that are not selected and are bounded. 
![image](https://user-images.githubusercontent.com/14842422/32233145-1d4317ba-be30-11e7-858f-646a849488bb.png)

**Comment by afrold** [comment]
@maxence-lefort I tested this and it was working. Now it is not.  
Please fix ASAP.  
Thanks

**Comment by maxence-lefort** [comment]
@smartinez290 you checked "All HL7 unbound" and "All custom unbound", that's the reason why. Can you uncheck those options and try again please?

**Comment by afrold** [comment]
if export config summary is enabled it should take precedence over the general config
