### ISSUE TITLE
Value Set Delta -- hitdev

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2630]
I can't select two value set to compare

**Comment by smartinez290** [comment]
It only lets me select one value set.

![image](https://user-images.githubusercontent.com/14842422/32298982-49e64652-bf2a-11e7-818f-4b0e46c95498.png)

**Comment by smartinez290** [comment]
Maybe because one is external? then when I click on compare I get the following screen. Notice that one of the value set is not in the list of value sets that I wanted to compare.

![image](https://user-images.githubusercontent.com/14842422/32299096-ae8c72de-bf2a-11e7-8d94-8af2ae34d0fd.png)

**Comment by Abdelghani90** [comment]
we compare with the current value Set, you don't need to select the second.
