### ISSUE TITLE
Deleting and re-adding V/s Issue - Mead

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2646]
From Mead: "In order to update my IG, I need to delete many value sets, and re-add them as flavors.

I am hitting a snag with PHVS_BirthAndFetalDeathFinancialClass.  It will not allow the deletion, and says it is referenced in my two PV1 flavors.   But, I see no reference there, and I did remove the reference from the FC_BR data type.  Is this a bug?

**Comment by Abdelghani90** [comment]
I fixed the IG. Please check with Mead and let me know.
