### ISSUE TITLE
Mead -- V/S binding broken

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2647]
I just tried to update the value set Birth Attendant titles by making it a flavor.

I deleted the prior reference, deleted the value set, and re-added the value set.

However, when I tried to then link it to the observation it belongs to – LOINC 73764-3 – I get the message that the value set binding is broken.  Can you check to see what this is?

**Comment by Abdelghani90** [comment]
Could you please send a screenshot. I don't understand the issue.

**Comment by afrold** [comment]
@smartinez290 please provide screenshot
