### ISSUE TITLE
Dave - can't delete clone IGs

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2650]
From Dave "I have made quite a few intermediate clones of the IG.  I tried to delete one that I no longer need, but it always fails to delete.  "

I tried to delete a clone ant it worked for me. I asked him for screen shot of the error. Here it is:

![clone](https://user-images.githubusercontent.com/14842422/32788289-d4999bea-c926-11e7-8c7f-e5c8ec521668.png)

**Comment by afrold** [comment]
@maxence-lefort  can you check this ?
