### ISSUE TITLE
Add regular expression to conformance statement editor

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#266]
Some existing conformance statements require a regular expression option in order to be replicated in IGAMT. For example, from the immunization IG:
![image](https://cloud.githubusercontent.com/assets/17408249/13819944/4c08ba82-eb69-11e5-8580-1c9134bbcc08.png)

Here, "equal to" may have a different meaning from "valued with"  in the validation tool for the testing suite. IGAMT options and the testing tools functionality need to be synced up

**Comment by Jungyubw** [comment]
merged to #290
