### ISSUE TITLE
Default ACK Message Conformance Profile throws Profile Errors while connecting to GVT.

### ISSUE THREAD

**Issue by pratikthakkar92** [haffonist/igamt#2663]
![image](https://user-images.githubusercontent.com/25619857/33031763-37a134d0-cded-11e7-8488-f8affd94e805.png)

I made no changes to the conformance profile of the ACK Message, when I try and connect it to GVT, it throws Profile Errors, leading me to believe that the default profile has issues.

**Comment by Jungyubw** [comment]
@pratikthakkar92 

Hello Pratik, Could you share your IG document with my account (Id: tcamt)?
I will investigate the issue.

Thanks.

**Comment by pratikthakkar92** [comment]
@Jungyubw I sent you my IG document. Please let me know if you need anything else. 

Thanks.

**Comment by Jungyubw** [comment]
@pratikthakkar92 

Thank you quick responding. The issue is event name of ACK message is missing.
In my understanding, the ACK event is dynamic (it depends on request message).

I will ask to my team member how to handle this.

Sorry for inconvenience

**Comment by pratikthakkar92** [comment]
@Jungyubw 

Thank you for identifying the issue. Glad I could help find an issue.

**Comment by robnist** [comment]
IGAMT can take the base message types and create an XML profile suitable for validation. However, there are some requirements. Complete MSH-9 is one. Some base message types  (e.g., ACK/QUERY/RESPONSE) are "templates" and are meant to be completed during the process of profiling.

A simple work-around is to add any event type  to the ACK profile. That should work. Let us know

**Comment by pratikthakkar92** [comment]
@robnist Thanks Rob, that actually worked and I was able to successfully send it over to GVT. I'll go ahead and close this ticket. Appreciate all the help.
