### ISSUE TITLE
Create conformance statement pattern for ISO compliant OIDs

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#267]
OID related conformance statements will likely be common enough to warrant a specific pattern in the conformance editor. For example:
![image](https://cloud.githubusercontent.com/assets/17408249/13820094/d5bf0916-eb69-11e5-8ec0-a466b5b2ca0f.png)

per Rob Snelick: probably need a "valued with" as an option and/or also add "ISO-compliant OID" as a pattern option

**Comment by Jungyubw** [comment]
Merged to #290
