### ISSUE TITLE
Deleting a data type

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#2671]
I created a data type flavor in a master data type library, made a few changes and then deleted it (right click in the navigation pane on the left side). The data type was deleted, but in the main editing pane, the data persisted (even with the Save button lit up). Saving doesn't do anything, but it's confusing that the data persists

![image](https://user-images.githubusercontent.com/17408249/33150398-decc1296-cf98-11e7-8f6f-81119c97c293.png)

When I try to navigate away to a different data type, I get the usual pop up.

![image](https://user-images.githubusercontent.com/17408249/33150461-2a32487c-cf99-11e7-9c20-19b47c1886bc.png)

Once a data type has been deleted, the data shouldn't persist.

**Comment by afrold** [comment]
@Abdelghani90 any update ?

**Comment by Abdelghani90** [comment]
@haffonist  this is fixed and deployed see pull request haffonist/igamt#2672
