### ISSUE TITLE
Code system changed to (random?) value after CSV import and removing empty code systems

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2676]
Step one: import CVS file where some codes do not have code system (this looks good)
![image](https://user-images.githubusercontent.com/13591511/33330225-4d9da634-d42c-11e7-8342-3f4874630b0a.png)

Step two: remove one of the "empty" code systems from the Source Code Systems on the top

Result: the empty code systems in the table are automatically changed to another value
![image](https://user-images.githubusercontent.com/13591511/33330372-b1d13c9c-d42c-11e7-817f-85957fd74af7.png)

I would leave the Code System as empty in the table (not randomly pick a value) with the "CodeSystem is required" message

**Comment by afrold** [comment]
@Jungyubw @Abdelghani90 please fix ASAP

**Comment by carolinerosin** [comment]
Tested - the empty code system is gone
