### ISSUE TITLE
Multiple code system (comma separated) added in value set table

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2677]
Step one : import CSV file
![image](https://user-images.githubusercontent.com/13591511/33330880-0c35b784-d42e-11e7-8b19-4a80b41c7f7d.png)

Step two : create a new code system ("99LAB")
![image](https://user-images.githubusercontent.com/13591511/33330895-1909f042-d42e-11e7-9a67-f675f8544dc8.png)

Step three: assign "99LAB" to values with no code system
![image](https://user-images.githubusercontent.com/13591511/33330931-37556aea-d42e-11e7-8a46-9fc0f27ce5d5.png)

Step four: remove the "empty" code system from Source Code System - now the code system of my two firt values changed automatically to wrong values
![image](https://user-images.githubusercontent.com/13591511/33331005-6af4f190-d42e-11e7-8e8f-b3af28a5c6b6.png)

Step five: remove the second "empty" code system, now the code systems for my two first values changed again and I get multiple code systems (comma separated) in my second value
![image](https://user-images.githubusercontent.com/13591511/33331087-a58ea4f4-d42e-11e7-9b93-9ff9a9def3c6.png)

[HL70291_USL-2.zip](https://github.com/haffonist/igamt/files/1510709/HL70291_USL-2.zip)

**Comment by afrold** [comment]
@Abdelghani90 @Jungyubw any update on this. This was reported a while back.

**Comment by carolinerosin** [comment]
tested and working
