### ISSUE TITLE
Pushing an IG to GVT is not sending an updated copy of the IG

### ISSUE THREAD

**Issue by pratikthakkar92** [haffonist/igamt#2678]
Changes made to certain fields in the RXA segment of the IG aren't carrying over to the GVT side.

**Comment by robnist** [comment]
Are you re-pushing to GVT? By looking at the question, you might be expecting changes made in IGAMT to be automatically reflected in GVT. This is not the case; you have to re-push to GVT (so you will end up this multiple copies in GVT--which you can delete, etc.). We are working on capabilities to just update--but those are available and the user has to make that decision.

If this doesn't answer your issue, then we will need to look at this further.

**Comment by pratikthakkar92** [comment]
Hey Rob, 

I am actually deleting the profile on GVT before pushing a new one. I even tried exporting from IGMAT and then importing it into GVT and it still reflected the old changes. I think there might be a bug in the RXA field/segment specifically.

**Comment by robnist** [comment]
OK, so other changes in other segments work? The issue is only for RXA (as far as you can tell)? Exactly what elements and constraints did you change in the RXA segment? I have a profile using the RXA segment and I can check.

**Comment by afrold** [comment]
Are you referencing the RXA segment flavor in the message before exporting to GVT ?

**Comment by pratikthakkar92** [comment]
I think Half found the issue, my RXA segment wasn't linked to my flavor and instead was pushing the default. I've fixed it and it seems to work fine now. I'll go ahead and close the ticket.
