### ISSUE TITLE
create conformance statement pattern for Set ID fields

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#268]
Set ID is common in many HL7 messages. Typically, where segments are allowed to repeat, Set IDs are numbered sequentially starting at 1 (if the segment is not allowed to repeat, the Set ID is usually constrained to the literal value "1".) It is worth having a pattern for this.
![image](https://cloud.githubusercontent.com/assets/17408249/13820250/7b7117a0-eb6a-11e5-8703-ef5bf70095e1.png)

Keep in mind that at the current time, the immunization IG allows OBX segments to either reset the set ID or not reset it between order groups. While resetting it is probably the "right" answer, both are allowed and must be accounted for here.

**Comment by Jungyubw** [comment]
merged to #290
