### ISSUE TITLE
create new high level activity for entering conformance statements

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#269]
Some conformance statements are self contained to a single field, but many either cross boundaries between fields (ie, the value of OBX-2 and -3 impact the value of OBX-5) or across segments (values in RXA impact values in OBX). There should be a new activity for entering conformance statements at the message, segment group or segment level.

**Comment by Jungyubw** [comment]
User can make complex cs/cp for 2 or more context. For example, we can create complex CS/CP for OBX-2 and OBX-3 and OBX-5.

Craig, if you think this is not clear, please reopen the ticket.
