### ISSUE TITLE
GVT RXA Segment Invalid Code System Error

### ISSUE THREAD

**Issue by pratikthakkar92** [haffonist/igamt#2694]
<img width="960" alt="screen shot 2017-12-05 at 9 28 22 am" src="https://user-images.githubusercontent.com/25619857/33612966-4620fab2-d9a1-11e7-8a05-ab55fc7becf6.png">

I am getting the following error whenever I try and validate a message with a RXA segment in it. Even though my Value Sets have CVX and MVX in them, it throws this error to me.

**Comment by robnist** [comment]
It depends on what value set you bound to those elements. For example, the base standard binds HL7 table 0292 to RXA-5, if you didn't change that then you should get this error. What do value set do you have bound to that element?

Here is how the immunization IG for ONC certification bound the value sets to those elements.

![image](https://user-images.githubusercontent.com/14874904/33613611-0f57d256-d9a3-11e7-8c91-b74ce12b0338.png)

**Comment by pratikthakkar92** [comment]
Hi Rob, 

Thank you so much for your help. I actually have bound the RXA segment to CVX and MVX segment as required. But specifically for 5.3 and 17.3 I have a different value set bound to it, CVX and MVX are part of the value set. That's where it is failing.

**Comment by robnist** [comment]
Please send a screen from the profile viewer with RXA-5 and RXA-17 expanded. Thanks.

**Comment by pratikthakkar92** [comment]
<img width="960" alt="screen shot 2017-12-05 at 10 34 12 am" src="https://user-images.githubusercontent.com/25619857/33615333-eaa7793e-d9a7-11e7-8f29-889786f44f35.png">
Expanded view for RXA-5

<img width="960" alt="screen shot 2017-12-05 at 10 34 23 am" src="https://user-images.githubusercontent.com/25619857/33615362-fa55c782-d9a7-11e7-941d-8d6f6b132267.png">

Expanded view for RXA - 17

**Comment by robnist** [comment]
OK. Please send a screenshot of the value sets (e.g., CVX-2-5-1). Thanks

**Comment by pratikthakkar92** [comment]
<img width="960" alt="screen shot 2017-12-05 at 10 40 47 am" src="https://user-images.githubusercontent.com/25619857/33615696-c9ff9bb6-d9a8-11e7-9b1a-ed65a6c906d7.png">

CVX-2.5.1

<img width="960" alt="screen shot 2017-12-05 at 10 40 53 am" src="https://user-images.githubusercontent.com/25619857/33615709-d134b880-d9a8-11e7-8120-1a11f726c372.png">

MVX-2.5.1

**Comment by robnist** [comment]
The validation is performing correctly. In your value set, you have the code system as HL70292 (as it is from the base standard-see image below). The CDC when creating the CVX value set changed the code system to CVX (from HL70292).  

Not sure if you have seen this Immunization tool, but it is a pretty good example of an Immunization IG.
https://hl7v2-iz-r1.5-testing.nist.gov   I'm pretty sure in IGAMT this is a shared IG so everyone can view it. It may be helpful in what you are trying to do.

![image](https://user-images.githubusercontent.com/14874904/33616736-c5d7568e-d9ab-11e7-8194-ad2cb5c6978f.png)

**Comment by pratikthakkar92** [comment]
Thanks for all the help, much appreciated. I will look into the links that you provided, I will go ahead and close this ticket.
