### ISSUE TITLE
Unable to save profile component

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2700]
I added a new item (OBX_LRI segment flavor) to a profile component (NG)
I modified the dynamic mapping (added more to the existing table)

The save button to save my profile component stays grey and I am not able to save. If I navigate to another element, I (obviously) lose what I just did

Note that I did the same thing in another profile component (GU) and it worked, I was able to save.

**Comment by smartinez290** [comment]
@carolinerosin this one is working from me every time. Weird, you showed it to me, maybe try a refresh on this one.

**Comment by carolinerosin** [comment]
I know it's weird because it worked for one profile component but not for the second one (so it's not systematic)

**Comment by afrold** [comment]
@Abdelghani90 ?

**Comment by carolinerosin** [comment]
tested and it looks like it is working properly
