### ISSUE TITLE
Adding data types from a user library

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2705]
I created two user libraries. 
. MyDTlib is empty
. TXT has some datatype I created

1. Right clicked on "MyDTlib" to  "Add User Datatype"
2. Selected "TST" lib, but no data types were displayed in the source column.
3, Did a search on a dt a I know is in TST lib, but the search did not respond

![image](https://user-images.githubusercontent.com/14842422/33786258-6ac45430-dc36-11e7-8dd4-e63a1d867dfd.png)

**Comment by Abdelghani90** [comment]
You can only see the published data types.
