### ISSUE TITLE
[Major blocking Issue] Can not add Segment to Group in Group

### ISSUE THREAD

**Issue by ncrouzier-nist** [haffonist/igamt#2711]
When I try to add a segment to a group (included in another group) in the message structure view, IGAMT fails to do so, the console shows a " ReferenceError: oldPath is not defined" error. 
Adding a Group works as expected. 
Adding a Segment to a Group not included in another group also works.

ref to #2357 

<img width="868" alt="screen shot 2017-12-14 at 10 12 32 am" src="https://user-images.githubusercontent.com/14352180/33999084-784dad06-e0b7-11e7-82bc-d58f26327132.png">

**Comment by afrold** [comment]
@Abdelghani90 was this fixed ?

**Comment by Abdelghani90** [comment]
this is fixed and deployed  pull request haffonist/igamt#2713
