### ISSUE TITLE
Can't select a code system when adding a New Value set

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2715]
1. Added a new Value Set" with codes
2. Entered a code system and save it (HL7396)
3. Entered a code and tried to select a code system -- none where listed. 

![image](https://user-images.githubusercontent.com/14842422/34383960-faf33300-eae6-11e7-94e6-c548f88917f8.png)

**Comment by afrold** [comment]
@Abdelghani90 ?

**Comment by Abdelghani90** [comment]
@smartinez290 Please QI
