### ISSUE TITLE
Datatypes are repeated in export 

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2716]
Per Dave: When I publish the guide to HTML, many of the datatypes are repeated and out of order, see below
![image](https://user-images.githubusercontent.com/14842422/34384012-704e1890-eae7-11e7-9ce1-001c67d59faf.png)
I checked Mead's IG and only one data type was repeated.

**Comment by afrold** [comment]
@maxence-lefort please fix ASAP. Anything to do with Abdel changes ?

**Comment by maxence-lefort** [comment]
@smartinez290 can you give me the IG document ID (share the link) please?

**Comment by smartinez290** [comment]
https://hl7v2.igamt.nist.gov/igamt/api/export/igDocument/5a4b791284aef4028b5983f9/html

**Comment by smartinez290** [comment]
@maxence-lefort I also shared the IG with you.

**Comment by maxence-lefort** [comment]
@smartinez290 Thanks, I'm looking into it.
