### ISSUE TITLE
Validaton is not evaluating co-constraints on OBX-6

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2719]
Checked the profile viewer in GVT the correct co-constraint was generated:
  | [CoConstraint-2-3]If  the value of OBX-3[1] (Observation Identifier) is '69440-6','then the  value of OBX-6[1].1[1] (Identifier) SHALL be one of codes in 0406_2-6' .

The following should generated a coConstraint error, but is not
OBX|1|ST|69440-6^FacilityIDNPIAssigned^LN|||xxxx|||||F

**Comment by HossamT** [comment]
I need to look at the XML resource, the text can be correct and the assertion still wrong.

**Comment by smartinez290** [comment]
[TestingIG--Copy--Copy-5a09c6d784ae34fd623e9b5c_20171228_142529.zip](https://github.com/haffonist/igamt/files/1591945/TestingIG--Copy--Copy-5a09c6d784ae34fd623e9b5c_20171228_142529.zip)

**Comment by HossamT** [comment]
@Jungyubw Constraint ID="OBX_TXT-CoConstraint-2-3" uses wrong path for OBX-6.1
Used in presence : 6[1].1[1].1[1]
Used in value set constraint : 6[1].1[1] - location : 1

The correct one would be : 
In presence : 6[1].1[1]
In value set constraint : 6[1] - location : 1

**Comment by afrold** [comment]
@Jungyubw  any idea ?

**Comment by Jungyubw** [comment]
I will look at it.

2018. 1. 4. 오전 10:28에 "Harold Affo" <notifications@github.com>님이 작성:

**Comment by Jungyubw** [comment]
@sandra,  what IG document are you using?

2018. 1. 4. 오전 10:28에 "Jungyub Woo" <jungyub.woo@nist.gov>님이 작성:

**Comment by Jungyubw** [comment]
Done
