### ISSUE TITLE
Create a co-constraint option for the conformance statement editor

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#272]
Groups of conformance statements can be defined in a tabular format. For example, there are multiple conformance statements related to the value set to use in OBX-5 depending on the values of OBX-2 and OBX-3. An option to build a conformance statement co-constraints table would be an efficient way to define these requirements.

![image](https://cloud.githubusercontent.com/assets/17408249/13820588/0a7b7106-eb6c-11e5-8fd7-466f55bcdb01.png)

**Comment by Jungyubw** [comment]
Need QA

**Comment by haffonist** [comment]
First version implemented. 
Will update UX for better experience. A new issue will be created.
