### ISSUE TITLE
Usage Notes

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2720]
Per Dave:  Another issue is that there are several places in the HTML export where there is a "Usage note:" but there is no text.  In fact, it is this way throughout the guide, blank usage notes.

![image](https://user-images.githubusercontent.com/14842422/34484189-1dbcc2d0-ef91-11e7-86e3-3a1ab85d008b.png)

**Comment by afrold** [comment]
@maxence-lefort please fix
