### ISSUE TITLE
Missing value set value in HL7 datatypes

### ISSUE THREAD

**Issue by ncrouzier-nist** [haffonist/igamt#2721]
When importing some datatypes (2.8 , 2.8.2) it seems some value set are not defined (see example with HD) 
As these are HL7 elements I can not define and this also makes the export fail.

<img width="1397" alt="screen shot 2018-01-02 at 12 56 22 pm" src="https://user-images.githubusercontent.com/14352180/34494061-a31022a8-efbc-11e7-8125-7c81c106675f.png">

**Comment by ncrouzier-nist** [comment]
Update: It seems that if I manually add the missing table it fixes the problem.
Maybe just an issue when creating the Datatype...

**Comment by afrold** [comment]
@Abdelghani90 please check to see why this is happening

**Comment by Abdelghani90** [comment]
@ncrouzier-nist  can you share your IG with me. I cannot produce it in the IGs I have.
to look for me please type my username : wakili

**Comment by ncrouzier-nist** [comment]
Bump.
This happened again at the Connectathon for MOP datatype (missing 148 table)
