### ISSUE TITLE
data type user library -- empty after publishing

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2722]
I am re-testing this feature, but now it is not working as expected. I created the data type library and published it. Then I tried to use it in my IG, but is empty:
![image](https://user-images.githubusercontent.com/14842422/34532496-4fd332ec-f084-11e7-86f8-534d7ef13a71.png)
Here is the library, I did not added any constraints, just published as it. Could it be that is missing the predicates? but, no errors were generated and the tool allowed me to created like that.

![image](https://user-images.githubusercontent.com/14842422/34532575-95911a56-f084-11e7-9508-c700ffd91752.png)

**Comment by Abdelghani90** [comment]
You will see only the datatypes with a version >= than the version of the IG

**Comment by smartinez290** [comment]
I see!! Thanks!!
