### ISSUE TITLE
Adding field in the midle of a segment

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2725]
I was able to add a field to the middle of a segment. I was discussing this with @carolinerosin  and we are wondering If IGAMT is supposed to let user add field in the middle of segments ? It seems wrong. @robnist we think this needs to be discussed. 

Per Caroline: "I can see the point for adding fields at the end of a segment, but not messing with an existing segment structure."

It is also messing up the verify, by adding the fields to the middle. 

I just added another field and now is doubling up the fields. Take a look.

![image](https://user-images.githubusercontent.com/14842422/34574341-1dd0f1be-f145-11e7-9e6b-90197e4dbb9e.png)

**Comment by Abdelghani90** [comment]
Please provide with the IG and the segment you are using.

**Comment by smartinez290** [comment]
@Abdelghani90 I will have to show you this one live.  I am just using a testing IG, that I have change many times.

**Comment by afrold** [comment]
As discussed the behaviour is normal. A new issue will be created to handle the creation of new field positioning.
