### ISSUE TITLE
create a conformance statement editor pattern for MSH-21

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#273]
MSH-21 is a repeating field containing a list of 1 or more profiles the message conforms to. Typically, a given profile will require a particular value to be in that list, but other values may be allowed too. This requires a very specific format for the conformance statement that can't currently be achieved with the tool.

![image](https://cloud.githubusercontent.com/assets/17408249/13820651/4dfeab32-eb6c-11e5-937f-1a4ffd358532.png)

**Comment by Jungyubw** [comment]
Merged to #290
