### ISSUE TITLE
HTML export of my LRI R2 IG fails

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2732]
I try to export > As HTML > IG Style

and I get a page with the following error : 

{"Errors stack":[],"Location":"[IG Document] 58349b5184ae8eb773924552"}

Export as xml seems to work (I did not check the contents yet, but at least I get a zip file)

**Comment by afrold** [comment]
@maxence-lefort ??

**Comment by maxence-lefort** [comment]
@carolinerosin I think we fixed this, correct?

**Comment by carolinerosin** [comment]
yep just tested, it works
