### ISSUE TITLE
Binding Location in Value set cross reference is sometimes incorrect

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2735]
This is not consistent, sometimes I get the right value, sometimes I don't
Here's an example. Binding Location should be 4 (not 3) because the value set is assigned to EI_GU.4
![image](https://user-images.githubusercontent.com/13591511/34615775-070d4c24-f204-11e7-98ed-cc701e281df3.png)

![image](https://user-images.githubusercontent.com/13591511/34615808-1e9200ba-f204-11e7-9984-394f053d37f7.png)

**Comment by afrold** [comment]
@Jungyubw  ??

**Comment by Jungyubw** [comment]
@Abdelghani90 Do you know this issue? I cannot produce it at my side.

**Comment by Abdelghani90** [comment]
I can't produce. @carolinerosin  what is the IG name

**Comment by carolinerosin** [comment]
LRI R2

**Comment by carolinerosin** [comment]
It looks like the value is not always "refreshed" and so I see the value from the previous value set I was looking at. If you want to reproduce, you need to go back and forth between two value sets.

**Comment by Abdelghani90** [comment]
Thanks I fixed the issue. it will be deployed ASAP.

**Comment by carolinerosin** [comment]
tested and looks ok now
