### ISSUE TITLE
New conditional group -- Can't add a predicate

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2742]
I can't add a predicate to a conditional group I added.

**Comment by Abdelghani90** [comment]
I checked and it is working for me. please attach an image.

**Comment by smartinez290** [comment]
I just tried  to click on "need predicate" noting happened. I refreshed and tried again, the same results.

![image](https://user-images.githubusercontent.com/14842422/34629022-96341ce0-f234-11e7-81f7-21a8139f15a7.png)

**Comment by Abdelghani90** [comment]
still cannot produce it. which IG you are using and which message ?

**Comment by smartinez290** [comment]
If the group is already created and you change the usage to conditional and try to add the predicate, it works. 
I am not able to add the predicate immediately after I creating the group indicating that is conditional. Just try to do it in any conformance profile, any message.
