### ISSUE TITLE
automatically assign IDs to individual constraints when using the complex conformance statement editor

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#275]
when building up complex conformance statements, a user must first enter individual constraints which are then linked together to make the Complex Constraint. While building the individual constraints, the user must enter an ID but these individual IDs are not part of the final constraint, they are simply used to build up the complex constraint. If users forget to give an id (or assigns a bad id), it makes it hard to build up the complex constraint. Given that the IDs are only used in the context of the editor, these IDs can be assigned by the tool directly (as is done in the predicate editor.

**Comment by Jungyubw** [comment]
Merged to #291
