### ISSUE TITLE
Multiple Value Sets Logic

### ISSUE THREAD

**Issue by Jungyubw** [haffonist/igamt#2752]
1. (Pre) need to find why we did exclude multiple valuesets for coded elements DT.
2. CE, CF, CWE, CNE, CSU could have multiple Value Sets
2.1 ID, IS, HD, ST, NM should have a single value set
3. For each element Multiple Value Sets bindings should have a single binding location.
4. XML should be :

bindingIdentifier='A:B' bindingLocation="1:4"
bindingIdentifier='A:B' bindingLocation="1"
bindingIdentifier='A:B' bindingLocation="4"

@carolinerosin @robnist, please confirm this requirements for multiple valuesets

**Comment by carolinerosin** [comment]
yes that is right.

**Comment by robnist** [comment]
Yes, but I'm not totally convinced on 2.1. I've times for an ID or IS where they authors wanted to specify one or the other (value set). I think this is bad thing to do but I've seen. So I'd rather not allow it.
So what you have is correct but don't be surprised if we have a user in the future asking to allow it for those other data types.

**Comment by afrold** [comment]
@Jungyubw ??
