### ISSUE TITLE
use consistent format when referring to segments, fields, components and subcomponents

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#276]
HL7 uses a standard format when referencing message or data type elements. Make sure all parts of the tool use this format. The conformance editor may not do this in all cases

For data types, the format is:
<data type>.<location>
for example CWE.3

For message locations, the format is:
<segment>-<field>.<component>.<subcomponent>
for example PID-3.4.1

**Comment by Jungyubw** [comment]
fixed
