### ISSUE TITLE
allow conformance statement ID refactor

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#277]
Include an option to refactor conformance IDs throughout the entire document (assuming the tools is upgraded to automatically assign a unique conformance ID at the time of statement creation).

We need to think about when it's acceptable to do this. Should it only be allowed before the first version of the document is published? For example, consider an existing document with the following conformance statements:
IZ-1 = requirement 1
IZ-2 = requirement 2
IZ-3 = requirement 3

During an update to the already published document, requirement 1 is removed but a new requirement (requirement 4) is added. Which of the following is better?
IZ-2 = requirement 2
IZ-3 = requirement 3
IZ-4 = requirement 4
or 
IZ-1 = requirement 2
IZ-2 = requirement 3
IZ-3 = requirement 4

Or instead, what if requirement 1 is tweaked (it addresses the same issue, but makes a small but significant change), which is better?
IZ-1 = requirement 1a
IZ-2 = requirement 2
IZ-3 = requirement 3
or 
IZ-4 = requirement 1a
IZ-2 = requirement 2
IZ-3 = requirement 3

**Comment by Jungyubw** [comment]
Merged to #291
