### ISSUE TITLE
Can't export IG due to special  characters in PhiVads 

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2771]
![image](https://user-images.githubusercontent.com/14842422/35691364-46cadd02-0746-11e8-9cb6-3ce7f590aa59.png)

This particular case the special character was in the pre-text
@Jungyubw is there a way to remove special characters when loading the value sets?

**Comment by Jungyubw** [comment]
Sandra, I will fix it on Monday.

**Comment by afrold** [comment]
@Jungyubw  We should remove those characters before importing a value set into IGAMT
Fix existing  value set by removing them 
remove from new before importing into db

**Comment by Jungyubw** [comment]
Fixed
