### ISSUE TITLE
Fix Add/Removing segment/group in message

### ISSUE THREAD

**Issue by afrold** [haffonist/igamt#2779]
Remove adding group to a message 
Enable adding segment everywhere in the message (Already supported) 
Do not handle the existing predicates when the segment is removed.  Let the user clean up their mess

Ignore verification for new segment added within the message definition.  
Make the new segment colored (green) and add an ? icon where hovered, show message:

Because this is an added segment, it will not be verified.

**Comment by smartinez290** [comment]
Is working!!!
