### ISSUE TITLE
unreferenced segment, datatype , value sets should not be exported in XML

### ISSUE THREAD

**Issue by afrold** [haffonist/igamt#2781]
@Jungyubw  they should not be exported. Any reason why they are being exported ?

**Comment by afrold** [comment]
Resolution:

Because of the dynamic mapping we are including all data types from table 0125 
Currently the tool is also exporting all segments. This will be fixed to only export relevant segment linked to the conformance profile selected.

**Comment by Jungyubw** [comment]
fixed for only included referenced segment.
