### ISSUE TITLE
Datatype Substitution

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2853]
Per Rob: At one point I think we came up with mapping table to state which data type substitution was allowable, but for the case of ID, I can’t select CWE, but I can select CNE. 
Something is wrong, here. 

We need to review the data type substitution table on Monday.

![image](https://user-images.githubusercontent.com/14842422/37852709-008919e4-2eba-11e8-94c6-a436b25347eb.png)

**Comment by Abdelghani90** [comment]
You cannot select CWE inside CWE. This is the only one we prevent.

**Comment by carolinerosin** [comment]
Another issue to think about is that this could potentially create 5 levels of elements - let's discuss that during the next IGAMT meeting
