### ISSUE TITLE
 5-level nesting

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2891]
Per Rob: It is urgent that the 5-level nesting is addressed immediately.

Custom   Verifications | Target | Error Type | Location | Error Message
-- | -- | -- | -- | --
DATATYPE | FiveLevelComponent | TS_2-5-1 | XPN_M_2-5-1.10.1   Datatype is TS_2-5-1, but it is not primitive.
DATATYPE | FiveLevelComponent | TS_2-5-1 | XPN_M_2-5-1.10.2   Datatype is TS_2-5-1, but it is not primitive.
DATATYPE | FiveLevelComponent | CE_2-5-1 | TQ_2-5-1.1.2   Datatype is CE_2-5-1, but it is not primitive.
DATATYPE | FiveLevelComponent | TS_2-5-1 | XCN_IZ_2-5-1.17.1   Datatype is TS_2-5-1, but it is not primitive.
DATATYPE | FiveLevelComponent | TS_2-5-1 | XCN_IZ_2-5-1.17.2   Datatype is TS_2-5-1, but it is not primitive.

**Comment by haffo** [comment]
Done.
