### ISSUE TITLE
Can't add entry to User's Guide

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2942]
Moving sections in the User's Guide was implemented and it is working, but now I can't add entries in the User's Guide. I click the + sign, when I tried to enter a title nothing happens:

![image](https://user-images.githubusercontent.com/14842422/45832024-cc335080-bcce-11e8-94bd-8beac6b06d58.png)

**Comment by haffo** [comment]
@Abdelghani90 please fix asap. thanks

**Comment by Abdelghani90** [comment]
the title is required. you must have a title to be able to save

**Comment by haffo** [comment]
I can't even type the title !
