### ISSUE TITLE
Can't build CS: Undefined value

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2943]
Issue reported by user:               

 I was trying to do something simpler, I was trying to make a Conformance Statement for OBX-4 that states that the value of OBX-4 must be greater than Zero. For some reason when I add a conformance statement that should say, “The value of OBX-4 SHALL be greater than 0” it is replacing 0 with the word undefined? Below are screen shots of what I am trying.

1)	Created a Custom Flavor of OBX-Observation/Result
 
2)	Clicked on the Conformance Statements Tab

 3) Added the following conformance statement
 

4)When I hit Add this is what displays, how is 0 being equated to Undefined?

**Comment by Jungyubw** [comment]
Fixed!
