### ISSUE TITLE
adding a new value while showing search results

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#301]
Users may make a bit of a mess if they click the "add value" button in the value set editor after they have done a value search. In this case, a space for a new value is added, but because there is no data for the new value (no code, no text) it doesn't show up in the search. This makes it appear that the "add value" didn't do anything (which will probably cause the user to furiously click it a few more times). Once the search is cleared, the empty "new value" slots appear. If the user did furiously click the add button, more slots will be available then they need. It's easy to delete them, but it's not ideal.

A couple of possible solutions:
-display a warning that values cannot be added while a search is in force
-include blank values in the search results

Clicking "add value" in this state:
![image](https://cloud.githubusercontent.com/assets/17408249/14025202/e97eb148-f1ba-11e5-8b5a-103061f5b822.png)

results in this (no apparent change):
![image](https://cloud.githubusercontent.com/assets/17408249/14025220/ff51e5c6-f1ba-11e5-94ef-a7670b4decc7.png)

clicking "add value" again (because it apparently didn't work the first time) and then clearing the search term results in this:
![image](https://cloud.githubusercontent.com/assets/17408249/14025247/2232e3e2-f1bb-11e5-997d-66270202d8b9.png)

**Comment by Jungyubw** [comment]
I just changed this logic. When the user adds a new value, the search box is reset.
