### ISSUE TITLE
PDF Export could use some white space

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#311]
When exporting a document, the IGAMT tool, Word document and HTML document all have white space between paragraphs but the PDF document does not. This helps readability and it would be nice if the PDF also included some white space between paragraphs. See red arrows below:
![image](https://cloud.githubusercontent.com/assets/17408249/14249605/2b601b8c-fa40-11e5-90bd-495c43e7df2a.png)

**Comment by haffonist** [comment]
We will not support pdf per Rob's instruction.
