### ISSUE TITLE
Too much white space after a section header

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#313]
The current exports seem to include a blank line after each section header. This results in a lot of white space in the document. Working in the Word document, it is possible to remove that extra line. When this is done, plenty of white space is left. I think it would be best if this blank line were not included in the exported document.

![image](https://cloud.githubusercontent.com/assets/17408249/14249981/066938ac-fa42-11e5-97d7-163a666fe854.png)

**Comment by haffonist** [comment]
Word is fixed

**Comment by haffonist** [comment]
I guess this is a related to the template being used. The current template we are using has those white spaces. 
@robnist I believe Bob Yencha plan to send us a new template to use. correct ? 
We might need to review that template during our wednesday meeting before we integrate into the tool.
