### ISSUE TITLE
Word doesn't respect the "quote" format for tables

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#319]
When a table is embedded in text that is formatted with the "Quote" format in the text editor, the formatting (the purple color of the text) is not applied to the table.

Also, if Paragraph Format (Heading 4) is applied to the table title, then Word creates a new sub-section for the table. This seems problematic (see previous comment #316 for a previous noting of this)

Also note that the alternate line shading applied in IGAMT is not present in the Word export.

![image](https://cloud.githubusercontent.com/assets/17408249/14251544/27f04a9a-fa49-11e5-979a-0412b3e7b13c.png)

**Comment by haffonist** [comment]
@Abdelghani90 please have a look at this. i think it is fixed by Olivier but not sure.

**Comment by haffonist** [comment]
This already fixed.
