### ISSUE TITLE
Section numbering is off

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#321]
The numbering of Use Case section is off in the HTML and PDF exports. Rather than being section 2 (as they should be and are in the Word export), they are section three. I played with the Use Case section (adding and deleting them). Keep in mind that during a Wednesday morning call, we added a Use Case section and then saw it disappear when we logged out and logged back in. Note that in the HTML table of contents, there are two section 3s (blue and black arrows).

![image](https://cloud.githubusercontent.com/assets/17408249/14252124/8ea1d806-fa4b-11e5-8399-7c0f486ccc21.png)

**Comment by haffonist** [comment]
This is not completed. So I am moving back to Sprint backlog pipeline.

**Comment by haffonist** [comment]
HTML + Word is fixed

**Comment by haffonist** [comment]
fixed
