### ISSUE TITLE
Bind Multitple Value Sets

### ISSUE THREAD

**Issue by haffonist** [haffonist/igamt#342]
[From Craig]

Rob, Sheryl,
 
As we discussed yesterday, here is the description of the issue with sending both NDC and CVX codes for new administrations. We expect that at least a few IIS will need to add this requirement on top of the national IG and certification regulations. The IGAMT improvements you are working on will need to document something like this. Please have a look and let us know if you need further clarification.
 
Thanks
Craig
 
The IIS must be able to accept NDC codes for new administration messages. It is the spirit of the regulation that all IIS will be able to accept NDC codes alone (and drive all business requirements based on the NDC code alone) and all IIS are highly encouraged to evolve their systems to meet this requirement. However, while IIS must be able to accept an NDC code without logging an error, local guides may further constrain the usage of RXA-5 to also require the cognate CVX code also be sent. RXA-5 uses a data type of CE which allows for sending of both an ID (using one coding system) and an alternate ID (using a different coding system) as long as both codes are close synonyms. In this case, the NDC code should be sent in one triplet while the CVX code should be sent in the other. No preference for order should be given by the IIS. Because NDC codes are only expected to be used for new administrations, the need to send both NDC and CVX codes should be limited to cases where RXA-9 contains the code 00 from the Immunization Information Source (NIP001) value set. In all other cases, the CVX code alone should be sufficient. Two different flavors of the CE data type may need to be defined in order to accommodate the need for the interoperating systems to use both triplets in RXA-5. The specific data type flavor to use would be drive off of the Immunization Information Source code found in RXA-9.

**Comment by haffonist** [comment]
This needs discussion with Rob. Should include Hossam, Woo and Harold

**Comment by Jungyubw** [comment]
I think, now we support this.
