### ISSUE TITLE
value set list is unsorted in two places

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#346]
In both the Table of Contents (red box below) and the "select value set for a data element" tool (blue box below), the value sets seem to be sorted in no apparent order which makes it difficult to find the value set you want.

![image](https://cloud.githubusercontent.com/assets/17408249/14824486/ce64ba10-0b9b-11e6-8652-cd2e1aa77a54.png)

**Comment by Jungyubw** [comment]
Fixed, need QA

**Comment by Jungyubw** [comment]
Craig,

the order of ValueSets on TOC is fixed.

However, value sets of binding dialog was correct. You can sort them to click 'small triangle' at the header.
