### ISSUE TITLE
value set value delete is behaving erratically

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#349]
I'm seeing odd behavior when I delete values from a value set. I started out by copying value set 0203. I then set about deleting some extraneous values that weren't relevant to the context i was going to use the value set in.

(1) the purple boxes highlight some key value to keep an eye on. I then deleted "Health Care Number"
(2) that resulted in the blue boxes. The top value of "Patient Internal Identifier" remained at the top of the list, and "License Number" and "Local Registry ID" moved up. I then deleted "License Number" and that's when things got odd
(3) as shown by the green boxes, not only was "License Number" removed and "Local Registry ID" moved up, but "Patient internal identifier" also seemed to have disappeared, to be replaced by "Person number"

If you continue the deleting values, you see the pattern that every other time, the top value in the list if replaced by a new value.

![image](https://cloud.githubusercontent.com/assets/17408249/14827071/4181d096-0ba6-11e6-9cde-82a8faadd2a9.png)

**Comment by Jungyubw** [comment]
Fixed
