### ISSUE TITLE
Inconsistent format for referring to data type components

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#350]
When referring to data type components the data type and the component number should be separated by a period (.) not a dash. That is being done in most places (see red boxes below) but one place in the predicate editor is still using a dash (green box).

![image](https://cloud.githubusercontent.com/assets/17408249/14828348/43b893da-0bac-11e6-8d98-16f2533b721d.png)

**Comment by Jungyubw** [comment]
Fixed.
