### ISSUE TITLE
Can't edit edit a code system.

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#352]
When a new code is added,  I can’t edit it to add a different code system.
See attachment.
![codesys](https://cloud.githubusercontent.com/assets/14842422/14860893/d9a10c5c-0c78-11e6-8c7c-33edc7e07654.png)

**Comment by Jungyubw** [comment]
CodeSystem will be automatically updated by user typing

**Comment by Jungyubw** [comment]
fixed
