### ISSUE TITLE
The IGAMT tool new release is not displaying the components of the segment

### ISSUE THREAD

**Issue by ctdph** [haffonist/igamt#359]
The IGAMT tool new release is not displaying the components of the segment or the values of the datasets. steps to reproduce the error:
- Click on any segment
- System only displays Name, Extension, Description, Comment, Definition Pre-Text and Definition Post text.

See attached screen shot. 
![igamt_segment](https://cloud.githubusercontent.com/assets/17731064/15551167/be3dbfa8-2282-11e6-8ba1-1724f2e5452f.png)

**Comment by smartinez290** [comment]
Click on the “Segment Definition” tab, it is not obvious, the developers are going to fix this.

Sandra

**Comment by ctdph** [comment]
Hi,

I saw.

Thank you so much.


Alejandra Martinez
Information Technology Analyst 1
Immunization Program
State of Connecticut, DPH
410 Capitol Avenue Hartford CT 06134
Email: alejandra.martinez@ct.gov<mailto:alejandra.martinez@ct.gov>

[http://www.ct.gov/insidedph/lib/insidedph/communications/DPH-Color.gif]
