### ISSUE TITLE
lack of notification when data is missing

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#362]
If required fields (highlighted in red) are required before a section can be saved, then it would be nice to have a notification to that effect. the button changes color when saving is possible but it's pretty subtle (see image below) and when you click on the "greyed out" save button, it does nothing, but there's clear indication that nothing is happening (but it doesn't really do a whole lot that is obvious to a user, when you are allowed to save)

![image](https://cloud.githubusercontent.com/assets/17408249/15587869/e6591d92-2350-11e6-9d67-9f15f5ebbf4c.png)

**Comment by haffonist** [comment]
fixed
