### ISSUE TITLE
Link editor cuts off

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#370]
When trying to insert a link when the text editor is empty, the last of the link editor is cut off. You can access it by tabbing through the fields (URL -> Text -> Open in new window) but you can't go straight to the check box. 

![image](https://cloud.githubusercontent.com/assets/17408249/15682571/f42639a6-2723-11e6-88df-26733f13703e.png)

This is not a problem when there is significant text already in the box
![image](https://cloud.githubusercontent.com/assets/17408249/15682638/442e3ade-2724-11e6-9888-d6598645037d.png)

**Comment by haffonist** [comment]
I believe this is fixed.
