### ISSUE TITLE
getting mixed messages...

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#371]
When adding text to the Conformance Profile MetaData and then hitting save, you get a message of "Message Saved" but the red header suggests there was an error. Did it save or not? It's hard to tell.

![image](https://cloud.githubusercontent.com/assets/17408249/15683104/5d3b4ace-2726-11e6-8659-ae74df72509d.png)

Then, if you try to leave, you get the usual conformation box:
![image](https://cloud.githubusercontent.com/assets/17408249/15683171/9e32a9aa-2726-11e6-950e-a0b8179776f9.png)

In general, if you move to a profile section and then try to leave (without making any changes). you sill get this pop up asking about discarding changes.
![image](https://cloud.githubusercontent.com/assets/17408249/15683216/d6db51e4-2726-11e6-9105-235085f09ecd.png)

**Comment by haffonist** [comment]
fixed
