### ISSUE TITLE
Data Type Purpose and Use doesn't seem to save

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#372]
I copied a data type and entered a Purpose and Use, Comment and Definition Text. When I saved the record it seemed to save (see green banner below). But when I navigate away from the data type and come back, only the Comment and Definition Text are there. The Purpose and Use doesn't seem to be saved.

![image](https://cloud.githubusercontent.com/assets/17408249/15683391/b97bb1ec-2727-11e6-85a0-3a69851adf75.png)

**Comment by haffonist** [comment]
fixed
