### ISSUE TITLE
duplicate Description in value sets

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#374]
The value set activity shows the description twice. Interestingly, if you put the cursor in one of the boxes and edit the text, it immediately shows up in the other box. Is there an intention that these should be different or is this a duplication?

![image](https://cloud.githubusercontent.com/assets/17408249/15683651/06bcf208-2729-11e6-8eff-3eadf88db4dc.png)

**Comment by haffonist** [comment]
fixed
