### ISSUE TITLE
Value set binding not working

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#399]

**Comment by smartinez290** [comment]
When is this issue going to be resolved?

**Comment by haffonist** [comment]
Isn't it fixed ? Have you saved ? 
Please provide screenshot ?

**Comment by smartinez290** [comment]
[cid:image001.png@01D1E973.F9C3E1D0]

**Comment by smartinez290** [comment]
![binding](https://cloud.githubusercontent.com/assets/14842422/17248310/ab191b94-5567-11e6-91ab-d89f61d88ec1.png)

**Comment by haffonist** [comment]
You need to type the name of the value set. You will get a list as you are typing along and select the match from the list.
