### ISSUE TITLE
incorrect segment group name??

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#404]
Is the segment group name below correct? It seems confusing that it is "PATIENT" when it contains patient visit related segments. Is this what HL7 calls it?

![image](https://cloud.githubusercontent.com/assets/17408249/16810057/28b57444-48e8-11e6-9d26-89656ede4fe1.png)

**Comment by haffonist** [comment]
Yes. It comes straight for the HL7 base.

**Comment by csnewman88** [comment]
It looks like your source files may have an error. Looking at the 2.8.2 documentation, it looks like it should be PATIENT_VISIT

![image](https://cloud.githubusercontent.com/assets/17408249/17305014/0e1bc2d6-57ee-11e6-954b-3acccf37c844.png)

**Comment by haffo** [comment]
@gcr-nist any idea ?
