### ISSUE TITLE
Associate OBX-2 to value set

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#420]
I am trying to associate a new value set (clone of HL70125) to OBX-2. When I click +, I get the search window. I enter the string of the value set name into search box and get a pop-up stating: Are you sure you want to change the usage from O to X....
Clicking yes does not change cardinality of field and does not link the field to desired value set.

**Comment by haffonist** [comment]
Hey Rob, can you provide some screenshots ? It will help a lot. 
Thanks

**Comment by robsavage** [comment]
could not reproduce.
