### ISSUE TITLE
problem adding segment

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#426]
I added new segment, selecting an existing segment. When I tried to set the position, I clicked the arrow heads on the right. the drop down was displayed, but I could not select from it. When I cancelled and retried, I just entered the number and it was accepted.

**Comment by haffonist** [comment]
What happened was once you selected the segment it was refreshing the tree while you were trying to select the position. We are fixing this right now.

**Comment by haffonist** [comment]
@IsmailMellouli, once a user select a segment or data type, or table flavor from the definition tree table, we need to lock the screen while reloading the tree by simply display the ui-block widget ("Loading..."). 
Please add this.

**Comment by haffonist** [comment]
@IsmailMellouli any update ?

**Comment by haffonist** [comment]
This is fixed.
