### ISSUE TITLE
Implement conditional constraints

### ISSUE THREAD

**Issue by Jungyubw** [haffonist/igamt#43]

**Comment by Jungyubw** [comment]
grunt build failed

...
{ message: 'Unexpected token: punc ({)',
  filename: '../../../../../igamt-lite-client/.tmp/concat/scripts/scripts.js',
  line: 6551,
  col: 45,
  pos: 259545,
  stack: 'Error\n    at new JS_Parse_Error (/Users/jungyubw/Documents/Works/Projects/igamt-lite/igamt-lite-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:196:18)\n    at js_error (/Users/jungyubw/Documents/Works/Projects/igamt-lite/igamt-lite-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:204:11)\n    at croak (/Users/jungyubw/Documents/Works/Projects/igamt-lite/igamt-lite-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:684:41)\n    at token_error (/Users/jungyubw/Documents/Works/Projects/igamt-lite/igamt-lite-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:688:9)\n    at unexpected (/Users/jungyubw/Documents/Works/Projects/igamt-lite/igamt-lite-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:694:9)\n    at semicolon (/Users/jungyubw/Documents/Works/Projects/igamt-lite/igamt-lite-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:714:43)\n    at simple_statement (/Users/jungyubw/Documents/Works/Projects/igamt-lite/igamt-lite-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:894:73)\n    at /Users/jungyubw/Documents/Works/Projects/igamt-lite/igamt-lite-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:767:19\n    at /Users/jungyubw/Documents/Works/Projects/igamt-lite/igamt-lite-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:727:24\n    at block_ (/Users/jungyubw/Documents/Works/Projects/igamt-lite/igamt-lite-client/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:1007:20)' }
>> Uglifying source .tmp/concat/scripts/scripts.js failed.
Warning: Uglification failed.
Unexpected token: punc ({). 
Line 6551 in .tmp/concat/scripts/scripts.js
 Used --force, continuing.
Warning: Cannot read property 'min' of undefined Used --force, continuing.

**Comment by haffonist** [comment]
Have you tried to rebuild bower components ?

**Comment by Jungyubw** [comment]
I have rebuild npm and bower but I met same error before for grunt buld:
It looks a parsing error for script.js


....
Running "ngAnnotate:dist" (ngAnnotate) task
Generating ".tmp/concat/scripts/scripts.js" from: ".tmp/concat/scripts/scripts.js"...ERROR
>> error: couldn't process source due to parse error
>> Unexpected token (6551:45)
Warning: Task "ngAnnotate:dist" failed. Use --force to continue.

Aborted due to warnings.

**Comment by haffonist** [comment]
Have you tried grunt serve ?

Harold

**Comment by Jungyubw** [comment]
It seems no error for app,js during grunt serve.
But build is not working.

**Comment by Jungyubw** [comment]
Sorry I found issue on my code. I will modify it and try it.

**Comment by Jungyubw** [comment]
I modified my parsing error in the Java script.  Build is okay.
But when I connect to home.
Tool shows this error and cannot log in:

Do you have any idea?
...

api/profiles/config
scripts...d69f.js (line 1)
TypeError: href is null
e/<()plugins...ae24.js (line 5)
db/this.$get</<()plugins...ae24.js (line 5)
i()plugins...ae24.js (line 5)
j/<()plugins...ae24.js (line 5)
Vb/this.$get</n.prototype.$eval()plugins...ae24.js (line 6)
Vb/this.$get</n.prototype.$digest()plugins...ae24.js (line 6)
Vb/this.$get</n.prototype.$apply()plugins...ae24.js (line 6)
_/h/<()plugins...ae24.js (line 4)
e()plugins...ae24.js (line 4)
_/h()plugins...ae24.js (line 4)
_()plugins...ae24.js (line 4)
$()plugins...ae24.js (line 4)
plugins.a8fcae24.js()plugins...ae24.js (line 8)
_.Callbacks/k()plugins...ae24.js (line 2)
_.Callbacks/l.fireWith()plugins...ae24.js (line 2)
.ready()plugins...ae24.js (line 2)
g()

**Comment by haffonist** [comment]
Great !
I have encountered this error on the iztool but it is not critical.
