### ISSUE TITLE
auto save causes jump back to beginning of text

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#431]
The autosave function jumps the cursor back to beginning of section when typing. This causes the typing to continue in the wrong spot.  Mildly annoying.

**Comment by haffonist** [comment]
@robsavage can you be more specific ? is this the section editor ? any screenshot will be helpful. 

Thanks

**Comment by robsavage** [comment]
It is interesting, it only occurs in some section editor. I will work to find which ones.
Thanks
Rob
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by robsavage** [comment]
It does not appear to occur when entering an unordered list. It saves and stays where the cursor was.
