### ISSUE TITLE
No ACK in message list for 2.8.1

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#432]
Creating a new IG from standard. ACK not in list of messages.

**Comment by haffonist** [comment]
@gcr-nist  any reason why ?

**Comment by robsavage** [comment]
No idea, there should be, it is in the standard.
R
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by haffonist** [comment]
G,

I think you forgot that we don't close anything that has not been QA yet. Please move back to QA.



________________________________
