### ISSUE TITLE
value set search is not user friendly

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#436]
When searching for a value set to bind to a data type element, it doesn't let you search by table number (eg 0396), you have to search  by the start of the name (eg co for "coding system" (table 0396). However, the search results only give the table number and they aren't in numerical order (presumably they are in alphabetical order based on the table name). This makes it really hard to find the right value set.

![image](https://cloud.githubusercontent.com/assets/17408249/17222029/ee428326-54bb-11e6-9f73-e78c295aae30.png)

**Comment by haffonist** [comment]
fixed
