### ISSUE TITLE
User defined data types not named right

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#437]
In the Word document export, user defined data types (ones copied from the basic data type) have bad name. Rather than using the data type extension (01 in the example below), it just seems to repeat the data type name.

![image](https://cloud.githubusercontent.com/assets/17408249/17224018/bd5e538a-54c4-11e6-94ab-099491e0e3a8.png)

![image](https://cloud.githubusercontent.com/assets/17408249/17223975/8f880c58-54c4-11e6-9e7a-a6825d5366bf.png)

**Comment by haffonist** [comment]
@csnewman88 please confirm fix.

**Comment by csnewman88** [comment]
looks good
