### ISSUE TITLE
Definition text doesn't show up in the Word document

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#439]
Even though I added Definition Text for the first two elements in a user defined EI data type, this text doesn't show up in the Word Document.

![image](https://cloud.githubusercontent.com/assets/17408249/17224176/8038bd5a-54c5-11e6-8999-1811f9a92f8b.png)

![image](https://cloud.githubusercontent.com/assets/17408249/17224238/b38006d2-54c5-11e6-93d4-c73b6b7c401b.png)

**Comment by csnewman88** [comment]
Update - the text is there, it's just not associated with the specific element.

**Comment by haffonist** [comment]
Thanks Craig for reporting this. We will fix this.

**Comment by olivier-m-mr** [comment]
Taken care of by @Abdelghani90. Thank you
