### ISSUE TITLE
what gets exported for a data type?

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#440]
Is the Purpose and Use of the data type expected to be exported. I kind of assumed it would be, but it's not in the Word Document. The Definition Text for the data type is, but not the Purpose.

![image](https://cloud.githubusercontent.com/assets/17408249/17224310/1042a41a-54c6-11e6-949b-c77021f24b89.png)
![image](https://cloud.githubusercontent.com/assets/17408249/17224351/38de811e-54c6-11e6-9024-d91fe51752fe.png)

**Comment by haffonist** [comment]
Correct, we will add this.
Thanks
