### ISSUE TITLE
IGAMT Login issue

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#441]
My IG is not displayed, when I first log in. It takes a second login to see it.

**Comment by robsavage** [comment]
I have seen the same thing.  I solved the problem by clicking back and forth within the same instance (my ig, ig library, my ig)
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by haffonist** [comment]
Yeah this is known bug. For now just click on the button on the top to reload the is documents.

**Comment by haffonist** [comment]
This is fixed now.
