### ISSUE TITLE
confused by the "O to X" option

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#449]
When I create a custom version of an atomic data type (ID, IS), there is a blue box in the Usage header of the Data Type Definition (see red box below). When I click this, it as me if I want to make the Usage go from O to X. When would this be useful? Once I click the button and consent to the usage change, I get the acknowledgment (see red arrow below) but I don't see any other change. The button is still active and behaves the same (which seems odd) and I don't see a way to change the Usage from X back to O (or some other usage). Overall, I'm not sure what this is trying to accomplish

![image](https://cloud.githubusercontent.com/assets/17408249/17303405/2ad250c8-57e6-11e6-960f-ba6bbda75f2e.png)

**Comment by csnewman88** [comment]
That same button is on all custom data types (see below for MSG). Even when there are components in a complex data type like this, why would you want this functionality?
![image](https://cloud.githubusercontent.com/assets/17408249/17305279/4f4867cc-57ef-11e6-9df0-a3a820ea9fad.png)

**Comment by haffonist** [comment]
@robnist can you answer this ?

**Comment by haffonist** [comment]
I got some explanation on this. Some ig documents have lots of O that should be X. This is a shortcut to change O to X.
