### ISSUE TITLE
export in Word produces blank document

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#450]
I tried to export in Word. I get a blank document with the following text:

{"text":"internalError","resourceId":null,"skip":false,"manualHandle":"false","scope":null,"version":null,"date":null,"id":null,"type":"danger"}

**Comment by haffonist** [comment]
Olivier, seems this is a null pointer exception. Please fix.

**Comment by olivier-m-mr** [comment]
Working on it

**Comment by robsavage** [comment]
I recreated the problem. I took an existing IG, cloned it. I edited profiles and renamed one (Z42 to Z92). I cloned an MSH segment that went with the Z42 and edited the profile, selecting the new cloned MSH. Then exported and got blank doc.  I tried to repeat with another clone without success. one is named IZ profiles broke and on just IZ profiles.

**Comment by haffonist** [comment]
@olivier-m-mr  what is the update of this ?

**Comment by robsavage** [comment]
I created a new IG from scratch, V 2.5.1, "HL7 V2.5.1 Implementation Guide for Requesting an Official Immunization History". I have been exporting to Word intermittently. I had success last at 1:58 (central) on 8/18. Today I imported CX data type, cloned several segments, modified the name of ACK profile.  I have attached the last successful export. Today, when I attempted to export in WORD, I got the empty document with error statement: {"text":"internalError","manualHandle":"false","skip":false,"resourceId":null,"date":null,"version":null,"scope":null,"id":null,"type":"danger"}
[HL7-V2.5.1-Implementation-Guide-for-Requesting-an-Official-Immunization-History-20160818_145803.docx](https://github.com/haffonist/igamt/files/430137/HL7-V2.5.1-Implementation-Guide-for-Requesting-an-Official-Immunization-History-20160818_145803.docx)

**Comment by robsavage** [comment]
not sure if it is related, but closed igamt, reopened and then tried to click to RSP segment. got the spinning dots for long time.

**Comment by olivier-m-mr** [comment]
[Request-official-immunization-record.docx](https://github.com/haffonist/igamt/files/449667/Request-official-immunization-record.docx)

**Comment by haffonist** [comment]
Hi @robsavage this should be fixed now. Please confirm.

**Comment by robsavage** [comment]
Hooray

I just exported one of the problem IG in WORD.  Got a WORD document and not a blank document.

Thanks
Rob
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by robsavage** [comment]
thanks

**Comment by haffonist** [comment]
From now on we will create the word document with any error found. Please check your document to see if it has any error. The document will contain a description of the error in red.

Thanks

Harold

________________________________
