### ISSUE TITLE
autosave locks pull down 

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#451]
When editing a cloned segment, I tried to create a new conformance statement. If I had a pull down open (in process of selecting) and autosave occurred, that drop down was locked and empty. I cancelled and recreated the CF, without problem. Went to create a second CF and encountered same problem.

**Comment by haffonist** [comment]
Rob,
There is no autosave in igamt. What do you mean ? Can you provide some screenshots ?
Thanks

**Comment by haffonist** [comment]
@Jungyubw look into this.

**Comment by robsavage** [comment]
not sure it is an autosave. there is a hiccup I interpreted as autosave. when this occurs in some cases the cursor jumps back to the beginning of text block.

**Comment by Jungyubw** [comment]
I cannot reproduce it at my side. 

@robsavage, do you still have this issue?

**Comment by robsavage** [comment]
I still get jumped to the beginning of a block of text when the screen flickers (auto save?), but I have not been looked in pull down for a while.

thanks
Rob
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039
