### ISSUE TITLE
Missing value sets

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#452]
What determines if a value set is included in an IG? Right now, even though my message contains an MSH segment and uses the MSH data type, none of the three necessary value sets show up. I can manually add the tables, but I'm not sure why they aren't there to start with.

![image](https://cloud.githubusercontent.com/assets/17408249/17303813/ee8a0c4e-57e7-11e6-835d-906cba8ef2fb.png)

**Comment by Abdelghani90** [comment]
@Jungyubw  this is related to other functions we still working on

**Comment by haffonist** [comment]
@Abdelghani90 is this fixed ?

**Comment by Abdelghani90** [comment]
@haffonist we should see after merging because it is related to data issues and some old issues we have already fixed
