### ISSUE TITLE
mass delete of values in a value set

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#453]
Some value sets are very large when you import them (for example 0003 - event type) and it is a lot of work to individually remove values you don't want (or to set the Usage to E). It would be nice to have a way to select all values (and maybe individually unselect a few) and then do a mass delete or data set

![image](https://cloud.githubusercontent.com/assets/17408249/17304486/67a09b4a-57eb-11e6-8e6f-defffa8fb121.png)

**Comment by haffonist** [comment]
@woo, Who is working on this finally ? you or @Abdelghani90 ?

**Comment by Abdelghani90** [comment]
I am working on it
