### ISSUE TITLE
custom value set usage starts out null

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#454]
When you copy a value set, the custom value set starts out with no Usage assigned to any of the values. I know you can't read the user's mind and assign the right usages, but starting out with one of the values (P perhaps) will mean that at least a few values have the right usage and don't need to be manually set. As it is now, the author has to set every value, any time savings would be good. Plus, what if the author doesn't set a usage? How will a reader interpret a value set where some or all values are missing a Usage? Having a default is good.

![image](https://cloud.githubusercontent.com/assets/17408249/17304651/3ed7e5a0-57ec-11e6-914a-6d6ed0676496.png)

**Comment by Jungyubw** [comment]
@csnewman88 

Default is "P". I have tested it, but I cannot find empty usage for copied value set.

If you meet this issue again, let me know.

Thanks.
