### ISSUE TITLE
Usage of F??

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#455]
It looks like all values in the HL7 base value sets have a Usage of F. What does F mean? Once I make a user defined copy of the value set, the only options are the familiar R, P and E. Do we even need a Usage column for base value sets if we expect users to copy them anyway?

![image](https://cloud.githubusercontent.com/assets/17408249/17304770/dae996dc-57ec-11e6-824f-f7c5e88fa900.png)

**Comment by Jungyubw** [comment]
F value is wrong. We just have R/P/E. I guess we had a fault to set the usage for code before.

I have updated database to use 'P' instead of 'F'. If you find any other 'F', let me know.

Thanks.
