### ISSUE TITLE
hitting "enter" while searching for a value set does the unexpected

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#456]
I tried to search for a value set to associate with an element in a custom MSG data type. I typed in a few characters and hit "enter". As soon as I hit enter, I got a popup box that asked if I wanted to Change Usage from O to X. This doesn't seem like the right behavior

![image](https://cloud.githubusercontent.com/assets/17408249/17305143/c0d0d20e-57ee-11e6-97ca-0df84d4a72bd.png)

**Comment by haffonist** [comment]
Ismail, please use the new widget I talked about. 
Thanks

**Comment by haffonist** [comment]
fixed
