### ISSUE TITLE
Value set search doesn't always work

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#457]
I tried to add a value set to elements in a custom MSG data type. When I tried to search for the "event type" value set by entering "e" into the search box, no results were returned even though there were clearly multiple value sets starting with "e".

![image](https://cloud.githubusercontent.com/assets/17408249/17305377/ca155500-57ef-11e6-8a1b-4fece8d96189.png)

"m" works fine as a search value and even brings up things like "admission type (0007)" which is probably too permissive

![image](https://cloud.githubusercontent.com/assets/17408249/17305482/24b00ea6-57f0-11e6-9afa-9771e331dbc8.png)

**Comment by haffonist** [comment]
fixed
