### ISSUE TITLE
Cross reference statement is inaccurate

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#458]
if a table (or data type or anything) is not cross referenced, the text statement says "segment" rather than table (or whatever is appropriate. This will confuse people

![image](https://cloud.githubusercontent.com/assets/17408249/17370231/e5153a92-5960-11e6-8515-914f4b97d96b.png)

**Comment by haffonist** [comment]
This is already fixed and will be deploy soon.

**Comment by haffonist** [comment]
fixed
