### ISSUE TITLE
Extensibility of "close" won't save

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#460]
When updating a custom value set, if the Extensibility is set to "close", it is not possible to save the value set. If you set any other attribute or set Extensibility to "open" and click the save button, you get a popup in the upper right corner saying the value set was saved, but if Extensibility is set to "close", you don't get that popup and if you try to migrate to a different section of the IG, you get the "unsaved data" warning. If you click "save and continue" in this popup, nothing happens. If you "discard changes", you do move away and the changes are lost.

![image](https://cloud.githubusercontent.com/assets/17408249/17406805/97f521b2-5a2a-11e6-9252-7e9ccf2684ae.png)

**Comment by haffonist** [comment]
fixed.
