### ISSUE TITLE
value set name doesn't update

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#462]
When a custom value set is created it is assigned an ID suffix (red arrow below) which is part of the value set record but also used as the ID in the data type it is bound to:

![image](https://cloud.githubusercontent.com/assets/17408249/17407369/9cb19562-5a2c-11e6-9e77-e99ad1858b26.png)

but if you doing the binding and then update the ID suffix, the name of the value set in the data type is not updated (see difference between red and blue arrows below). If a value set ID is updated, it needs to be updated in places that use it.
![image](https://cloud.githubusercontent.com/assets/17408249/17407495/1b2144f6-5a2d-11e6-94a4-3dc1b6b8c55f.png)

**Comment by Jungyubw** [comment]
@Abdelghani90 

Please make sure that:

We will not use "name" and "ext" in link, we should use Object name and ext.

Please check all UI for Table mapping on Message/Segment/Datatype views.
