### ISSUE TITLE
can't add new data type

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#463]
I have created a clone of the data type table with ED data type in it. I tried to add to the data type list and don't see it in the pull down list.
[ed datatype.pdf](https://github.com/haffonist/igamt/files/401965/ed.datatype.pdf)

**Comment by robsavage** [comment]
I figured it out

**Comment by robsavage** [comment]
I am encountering this problem again. I have assured that ED is in table 0441. The attached screen shot shows all my choices.
[2 data type import.pdf](https://github.com/haffonist/igamt/files/413594/2.data.type.import.pdf)

**Comment by haffonist** [comment]
As of now we only import HL7 datatypes. I am confused by "ED is in table 0441". What do you mean ? 
Thanks

**Comment by haffonist** [comment]
@robsavage any update ?

**Comment by haffonist** [comment]
@IsmailMellouli any update on this ?

**Comment by haffonist** [comment]
I believe this is now closed

**Comment by robsavage** [comment]
closed
thanks
R
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039
