### ISSUE TITLE
value set cross referencing is not working

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#464]
Even when a value set is bound to a data type which is used in a custom segment which is used in a profile, the cross reference tab in the value set still says it's not being used. Cross referencing at the segment and data type level seems to work fine.

![image](https://cloud.githubusercontent.com/assets/17408249/17407630/9b431c54-5a2d-11e6-8a1e-4f8785ccd3bd.png)

![image](https://cloud.githubusercontent.com/assets/17408249/17407662/cba02b4e-5a2d-11e6-82db-f8114b06eef1.png)

**Comment by haffonist** [comment]
No just value set but also Try with datatype, segment, message.

**Comment by haffonist** [comment]
fixed.
