### ISSUE TITLE
How to add non HL7 and non PHINVADS value sets

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#465]
The immunization IG uses USPS state abbreviations but I don't see a way to load value sets that aren't based in HL7 or PHINVADS. How would I do this?

**Comment by haffonist** [comment]
I think you mentioned in one of your tickets the idea or importing a csv file. Does this still apply here ?

**Comment by robnist** [comment]
See my related comment. PHINVADS may or may not have all the external code systems we want. We need to look into using FHIR to access terminology servers for importing and importing/filtering code systems. We need to support both (and probably others). This will allow the user the choice of where they can import code systems.

**Comment by Jungyubw** [comment]
Now we support 4 ways to create New Table:

1. Create New Table from the beginning.
2. Create New Table from the HL7 base
3. Create New Table from the PHINVADs
4. Create New Table from CSV file
