### ISSUE TITLE
Adding value sets to ST elements

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#466]
The State element in XAD (XAD.4) is a string data type (ST) but those strings should be chosen from the set of USPS state abbreviations. But it's not possible to bind a value set to an ST element. How do we handle this?

**Comment by robsavage** [comment]
conformance statement I think
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by haffonist** [comment]
@robnist any input ?

**Comment by Jungyubw** [comment]
Same ticket with #510

**Comment by haffonist** [comment]
Per rob: 
We should analyze the circumstances in which they are allowed. We should gray out area where you can't bind a value set.
@carolinerosin  is working on determining the list of data types where we should allow binding of value set.
