### ISSUE TITLE
Possible need for conditional value sets

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#467]
The immunization IG current says the following for the XAD.4 data type.

This component specifies the state or province where the addressee is located. State or province should be represented by the official postal service codes for that country. In the US it SHALL be the 2 character state codes (ie AK, ME, WI)

Should we be trying to make the last sentence into conditional value set or just make it a conformance statement (which won't be machine computable)

**Comment by Jungyubw** [comment]
@csnewman88, as you know, we are supporting to this pattern using regrex format in the conformance statment. For now you can use this.

@robnist Do you think we need have some pattern codes for the value set? like 5 digit codes?

**Comment by robnist** [comment]
Yes. We should associated a format validation to value sets that have a specific format defined. This should be part of the validation. IGAMT can have defaults. The user could add their own if none exists or modify the default. We need to discuss with Hossam.
