### ISSUE TITLE
can't add value sets

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#470]
All of a sudden, I can't add any value sets. I've tried 3 or 4 different ones (alone and in pairs) and while I get a "table is successfully save" announcement, the tables don't show up in the Value Set list. Maybe the get added but not displayed? At the very bottom of the value set list there is a funny looking "bbb" (see red arrow below)

![image](https://cloud.githubusercontent.com/assets/17408249/17415123/01ad8c70-5a4e-11e6-8f3f-1d536d1516f7.png)

**Comment by csnewman88** [comment]
Update - I got kicked out of the IG (don't know what happened) but when I went back in, all the tables I was trying to add are now there.

![image](https://cloud.githubusercontent.com/assets/17408249/17415375/3a794462-5a4f-11e6-8809-7a7475ff258b.png)

**Comment by haffonist** [comment]
@Abdelghani90 make sure the value sets are showing when added. And please remove the bbb string.

**Comment by haffonist** [comment]
fixed.
