### ISSUE TITLE
Need to enhance the DTM data type

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#471]
The DTM data type needs some special functionality so that we can designate how year, month, day, hour, etc are used. For example, we need something like this:

![image](https://cloud.githubusercontent.com/assets/17408249/17416140/72c33122-5a52-11e6-901a-d3941d6c186d.png)

![image](https://cloud.githubusercontent.com/assets/17408249/17416085/353b074e-5a52-11e6-90a3-53b8513f89a2.png)

**Comment by robnist** [comment]
Harold,
The Lab group is finalizing a group of data type flavors for this. I think we can adopt and include as our first set of master DT flavors. I will provide the spec.

**Comment by haffonist** [comment]
Guys, let's brainstorm on how to implement this.

**Comment by Jungyubw** [comment]
Done. I implemented DTM special UI for formatting.
