### ISSUE TITLE
deleted conformance statement IDs are still used

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#472]
I was trying to replicate existing conformance statements from the immunization IG and I put one on the wrong field. So I deleted the conformance statement and tried to recreate it on the correct field, but when I did, I got a notification that the ID as duplicated even though the original conformance statement had been deleted. This is going to keep me from creating conformance statements in IGAMT that line up with the existing guide. 

Once a conformance statement is deleted, if I can't get it back (to move it to a different field), then the ID should go back into the pool of IDs that are valid. Maybe we need to distinguish between "delete" and "retire" for conformance statements (IDs from the former could be reused but IDs from the latter could not).

Step 1 - create a conformance statement
![image](https://cloud.githubusercontent.com/assets/17408249/17439772/40abd30e-5aef-11e6-9676-aa739c9bd15a.png)

![image](https://cloud.githubusercontent.com/assets/17408249/17439788/4d3514be-5aef-11e6-8c70-14ebdf5012df.png)

Step 2 - delete the conformance statement
![image](https://cloud.githubusercontent.com/assets/17408249/17439817/65923078-5aef-11e6-9056-cf5a5133a99d.png)

Step 3 - try to recreate a conformance statement
![image](https://cloud.githubusercontent.com/assets/17408249/17439887/a021ae80-5aef-11e6-8b04-9068ff5c75a1.png)

**Comment by Jungyubw** [comment]
Fixed

**Comment by haffonist** [comment]
Need to review

**Comment by Jungyubw** [comment]
Working now
