### ISSUE TITLE
No way to revert a node selection in conformance statements

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#473]
If you select the wrong value in the Node, you can't go back and correct your mistake. In the example below, I selected MSH-22 but intended to pick MSH-21, but now, I can choose a component of MSH-22 but I can't change it to MSH-21. I have to "close" to get rid of the conformance statement under construction because there isn't even a way to throw away the new conformance statement and start again without closing the popup window

![image](https://cloud.githubusercontent.com/assets/17408249/17443770/12aea202-5b02-11e6-8e80-5f604180aa5c.png)

**Comment by Jungyubw** [comment]
Will consider later.

**Comment by Jungyubw** [comment]
this ticket merged to #725
