### ISSUE TITLE
Need to reorder conformance statements

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#474]
There needs to be a way for an author to specify the order in which conformance statements are listed. It seems like the "draggable" column might allow this, but if it does, I can't figure out how to use it. In the case below, I created the statements out of order and want to reorder them, We can assume all conformance statements should be in numeric (alphabetical) order but there has to be a way to specify the best order.

![image](https://cloud.githubusercontent.com/assets/17408249/17443946/ff20bc1a-5b02-11e6-8af6-c5c03b08267a.png)

**Comment by Jungyubw** [comment]
Draggable icon is just for Complex Constraints. So I make this icon will be shown when the user choose "Complex constraint mode".

Also you can sort the constraints by location or id.
