### ISSUE TITLE
Usage of R and X should set the cardinality

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#475]
One of the most obvious advantages to IGAMT is to enforce technical rules. One of these is that R elements have to have a minimum cardinality of at least 1 and X elements should have a cardinality of 0..0. So when an author changes the usage to one of these values, the cardinality should automatically update. In the example below, when PID-8 was set to R, the minimum cardinality was still 0 (blue arrow)

![image](https://cloud.githubusercontent.com/assets/17408249/17444728/332fc6be-5b07-11e6-9b1d-152474d0c9e8.png)

**Comment by Abdelghani90** [comment]
@haffonist 
Fixed for message and segment => abdel-DtLib branch
