### ISSUE TITLE
valildate the cardinality fields

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#476]
An author can enter values into the Cardinality fields that don't make sense.  In the example below, you can put anything into one of those fields (blue box) or have a minimum cardinality larger than the maximum cardinality (green box). You should validate that the values make sense (min<max, consists of a number or "*", etc),. This sort of validation is one of the biggest selling points of IGAMT (keeping people from doing something stupid)

![image](https://cloud.githubusercontent.com/assets/17408249/17444907/1a2322fa-5b08-11e6-97f2-90241a342331.png)

**Comment by haffonist** [comment]
@IsmailMellouli and @Abdelghani90 please fix this today.

**Comment by Abdelghani90** [comment]
@haffonist is it fixed now?

**Comment by haffonist** [comment]
The validation is missing for message.

**Comment by haffonist** [comment]
We need  to support the following values as well: 
*, =, #
