### ISSUE TITLE
Usages lost in custom segments

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#477]
When duplicating a segment, fields with a base usage of B or W don't have a default usage in the custom segment (blue and red boxes below). Given that W elements can only be constrained to X, it seems like the Usage could be set to X and the cardinality set to 0..0. For B, it's a bit harder. I don't think it should be set to X. Are B's allowed in constrainable profiles? I don't think so, but I don't like having them be blank. Not sure what to do

![image](https://cloud.githubusercontent.com/assets/17408249/17445697/9ea7aafc-5b0b-11e6-9b0b-466c3dbb582d.png)

**Comment by Jungyubw** [comment]
@haffonist  What do you think of?

**Comment by haffonist** [comment]
This is fixed now. We changed all W,B,F usages to X
