### ISSUE TITLE
Cardinality is wrong for a few fields

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#478]
In v2.8.2 base, the PID-13 and -14 fields are allowed to repeat (even though they have a usage of B) - see blue box below. but in the base segment definition, the cardinality is 0..1 (green box below). I think it should be 0..*

Other fields may be similarly affected (in fact all of the repeating fields in the screen shot below have this issue).. 

![image](https://cloud.githubusercontent.com/assets/17408249/17445863/43274a06-5b0c-11e6-8f01-657acda27dd1.png)

![image](https://cloud.githubusercontent.com/assets/17408249/17445815/16789b4a-5b0c-11e6-8543-baa5a2fe6bb1.png)

**Comment by haffonist** [comment]
@gcr-nist is this an issue in Frank's base ? How do we fix this ?

**Comment by haffonist** [comment]
@gcr-nist Will this be fixed now ?

**Comment by gcr-nist** [comment]
According to the rules we established Friday last, it is fixed.  e.g. the cardinality of the fields cited above are no longer 0..1 but are now 0..* .

**Comment by haffonist** [comment]
Same to QA

________________________________
