### ISSUE TITLE
tables versus value sets

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#481]
In multiple places, you use the word "table" when I think you want "value set". There is a level of complexity here that I know I don't understand and which many IG authors won't either. We want them to use value sets (and not tables) in their own IGs, so the tools should not use table unless it is referring to an actual table and not a value set.

![image](https://cloud.githubusercontent.com/assets/17408249/17446725/38672dd0-5b10-11e6-9624-a72519fae6bc.png)

![image](https://cloud.githubusercontent.com/assets/17408249/17446786/903b30ec-5b10-11e6-8ac2-663b99fc405c.png)

**Comment by haffonist** [comment]
Let's replace all "Table", "table" labels by "Value Set"
