### ISSUE TITLE
How do I import several message structures in a single IG ?

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#485]
Is it possible to have several message structures in a single IG ?
Example : 
OML^O21^OML_O21
ORL^O22^ORL_O22
ACK^O22^ACK

in one IG document and not 3

**Comment by robnist** [comment]
Yes. We have 8 in immunization. 

When you first created the IG you can select as many as you need. I'm pretty sure you can add more as you go--if not, then that feature needs to be added.

**Comment by carolinerosin** [comment]
ok I'll have look. Problem is now that I already created the OML^O21 for LOI, can I still add the other ones ?

**Comment by Jungyubw** [comment]
Yes, you can add a message on your profile.

**Comment by carolinerosin** [comment]
ok I found it, thank you !
