### ISSUE TITLE
Adding component to a datatype does not seem possible

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#486]
I'd like to add components to some datatype flavors I created, I don't think this is possible ? It looks like I can do it for fields in a segment.

**Comment by robnist** [comment]
Why?

Is this because a DT was pre-adopted from a later version of HL7? If so, then we should allow for the pre-adoption (which I think is supported already--but I can't remember).

**Comment by carolinerosin** [comment]
yes it is for preadoption of datatype
Example : 
![igamt_18](https://cloud.githubusercontent.com/assets/13591511/17571069/ca9afe92-5f1c-11e6-885f-dbc4ecd8227f.JPG)

**Comment by haffonist** [comment]
No pre-adoption as of now. We will add this.

**Comment by robnist** [comment]
What is the solution here?

Adding a component is the wrong solution and something we do not want user to be able to do. This goes against IGAMT philosophy. The solution is to allow pre-adoption. This is the intent of the standard allows and what the IG states.

**Comment by IsmailMellouli** [comment]
Should we support pre-adoption for datatype ?

**Comment by robnist** [comment]
Yes. I don't like it in general but we really don't have a choice. We do not want to support adding a component. Only field and segment and this should be for only certain message types that support query and response messages.

**Comment by haffonist** [comment]
This becomes an issue with wether we want to support pre-adoption of datatype or not.Per our discussion with the user group, we decided to support pre-adoption for datatype as well.
