### ISSUE TITLE
view assertion checkbox

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#487]
1. The checkbox has no effect before we "add" the predicate or conformance statement. This can be confusing.
2. View assertion should show the whole predicate/conformance statement, not only the condition.
3. Is that a feature that will stay ? I agree that is useful during development stage, to see the constraint that is generated, but to we want expose that to the final user ?

**Comment by Jungyubw** [comment]
I think the information will help user to check the validation, because we will allow user edit the cs/cp description.

I will check (1) issue.

**Comment by Jungyubw** [comment]
We will see this ticket later.
