### ISSUE TITLE
Root of XXX for predicate

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#488]
What is the use of "Root of ..." for the predicates ? What would be generated in in Target element of the conformance context ?
![igamt_1](https://cloud.githubusercontent.com/assets/13591511/17568986/41fa5bf8-5f14-11e6-9508-4b21b142ca16.JPG)

**Comment by Jungyubw** [comment]
I will modify that this function is just for primitive DTs (no component) conformance statement.
we implemented this for DTM conformance statements.

DTM does not have any child component but we need to define Date Time format assertion.

**Comment by carolinerosin** [comment]
I think the validation core already does part of the work for the date/time format. What is not checked by the validation, maybe the user can implement at the parent level instead of the primitive datatype ?
I just don't quite see what we will generate in the conformance context if we ant to add a constraint on a primitive datatype (I am not sure the conformance context and validation allow that)

**Comment by Jungyubw** [comment]
Fixed
