### ISSUE TITLE
Complex predicate and conformance statements

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#489]
The process to write complex predicates and conformance statements needs to be improved.
1. For predicate, it does not make sense that the user has to choose True Usage/False Usage for each "part" the the complex predicate.
2. For conformance statement, the user has to "make up" unique identifier that are useless, because they will be deleted.
3. The whole process is cumbersome : the user needs to create all the "bricks", combine two together (and only two), then delete the "brick" ones. Too many operations (what if the user has to combine 3, 4 or more ?)

**Comment by Jungyubw** [comment]
We already know 1 and 2 issue. 

For 3, user can make a complex one using two plain ones, and then user can add the another plain one into the complex one. 

At the first time, I implemented the system automatically delete used brick ones, but we changed it to keep used ones. but I am not sure why...

**Comment by carolinerosin** [comment]
I see, my problem is that sometimes I have a lot to combine (5 or more) so it takes a lot of time to create, combine,delete. I don't have a clear solution right now, but I think this is something we should think of to improve the tool..

**Comment by Jungyubw** [comment]
We will discuss it later.

**Comment by Jungyubw** [comment]
Updated UI, Please check this again
