### ISSUE TITLE
"is not" implementation does not look right

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#491]
The "is" and "is not" produce the same assertion. 
![igamt_3](https://cloud.githubusercontent.com/assets/13591511/17569221/459f9484-5f15-11e6-967f-6655c7c69667.JPG)

**Comment by robnist** [comment]
I don't understand; both are "is not" in the image you provided.

**Comment by carolinerosin** [comment]
yes but the Assertion that is added in the conformance context does not contain the "NOT"
if I implement the "is", I get the exact same assertion

**Comment by Jungyubw** [comment]
I will fix it.

**Comment by Jungyubw** [comment]
fixed
