### ISSUE TITLE
modifying a conditional usage

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#492]
I noticed that if a user wants to change the usage once a predicate is set (example : changing a C(R/X) to O), the predicate needs to be deleted first. It is that obvious that this a two steps process (and only when the predicate is set)

**Comment by robnist** [comment]
When changed from C to O (or something else), we could just remove the predicate--but then you lose the predicate. I'm OK with this. We could "store" the deleted predicate and if the user changes it back provide the user with an option to re-instate the predicate.

**Comment by haffonist** [comment]
@Jungyubw we will need to think about this.

**Comment by Jungyubw** [comment]
@carolinerosin @csnewman88 @robnist, I added cross button for conditional usage. If you want to change the conditional usage (like C to O), you can click this button. Then the predicate will be deleted and you can choose another usage.
