### ISSUE TITLE
predicate and conformance statement location could be improved

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#493]
Location could be improved: include the flavor name, remove the brackets (unless there is a use I don’t see?) ?
![igamt_4](https://cloud.githubusercontent.com/assets/13591511/17569357/d3957f2e-5f15-11e6-8d58-13c5f46560be.JPG)

**Comment by robnist** [comment]
Agreed.

**Comment by Jungyubw** [comment]
I will handle it.

**Comment by Jungyubw** [comment]
Done
