### ISSUE TITLE
Location of conformance statement can be empty

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#496]
is that an expected behavior ? what is going to be generated for the conformance context ?
![igamt_7](https://cloud.githubusercontent.com/assets/13591511/17569495/87be1966-5f16-11e6-983d-14d8dd9e34c9.JPG)

**Comment by Jungyubw** [comment]
Because you created this CS on the root. Location is '.', not empty.
Anyway we will prevent root CS for complex DTs

**Comment by carolinerosin** [comment]
ok sounds good

**Comment by Jungyubw** [comment]
Fixed
