### ISSUE TITLE
do not allow the conditional element to be part of the condition

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#497]
when a user write a predicate for a particular element (example EIP_GU.2), it does not make sense that the said element can be chosen in the condition predicate.

**Comment by Jungyubw** [comment]
I understand this, but it is not critical.

Frankly I don't want to make too many restriction for the user to define the CP.
However I will consider it again after we update CS/CP editor.

**Comment by carolinerosin** [comment]
sounds good, thank you

**Comment by Jungyubw** [comment]
This ticket will be at "pending". We will see it later.
