### ISSUE TITLE
datatype missing from library

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#498]
Some datatypes are missing from the library I use (ERL, OG), so I can't create my own flavor and properly define my segments.

**Comment by haffonist** [comment]
Hi Caroline, 
Are you stil having this issue ?

**Comment by carolinerosin** [comment]
Sorry - I just noticed I never answered. Looks like the missing datatypes (at least ERL and OG) are present now. I'm closing the issue.
