### ISSUE TITLE
multiple predicate for same element

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#499]
IGAMT allows the user to define multiple predicates on the same element. I am not sure if that should be the case and how the validation will react ?

**Comment by Jungyubw** [comment]
I will fix it.

**Comment by Jungyubw** [comment]
I added warning message if node has multiple predicates

**Comment by robnist** [comment]
I need more info on this one. There should only ever be 1 CP for an element. Explain when there would be a need for multiple? To me this is a specification error.
