### ISSUE TITLE
conformance profile viewer and group names

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#500]
would be nice to be able to see the whole group name
![igamt_11](https://cloud.githubusercontent.com/assets/13591511/17569908/31967310-5f18-11e6-891d-a00d15af1892.JPG)

**Comment by haffonist** [comment]
Fix the name of the group 
Fix the ui to display in a tooltip the name of the element.

**Comment by carolinerosin** [comment]
Looks like some update took care of that one, thanks !
