### ISSUE TITLE
cannot implement predicate

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#503]
I don't think IGAMT supports this type of predicate : target element is PID-11 but condition predicate references a node in another segment (PV1). Note that this is something I can do when I write my profile “by hand” and I implement it at the group level.

![igamt_13](https://cloud.githubusercontent.com/assets/13591511/17570063/dbf5fb3c-5f18-11e6-80aa-e03230f43e78.JPG)

**Comment by Jungyubw** [comment]
Of course we can do. Please try to make message level predicate.

**Comment by carolinerosin** [comment]
ok I probably missed it - I'll give it a try and will get back to you.
Thank you

**Comment by carolinerosin** [comment]
got it, thanks !
