### ISSUE TITLE
group level conformance statement do not seem to be correct

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#504]
When I want to add a conformance statement at a group level (PATIENT), I have access to elements that are not in that group (MSH). Does not seem right, what is the exact constraint that is going to be generated in the conformance context ?
![igamt_14](https://cloud.githubusercontent.com/assets/13591511/17570331/eb811fae-5f19-11e6-9fa9-007221851b3c.JPG)

**Comment by Jungyubw** [comment]
IGAMT does not support Group Level Constraints. this is message level.

So you can access every location.

**Comment by carolinerosin** [comment]
I'll have to think about that a little bit more, but I think we may run into issues for groups that can repeat if we don't support group level constraints.

**Comment by Jungyubw** [comment]
This ticket is merged into #725
