### ISSUE TITLE
TS/DTM constraint implementation

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#507]
I am not sure if this is doable or not
![igamt_10](https://cloud.githubusercontent.com/assets/13591511/17570543/d1d35792-5f1a-11e6-9ae6-97879d1b9c45.JPG)

**Comment by Jungyubw** [comment]
We already know this issue, IGAMT will support it.

**Comment by Jungyubw** [comment]
This ticket is closed because it merged to #471
