### ISSUE TITLE
adding a value set

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#510]
More like a @robnist  question : 
should it be allowed to add a value set on an element that is ST ? IGAMT does not let me do that, but LOI IG has it (XAD.4 with USPS Alpha State Codes).

**Comment by Jungyubw** [comment]
@robnist Could you make an answer for us?

**Comment by robnist** [comment]
Yes. We need to allow for this. Typically these are value set binding that do not have a specific HL7 table associated with the element. HL7 tables have IS or ID DT for the primitive elements. External tables do not. So for elements like XAD.4 and XAD.5 we need to allow the value set binding. 

However, the question is do we allow for all elements or do we review and allow for only certain elements where it makes sense.  For now we can allow all for primitive types or if someone wants to go through the DTs and provide a list for the ones that makes sens.

**Comment by haffonist** [comment]
@Jungyubw this needs to be moved back to sprint backlog, correct ?

**Comment by haffonist** [comment]
duplicate with $510
