### ISSUE TITLE
CP editor needs additional functionality

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#512]

**Comment by csnewman88** [comment]
It's not possible to write the current immunization ORC=-10 predicate. it references a field in a different segment (the RXA segment) and it also targets a specific occurrence of a field (1st occurrence in RXA-9). Ultimately, we will likely change the occurrence requirement to a coding system reference (00 from the NIP001 coding system must be present in RXA-9) but either way new functionality is required.

Common Order Segment (ORC)
				
12	Ordering Provider	If the first occurrence of RXA-9.1 is valued "00" and RXA-20 is valued "CP" or "PA"

**Comment by haffonist** [comment]
This marked urgent. Please fix ASAP.

**Comment by Jungyubw** [comment]
@csnewman88, please create this predicate at the message level

**Comment by csnewman88** [comment]
that would be inconsistent with how we are using conformance predicates in all other cases where we are putting them at the segment level. Even for conformance statements, I've been putting them at the segment level if they will apply to all profiles and only  putting them at the profile level if they vary by profile (for example the MSH-21 value will change by profile).

Can we discuss this on our Wednesday morning call next week (Aug 31)?

**Comment by Jungyubw** [comment]
Okay. We will discuss it.  I will let this ticket at Pending.

**Comment by haffonist** [comment]
@haffonist for reference

**Comment by haffonist** [comment]
Need to define the predicate across segments in a profile. Does the validation support this ?

Harold
