### ISSUE TITLE
server error on save

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#513]
I copied use case section, deleted interaction section from one, clicked on the cloned interaction section. A popup asked to save before leaving. I saved and got a popup stating save failed due to error on server.

**Comment by robsavage** [comment]
[1 server error.pdf](https://github.com/haffonist/igamt/files/413372/1.server.error.pdf)


the server error popup disappeared before I could capture.

**Comment by robsavage** [comment]
I repeated this by editing a section text and attempting to move outside the section to another section.  Got asked to save and got server error.

**Comment by haffonist** [comment]
@Abdelghani90 try to reproduce and fix this.
