### ISSUE TITLE
Value set IDs don't sort nicely for numbers

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#514]
When the value set code is a number, they don't seem to sort properly. In the example below the values in the blue boxes interrupt the normal sequence of codes (9, 10, 11, 12, etc)

![image](https://cloud.githubusercontent.com/assets/17408249/17591934/e03ea74c-5fa5-11e6-9b93-cc98f3d85a61.png)

**Comment by haffonist** [comment]
@Jungyubw Is this fixed ?
