### ISSUE TITLE
add a comment for value set values

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#515]
Might be nice to have a comment column in the value set table. That way we could add individual comments to a given value. For example, in the CVX value set, some CVX codes will be P or E because they are either immunoglobulins (out of scope for the IG) or were never active - it would be nice to explain why a given CVX is P or E.

**Comment by haffonist** [comment]
I think this is a duplicate.

**Comment by Jungyubw** [comment]
Added
