### ISSUE TITLE
add an import option to the value set activity

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#516]
It would be great to have the ability to import a .csv (or some other sort of file) file to create or append to a value set. If there are lots of values to add, it's easier to do the work often in Excel and then import it. For example, the CVX table (HL70292) is missing 40 or 50 codes and it would be a lot easier to import them than to enter them one by one

**Comment by haffonist** [comment]
@csnewman88  Do you have an example of the csv file ?

**Comment by csnewman88** [comment]
I think you would need to define the file format for uploading value set. You could define what data elements you need (code, description, usage, etc) and then the author would have to match that format. As long as you keep it simple, it shouldn't be a problem.

**Comment by Jungyubw** [comment]
Done. Need QA
