### ISSUE TITLE
Missing segments when adding new message structure to IG

### ISSUE THREAD

**Issue by ncrouzier-nist** [haffonist/igamt#518]
I added multiple message structure to my IG and certain segements seem to be missing in the segment list and message structure (see ACK)

<img width="2499" alt="screen shot 2016-08-11 at 11 38 57 am" src="https://cloud.githubusercontent.com/assets/14352180/17594811/98e27c3a-5fb8-11e6-8b55-8ed39a9752e4.png">

**Comment by haffonist** [comment]
Not missing but a client side bug. What is your ig title and hl7 version ?
