### ISSUE TITLE
ACK message Structure Id "typo"

### ISSUE THREAD

**Issue by ncrouzier-nist** [haffonist/igamt#519]
The ACK message Structure Id has an extra underscore (probably due to it's "varies" option). Might want to remove that.

<img width="962" alt="screen shot 2016-08-11 at 11 43 41 am" src="https://cloud.githubusercontent.com/assets/14352180/17594947/14f74e5e-5fb9-11e6-9cd1-c27407b4435d.png">

**Comment by haffonist** [comment]
This is a know issue from the frank's DB that we put aside sometimes ago for lack of time. I think it is the right time to fix this. 
@IsmailMellouli let's talk about this during the week.
