### ISSUE TITLE
Support for external code systems

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#520]
Should we have external code systems available in IGAMT for profiling.
Should be be able to import like we do with PHINVADS?

Can we bring in certain subsets if the external code system supports this (via a web service, e.g.,). 

Need to discuss what we can do.

**Comment by haffonist** [comment]
Let's talk about this.

**Comment by robnist** [comment]
I was reading a little about how FHIR supports terminology servers; we could create a FHIR interface to bring the code systems into the IGAMT space and they could be profiled. Also, filter can be placed on the value set using FHIR, this in essence would also be profiling.

**Comment by Jungyubw** [comment]
Let's discuss about this ticket when Rob come back.

At this time, I will put this ticket at Pending.
