### ISSUE TITLE
need a way to avoid a condition predicate

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#521]
There are cases where a field is C in the base standard but we want to make it O in the IG. For example, look at RXA-12 or ORC-26. We can't just change the IG usage to O but we can make it C(O/O). the problem is that the CP editor requires a predicate. After talking to Rob Snelcik, what we need is a way to skip the predicate if the True and False usages are identical.

**Comment by Jungyubw** [comment]
This ticket is closed because to be merged to #492
