### ISSUE TITLE
have to click an icon to enter a new CS ID

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#522]
when adding a new CS, you can't just click in the box to enter the ID, you have to click on the pencil icon (blue box below) in order to activate the box. This seems unnecessary. The pencil (edit??) icon really only make sense once the CS exists.

![image](https://cloud.githubusercontent.com/assets/17408249/17595879/917df7fc-5fb4-11e6-9f31-2a2a754577c2.png)

**Comment by haffonist** [comment]
@Jungyubw This is part of the ux enhancements that need to be implemented. "The fewer the click the better". Please look into this.

**Comment by Jungyubw** [comment]
I will fix it later.

**Comment by Jungyubw** [comment]
Fixed.

I removed "duplicated ID" function for conformance statements. User can edit freely anything for conformance statement, even duplicate ID. 

Sometimes, user wants duplicated IDs for conformance statements in case of that there are multiple flavors.
