### ISSUE TITLE
show version in metadata

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#523]
It would be great see which version the IG is based on.  It could be shown in the meta data.  

Some of the metadata fields do not show on the cover and vice versa.

**Comment by haffonist** [comment]
@robsavage you mean the hl7 version the ig is based on, correct ?

**Comment by robsavage** [comment]
correct
thanks

Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039
