### ISSUE TITLE
CS needs an "if populated" option

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#524]
The immunization guide has the following existing CS:

IZ-30: If RXA-4 (Date time of admin end ) is populated, then it SHALL be the same as Start time (RXA-3) 

I can get close to replicating this, but I can't do the "if populated" part. Given that RXA-4 is optional, this is an important piece.

The value of RXA-4(Date/Time End of Administration) SHALL be equal to the value of RXA-3(Date/Time Start of Administration).

Also, does "equal" imply any sort of mathematical relationship or can it be applied to strings like a date/time?

**Comment by carolinerosin** [comment]
I was just reading your ticket - and it raised a questions in my mind : is there a difference between 
- "if present"
- "if populated"
- "if valued" 
?

@robnist ?

**Comment by csnewman88** [comment]
I don't think so, but we should be consistent in our verbage

**Comment by robnist** [comment]
We should only have one; I pushed for "valued" as the term to use. I know when used this in the initial set of conformance statements for v2 in the lab spec years ago. Not sure what has happened more recently. So IGAMT should only support "valued". Existing guides can use this even if other terms are used--the meaning of the conformance statement is not altered. This will keep everyone consistent. 

I also ponder if the qualifier should be used at all. The if is implied when married to usage. I know folks want to do this with O and RE, but it is not necessary. If RE is changed to R then you have to take care of changing the conformance statement. I can see arguments on both sides of this.

**Comment by carolinerosin** [comment]
So if there is no difference between populated and valued, I think IGAMT already has what you need to implement your conformance statement. I would just need to double check how the "equal" works for dates.

**Comment by Jungyubw** [comment]
Yes you can create "valued' and then may modify description if you want.

For "Equal", I need to check with Hossam.
I will let you know.
