### ISSUE TITLE
Value Sets in 2.8.2 have multiple copies 

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#527]
![capture](https://cloud.githubusercontent.com/assets/14874904/17606897/09df0246-5ff0-11e6-98c8-ab835e77690c.PNG)

I just created a new 2.8.2 IG and there are a number of USR value sets. Also, some are CDCREC, which I know Craig created but how did they end up in mind?

**Comment by haffonist** [comment]
@Abdelghani90 This is fixed right ?

**Comment by Abdelghani90** [comment]
@haffonist  It was a data problem. It should be fixed with the new database.
