### ISSUE TITLE
Usage and Cardinality Checks on Segment

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#530]
Performs checks and change automatically.

e.g., R --> min must be 1 

When O changed to R, then change cardinality

When cardinality is changed and usage doesn't match then highlight RED in cases where it can't be determined, for example, 0..1 can be O or RE.

**Comment by haffonist** [comment]
@Abdelghani90 what is the estimate on this. If you are not working on this right now please move from In Progress.

Thanks
