### ISSUE TITLE
To many clicks to clone and bind value sets

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#531]
Provide feature to right click on value set edit/binding in data element to Create Clone and also Create Clone and Bind. Then go to the base value set. Once profiled and saved, if the latter is selected, then it is automatically bound to element.

Also, when you select a value set to view, add a button to create clone in this panel; this is more convenient then going back to the navigation and doing it there (however, still keep this feature).

**Comment by haffonist** [comment]
This is a bulk replacement. The selection should be in the cross-reference panel for datatype, segment and value sets.

**Comment by Jungyubw** [comment]
@IsmailMellouli Let's discuss about this issue after tomorrow standup meeting.

**Comment by Jungyubw** [comment]
Done.
