### ISSUE TITLE
adding multiple values in a value set causes focus issues

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#532]
This one is a bit odd.

Create a value set and click the "Add Value" several times so that you get multiple blank values:
![image](https://cloud.githubusercontent.com/assets/17408249/17625053/c0bc3b88-606c-11e6-8d21-d9762f1ec865.png)

If you click in one of the fields, and start typing, only the first character is recorded (no matter how many you enter) and you have to reclick in the field to restore the cursor and keep typing
![image](https://cloud.githubusercontent.com/assets/17408249/17625095/eee21014-606c-11e6-883e-315c5c45382f.png)

**Comment by Jungyubw** [comment]
Fixed
