### ISSUE TITLE
Search for PHINVADS value set doesn't seem to work

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#534]
I can't figure out how to find PHINVADS value sets. No matter what I search for, I can't find any value sets. For example, I need to create a value set for these values:

Value Set Name – Funding Eligibility Observation Method (IIS) 
Value Set OID - 2.16.840.1.114222.4.11.6039
Value Set Code: PHVS_FundingEligibilityObsMethod_IIS
Value set definition: The Funding Eligibility Observation Method identifies the method for capturing funding program eligibility. Note that it is always reported at the immunization level. Used in OBX- 17

Concept Names	Concept code	Code System Identifier – HL7 Table 0396
Eligibility captured at the immunization level	VXC40	CDCPHINVS
Eligibility captured at the visit level	VXC41	CDCPHINVS

But no matter what I search, I can't find anything. Am I doing something wrong?

![image](https://cloud.githubusercontent.com/assets/17408249/17625660/6acf4028-606f-11e6-87b6-e943c6cb2e52.png)

**Comment by haffonist** [comment]
@Jungyubw this is marked urgent. Please fix as soon as possible

**Comment by Jungyubw** [comment]
I think you confused by ugly UI. I improved it.
