### ISSUE TITLE
Co-constraints table Description and Comments are hard to work with

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#536]
If you're trying to add a Description or Comment to a Co-constraints table, it's hard to work with if the text is of any significant length. It may be better to use the same expandable text box as the Text Description in the segment table itself.

![image](https://cloud.githubusercontent.com/assets/17408249/17625915/97998ce8-6070-11e6-858f-590aa1374d99.png)

**Comment by Jungyubw** [comment]
Done
