### ISSUE TITLE
empty co-constraints table column

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#537]
What should we do if a table in a co-constraints table doesn't have a value. For example, in the co-constraints table for OBX, only a single value uses OBX-17 (eligibility), for other values (such as VIS or funding source) do we just leave it blank or would it be better to have an option to include "n/a" or something to more explicitly indicate that there is no value/value set to use?

![image](https://cloud.githubusercontent.com/assets/17408249/17626208/e1c2886e-6071-11e6-99ab-123ef7237c9c.png)

**Comment by Jungyubw** [comment]
Done
