### ISSUE TITLE
Conformance Statement at the profile level not published

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#539]
When exporting to a Word document, it appears that the profile level Conformance Statements are not included in the document anywhere.

![image](https://cloud.githubusercontent.com/assets/17408249/17630849/db85e968-6086-11e6-9818-0b3465c962f1.png)

**Comment by Abdelghani90** [comment]
@olivier-m-mr  @maxence-lefort @haffo 
We have the same code why it works only for word?

**Comment by olivier-m-mr** [comment]
The docx export and the html export are based on the same principle.
The first step consists in gathering the data from the model (and therefore the db) and the second step deals with the formatting and rendering. 
That being said, while we retrieve the entire IG for the html, we do it by steps for the docx (first the sections, then the message, then segments...; when doing the messages we go through the segment refs and the groups then the constraints etc).
I would check the serializer to verify that the data are fetched. I would then checked the stylesheet that does the html formatting and rendering. 
side note: I think we saw that it was there but it was not rendered the same way as the segments and datatypes constraints

**Comment by Abdelghani90** [comment]
I know that ;) 
The serializer is ok. because it works for word. 
I have added the same code we use in the xsl of the word document and it works for datatypes and segments .. 
I Think there is something you that makes them disappear especially for the profile level.
Please stop by or try to fix it.

**Comment by olivier-m-mr** [comment]
Can you send me a serialized IG document with the profile level constraints and the stylesheet please? I'll run the transformation on my computer. 
To generate the serialized IG, you can either add a breakpoint after the serialization and copy the string to a text file or replace temporarily the TempFile by a File.

**Comment by Abdelghani90** [comment]
you can test with any IG document. It is not specific to one IG
