### ISSUE TITLE
font size seems really big

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#540]
In the exported Word document, the font seems larger than is necessary. it seems to default to 12 point font, but I think switching to 10 point (see red box below) would be fine and help make the tables look nicer (in terms of column widths and line wrapping) and would save a little space

![image](https://cloud.githubusercontent.com/assets/17408249/17630960/818ea2a0-6087-11e6-9c1b-512caccd842a.png)

**Comment by maxence-lefort** [comment]
Fixed. See pull request #777
