### ISSUE TITLE
extra space in the segment definition text

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#541]
The header for the Definition Text after the segment table has an extra space in the data type text. There is a space between the forward parenthesis "(" and the data type (see red arrows below).

Also, there seems to be a lot of white space between fields too. If that can be reduced, it will help the overall  size of the document

![image](https://cloud.githubusercontent.com/assets/17408249/17631047/f990648c-6087-11e6-8b58-a19f0fe76f12.png)

**Comment by maxence-lefort** [comment]
@olivier-m-mr can you please confirm that this was fixed?
