### ISSUE TITLE
lengths of 0 for complex data type fields

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#545]
I think IGAMT will confuse authors and readers because it lists the lengths of fields using complex data types as 0..0

I know the data types define their own lengths, but I think it's confusing that a field can be R and have a length of 0..0

I think it's appropriate for X elements but not R, RE, C or even O. I know you can't put values in there, but I think "blank" is better that 0..0

![image](https://cloud.githubusercontent.com/assets/17408249/17632220/d47f1710-608c-11e6-9c95-50a787d36856.png)

**Comment by haffonist** [comment]
implemented and available at next deployment. Word/HTML still need to be updated.
