### ISSUE TITLE
triggering of the "save" button is inconsistent

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#547]
If you open an existing user defined segment and just update an existing Definition Text, it doesn't activate the "save" button. You have to go and edit something else to be able to save the change. However, if you try to move away from the segment to a new one, you do get the "confirmation" pop up to save or discard the changes so it's not clear if you need to save the change to get it to persist. Either way, either the Save button needs to light up or the confirmation box needs to go away so it consistently reflects what has to happen for the text change to persist

**Comment by haffonist** [comment]
@csnewman88 I believe the save button does activate, it is just not obvious that it is activated. We will make it more obvious as suggested. 

Thanks

**Comment by csnewman88** [comment]
I'm pretty sure it isn't activate. Or if it is, it doesn't give the same confirmation message you click on it.
