### ISSUE TITLE
Definition Text tables don't represent well in the Word document

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#548]
Tables built in the Definition Text doesn't seem to be exported the same. In the example below, the Component Name column seems too narrow in the Word document and none of the table borders are there making it tough to read.

![image](https://cloud.githubusercontent.com/assets/17408249/17633166/8fd93780-6091-11e6-827f-6a6806926429.png)

![image](https://cloud.githubusercontent.com/assets/17408249/17633142/7a4697b4-6091-11e6-9b6c-2b80153a2d6c.png)

**Comment by haffonist** [comment]
@olivier-m-mr I thought this was fixed, please fix.

**Comment by Abdelghani90** [comment]
@haffonist  @olivier-m-mr  fixed and need to QI
