### ISSUE TITLE
column order

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#549]
The order of columns in segment and data type fields is different. Ideally they would be the same. In particular, I don't like that the Length and Conf length columns are spatially separated

![image](https://cloud.githubusercontent.com/assets/17408249/17633354/800d342c-6092-11e6-9a7d-6f855387d96b.png)

![image](https://cloud.githubusercontent.com/assets/17408249/17633337/66cdcac6-6092-11e6-8212-758eaa79f548.png)

**Comment by haffonist** [comment]
@olivier-m-mr please fix this.
