### ISSUE TITLE
name change on cloned segment fails

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#550]
I created a clone of Z42, renamed, saved, got successful save message, but title in left hand box does not change.  Repeated 4 times
[profile name change.pdf](https://github.com/haffonist/igamt/files/418277/profile.name.change.pdf)

**Comment by robsavage** [comment]
Edited the segment, added new version of OBX, deleted segment and group, saved, got success pop-up, but segment  NOT saved

**Comment by robsavage** [comment]
closed igamt, reopened, and tried to change name again.  success this time.  AND OBX correctly listed, in spite of no changes this time around on my part.

Very strange.

**Comment by robsavage** [comment]
the name down the side shows the new name of segment, but there is still a link to it. when I tried to delete the MSH that was copied and replaced for the message. I got the can't delete, still linked message.
[4 broken link to segment.pdf](https://github.com/haffonist/igamt/files/420292/4.broken.link.to.segment.pdf)

**Comment by robsavage** [comment]
does this relate to WORD problem?

**Comment by haffonist** [comment]
@Abdelghani90 please look into this.
