### ISSUE TITLE
MSH delete prevented

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#551]
I cloned an MSH and renamed. I linked that MSH to a cloned segment (one that did not allow rename when cloned and edited). tried to delete the old MSH and got the can't delete because still linked.

[delete old msh.pdf](https://github.com/haffonist/igamt/files/418308/delete.old.msh.pdf)

**Comment by robsavage** [comment]
could this relate to the word problem?

**Comment by haffonist** [comment]
per our discussion on 08/17/16 this is  fixed
