### ISSUE TITLE
Images cannot be resized

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#552]
I've inserted a couple of images into a text box and I can't resize them either within IGAMT itself or by resizing them in another program and saving the larger image. Plus when I export to a Word document the images are missing.

**Comment by haffonist** [comment]
I will add back the resizing feature but note at this point the size will have no effect on the word document. As agree upon, the user will need edit the images in the word.

**Comment by haffonist** [comment]
Resizing is added brack.
