### ISSUE TITLE
sections not all being exported

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#553]
I'm working on the Use Case section of my IG. I've moved a few sections around and deleted a couple, but now, not all of the sections that in IGAMT are in the exported documents (Word or HTML). For example, the red arrow below highlights the "scenarios" section (I think that was an original section that came with the template) but it's not in the HTML output.

![image](https://cloud.githubusercontent.com/assets/17408249/17676315/a27bd352-62f3-11e6-9842-0cd4f10181dd.png)

![image](https://cloud.githubusercontent.com/assets/17408249/17676378/e3d61d3a-62f3-11e6-8eff-e16dac18cd96.png)

**Comment by haffonist** [comment]
@maxence-lefort, @Abdelghani90 Any update on this ?

**Comment by Abdelghani90** [comment]
This seems to be fixed.
