### ISSUE TITLE
Changes to value sets are not being kept

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#561]
I know for a fact, that I deleted a bunch of value sets for optional fields (blue box below) and updated a bunch of value sets to user defined ones (red box below). Yet, they are now back to the original default value sets. Bad IGAMT, bad.

![image](https://cloud.githubusercontent.com/assets/17408249/17748412/e329cf58-647e-11e6-8ffc-975298554bd4.png)

**Comment by haffonist** [comment]
Can you please check with the new deployment of 08/17 ?

**Comment by csnewman88** [comment]
I just updated the PID segment in my 2.8.2 IG (see below). I'll close out and check it later and see if it's still all there.

![image](https://cloud.githubusercontent.com/assets/17408249/17809355/9a66daa0-65db-11e6-85cc-9fc48fc775f8.png)

**Comment by haffonist** [comment]
ok. please let us know. Most issues we are currently facing is with the data itself and we write codes to fix the data but sometimes(shamefully) it creates other issues. 
Sorry for the inconvenience.

**Comment by haffonist** [comment]
This is fixed I believe.
