### ISSUE TITLE
description text truncated

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#562]
One of the description texts is being truncated in the Word export

![image](https://cloud.githubusercontent.com/assets/17408249/17749184/4069fabe-6482-11e6-9b89-248bd1afb25f.png)

![image](https://cloud.githubusercontent.com/assets/17408249/17749167/32e59826-6482-11e6-975c-428c77fee95d.png)

**Comment by haffonist** [comment]
Here is the html representation of the content. Notice the . This is what is stopping the process. May be this was copied from word.  

<p>This field identifies whether a person&#39;s information may be shared with others(
	****

**Comment by haffonist** [comment]
I removed `<!--[if !supportFootnotes]-->` from the content. It should work now.
