### ISSUE TITLE
need "not valued" option in predicate editor

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#563]
We need a "not valued" option in the Constraint Pattern list of the predicate editor so that we can do things like RXA-5.1 is not valued "998"

![image](https://cloud.githubusercontent.com/assets/17408249/17749583/e4484d74-6483-11e6-9e62-eaa8847595bf.png)

**Comment by Jungyubw** [comment]
@csnewman88 

in your case, 
RXA-5.1 is not valued "998"

we can represent this predicate to select 'is not' for a verb and select 'a literal value' for a pattern and type '998' for a value.

Then the tool create predicate:

- Desc: If the value of RXA-5.1(Identifier) is not '998'.
- Assertion: <Condition><NOT><PlainText Path="1[1]" Text="998" IgnoreCase="false"/></NOT></Condition>

Is it what you want?

Thanks.

**Comment by Jungyubw** [comment]
Of course, you can edit the Description if you want.

**Comment by csnewman88** [comment]
That should work. Thanks
