### ISSUE TITLE
order of value sets makes life difficult

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#564]
In the co-constraints table, when specifying a value set to use, it lists the value set ID (usually just a number) but not the name. Yet the name is possibly sorted by name alphabetically. This makes it very hard to find the value set you want because the numbers aren't in order and you can't see the names.

![image](https://cloud.githubusercontent.com/assets/17408249/17782101/9e59219e-6537-11e6-94a7-f726ed07680f.png)

**Comment by haffonist** [comment]
add name as well.

**Comment by Jungyubw** [comment]
Done.
