### ISSUE TITLE
data type creation error

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#565]
I added data type to new IG, CX. clicked save and got the attached screen.  note weird thing in list.
[9 data type.pdf](https://github.com/haffonist/igamt/files/425691/9.data.type.pdf)

Note I am in an empty add box.

**Comment by robsavage** [comment]
I tried again and find that the list does not contain CX data type.  The screen shot shows the entire list of available data types to add. If I type in CX, it goes to the empty screen in the previous comment.

[8 missing data type.pdf](https://github.com/haffonist/igamt/files/425718/8.missing.data.type.pdf)

**Comment by haffonist** [comment]
This feature is to import only HL7 DT and not user's DTs.


________________________________

**Comment by robsavage** [comment]
CX is HL7 data type in 2.5.1

2.A.1            <> <> <> <> <> <> <> <> <> <> <> <> <> <> <> <> <>CX - extended composite ID with check digit <>
HL7 Component Table - CX – Extended Composite ID with Check Digit <>
SEQ

LEN

DT

OPT

TBL#

COMPONENT NAME

COMMENTS

SEC.REF.

1

15

ST

R

 

ID Number

 

2.A.74

2

1

ST

O

 

Check Digit

 

2.A.74

3

3

ID

O

0061

Check Digit Scheme

 

2.A.35

4

227

HD

O

0363

Assigning Authority

 

2.A.33

5

5

ID

O

0203

Identifier Type Code

 

2.A.35

6

227

HD

O

 

Assigning Facility

 

2.A.33

7

8

DT

O

 

Effective Date

 

2.A.21

8

8

DT

O

 

Expiration Date

 

2.A.21

9

705

CWE

O

 

Assigning Jurisdiction

 

2.A.13

10

705

CWE

O

 

Assigning Agency or Department

 

2.A.13

Definition: This data type is used for specifying an identifier with its associated administrative detail.

Maximum Length: 1913

 

Note:  The check digit and check digit scheme are null if ID is alphanumeric.

Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by haffonist** [comment]
Ok.
CX is not showing for some reason even though it is in the ig document. 
What is the name of your ig document ?

Harold

**Comment by robsavage** [comment]
hl7 v2.5.1 Implementation guide for requesting an official immunization history

Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039
