### ISSUE TITLE
CS needs a "positive integer" option

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#566]
The list of Constraint Patterns in the Conformance Statement editor needs to have an option of "a positive integer". For example, the CQ data type is used to indicate the number of query response records to return. IZ-1 current constrains CQ.1 to be "a positive integer". We can't replicate that with current functionality. We can do "greater than or equal to 1" but that's not quite the same and does exclude things like 1.5 which just doesn't make sense.

**Comment by Jungyubw** [comment]
Added "Positive Integer" pattern in "Formatted Value"
