### ISSUE TITLE
The "Binding Location" attribute missing from IGAMT XML profile

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#568]
I am getting a “The binding location is missing” in the Viral Records validation.  The IGAMT profile is not specifying the correct binding. 
This is happening in all the segments using the HD data type. 

It looks like the VR profiles are missing the a Binding Location.

VR profile: <Field Name="Sending Application" Usage="R" Datatype="HD_VR" MinLength="1"
                MaxLength="227" ConfLength="1" Binding="0361" Min="1" Max="1" ItemNo="00003"/>

IZ-Profile: <Field Name="Sending Application" Usage="RE" Min="0" Max="1" Datatype="HD_IZ" MinLength="1" MaxLength="227" Binding="HL70361_IZ" BindingStrength="R" BindingLocation="1" ItemNo="00003"/>

**Comment by Jungyubw** [comment]
Fixed
