### ISSUE TITLE
Possible Encoding issue on Conformance Statement

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#570]
I am getting an error coming from a CS, VR-29 - The value of MSH-9(Message Type) SHALL be 'ADT^A04^ATD_A01'. I have the exact value in the message, an error should not be generated.
Hossam indicated that this might be due to an encoding issue, coming from TCAMT or IGAMT.

**Comment by Jungyubw** [comment]
@smartinez290  I created new profiles and checked the constraints, but I could not find any issue.
If you have the issue still, let me know.
