### ISSUE TITLE
duplication of document sections

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#573]
I was reviewing the document and found that sections that I had added as subsections we duplicated as sections below with the same name.  When I click on the subsection, the section is also highlighted.

[3 duplication of sections.pdf](https://github.com/haffonist/igamt/files/436982/3.duplication.of.sections.pdf)

**Comment by Abdelghani90** [comment]
@robsavage this may happen if those section were created a long time ago, before we fixed some issues. Please create a new copy and delete the old. 
Thanks,

**Comment by robsavage** [comment]
I created on Tuesday 8/23.
R
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by Abdelghani90** [comment]
Thank you, we will fix that

**Comment by robsavage** [comment]
I deleted the duplicate sections and the numbering on the messaging infrastructure renumbered to correct number.


Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039
