### ISSUE TITLE
section is misnomered

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#574]
The section #11 is misnumbered and has a different font.
[1 section missnumbered.pdf](https://github.com/haffonist/igamt/files/437100/1.section.missnumbered.pdf)

**Comment by Abdelghani90** [comment]
@haffonist  Do you have this problem?

**Comment by Abdelghani90** [comment]
@robsavage can you tell us the actions you did before having this problem ?

**Comment by robsavage** [comment]
Tuesday, I created this IG from scratch. I rearranged a number of sections and removed a few sections.I saved each time and exported after each save.  Interestingly, it numbers correctly in WORD export.
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by robsavage** [comment]
I forgot to add that this is a clone of Tuesday’s IG and it is misnumbered in the original as well

Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by haffonist** [comment]
fixed
