### ISSUE TITLE
Issue saving a profile

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#575]
Copied a profile, changed name and segment definition. Click on "Save", the name is not updated in the table of content. I have to do a re-fresh every time. Also, the tool is super slow.

**Comment by Abdelghani90** [comment]
@smartinez290  we have already fixed that, but we haven't deployed it yet.
For now you can just save and refresh after you clone and it will work.
Thanks

**Comment by haffonist** [comment]
Send only the meta data.
