### ISSUE TITLE
confirmation window could use more detail

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#576]
When you go to delete an IG, you get the confirmation popup window double checking that you want to go through with it. It is great to ask for confirmation, but it would be even more helpful if the popup window message contained the name of the document being deleted. For example, in the screenshot below, you can't read the message and confirm whether it's the OML or "work test try 2" document that will be deleted. For paranoid people like me, the fact that it's irreversible makes us reluctant to click the "delete" button without knowing exactly what will happen (did we screw up at an earlier step and are we going to permanently delete something we want to keep??).

![image](https://cloud.githubusercontent.com/assets/17408249/18056127/4782737e-6dd0-11e6-8408-ed2d40f257f6.png)

**Comment by robsavage** [comment]
amen!!
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by haffonist** [comment]
ok.We will add this.


________________________________

**Comment by haffonist** [comment]
@IsmailMellouli please implement this next.
