### ISSUE TITLE
When creating custom fields, the data type should not be restricted

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#580]
When editing a segment record, the list of possible data types is constrained to a list of related data types (all HD flavors or all DTM flavors for example). This makes a lot of sense for standard segments and fields where you don't want the author to redefine the data type of a field that is specified by the base standard. However, it would be nice to have an exception to this constraint for custom created fields. Because these don't exist in the base standard, the author should be allowed more latitude in defining the data type and be able to change it more dramatically (such as from ID to CWE). Typically, this would need to be done if the author makes a mistake when creating the field. There is a work around of deleting the field and recreating it, but that is extra work for the author.

![image](https://cloud.githubusercontent.com/assets/17408249/18061890/1cd1aaf4-6dea-11e6-8627-0417d80c0b54.png)

**Comment by robnist** [comment]
I agree. 
The solution is to include "Other" in the dropdown. In 99% of the time the user will select a DT with the same root, so we only want to show those possibilities without clutter. The "Other" option will allow them to select from all of the DTs in a dialog or similar utility.

**Comment by robsavage** [comment]
Craig
You might want to drop these two fields from query. Not sure anyone is using them.  Only Alean wanted them.

Cheers
R
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039
