### ISSUE TITLE
Inappropriate value set association possibilities

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#582]
When creating custom fields for a segment (such as QPD), the segment editor will allow the author to associate value sets with some inappropriate data types. In the example below, you can add a value set to NM_01 and DTM_01 (purple box) but not DTM (red box). The latter is appropriate, the former are inappropriate. The tool should only allow value sets to be associated with logical data types (and their related flavors).

![image](https://cloud.githubusercontent.com/assets/17408249/18062672/6f32258c-6ded-11e6-825a-ca1f0c5b1629.png)

**Comment by haffonist** [comment]
Only IS, ID, CWE, CNE and CE  should allow binding of value sets.
We will fix client to only allow for those datatypes. But how de we handle the existing data ?
