### ISSUE TITLE
problems with sections continue

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#607]
I opened the recovered IG and found the duplication of sections. I deleted duplicate sections and closed.  When I reopened, the duplicates were back.  Also note that the sections are misnumbered in both attached screen shots.
[2 duplicate sections.pdf](https://github.com/haffonist/igamt/files/449654/2.duplicate.sections.pdf)
[1 duplicate sections.pdf](https://github.com/haffonist/igamt/files/449655/1.duplicate.sections.pdf)

**Comment by robsavage** [comment]
[HL7-V2.7.1-Implementation-Guide----Get-Official-Immunization-History-Document-II-20160901_100447.docx](https://github.com/haffonist/igamt/files/449844/HL7-V2.7.1-Implementation-Guide----Get-Official-Immunization-History-Document-II-20160901_100447.docx)
Note in the index that the duplicate sections are see and that the subsections under 2.2.3 are not seen.  They are the sections that are duplicated in the 3-6 sections.  I wonder if database is corrupted.

**Comment by Abdelghani90** [comment]
@haffonist @robsavage I need to see this IG. Because I still cannot trigger the problem.

**Comment by robsavage** [comment]
how can I share?

want to login as me?

Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by Abdelghani90** [comment]
You don't need to, I got it. 
I will fix that as soon as possible. 
Sorry for that. 
Thanks

**Comment by robsavage** [comment]
fixed
thanks
