### ISSUE TITLE
include profile Identifier in the table of contents

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#609]
At least for immunizations, we use the profile Identifier (Z22, Z34, etc) a lot and so it would be nice if that were included in the profile name (red box) in the table of contents (probably before the Profile Description so that it is always visible no matter how long the description is.

![image](https://cloud.githubusercontent.com/assets/17408249/18169921/e0b76254-7021-11e6-834b-0852a169f37a.png)

**Comment by Abdelghani90** [comment]
@IsmailMellouli has already fixed that
