### ISSUE TITLE
another issue with sections

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#610]
See attached. 
[2 missing section.pdf](https://github.com/haffonist/igamt/files/449916/2.missing.section.pdf)

I tried copying the same block into a different section without problem saving.

**Comment by haffonist** [comment]
The tool is behaving that way before of the special character found in the word document.  
When copying from word to the tool, I recommend you paste into a simple editor such as notepad and show the special characters before pasting into the tool.
