### ISSUE TITLE
profile contents don't show

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#613]
I have added some data types, made flavors of data types and segments.  I have been adding fields to QPD query parameters. After making a flavor of XTN, I went back to QPD_xxx and got a blank edit box and spinning circle of dots.

[6 empty edit area.pdf](https://github.com/haffonist/igamt/files/450359/6.empty.edit.area.pdf)

**Comment by haffonist** [comment]
What happened when you close and open again the document ?

**Comment by robsavage** [comment]
still empty with spinning ball.
R
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by robsavage** [comment]
Occurred again. I was editing the RSP. I tried to add OBX to response group.  Nothing happened.  Tried to delete response group.  Got green deleted notice, but the dialog box for deletion remained. So did the response group. Tried to delete the "any segment" segment. Got green notice but did not delete. Closed IG and reopened.  When I went to RSP, got the empty screen and the spinning ball again.  Is this because of data base error and failing to find the elements needed to build the screen?

**Comment by robsavage** [comment]
I can't open either QBP or RSP in my current profile.  I can open ACK.  Is anyone looking into this?

**Comment by haffonist** [comment]
Rob, on safari click on Develop > Show Error Console (See attached screenshot) and copy and paste the red text you see. It will help us better debug this issue since nobody else is having this. 

![screen shot 2016-09-07 at 11 44 07 am](https://cloud.githubusercontent.com/assets/13695248/18318657/8753be78-74f0-11e6-8d6d-dcec94c975cd.png)

**Comment by robsavage** [comment]
here you go






Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by haffonist** [comment]
sorry, nothing is pasted.

**Comment by robsavage** [comment]
It was attached as PDF document


Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by haffonist** [comment]
There is no pdf attached. Can you attach directly to the github ticket ? May be that will work.

**Comment by robsavage** [comment]
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by haffonist** [comment]
Rob,
How are you attaching the file ? I am not seeing anything attached.

**Comment by haffonist** [comment]
I think the just deployed version might have solve that issue. Please give it a try and let me know.  

Thanks

**Comment by haffonist** [comment]
It is data issue. Can't find DT datatype in the ig document. Any idea on your end how this might have happened ? I can fix this by adding the DT back to the ig document.

**Comment by robsavage** [comment]
no idea.  I created from scratch with QBP, RSP and later added ACK. It does appear that not all data types import.  For example, the SAD was missing, though I think the XAD, which uses it was not when I started. It did not show in the XAD data type until I added it. If I remember, only DTM was present when I started.

Thanks
Rob
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by haffonist** [comment]
ok, I am working on fixing this. A temporary solution is  that you add DT.


Harold


________________________________

**Comment by robsavage** [comment]
just did
but still getting spinning ball
I will play a bit to see what else is missing.

Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by robsavage** [comment]
does it matter that when I add fields to a segment (QPD, for example) the conformance length is empty?


Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by haffonist** [comment]
conf length is currently optional.

________________________________

**Comment by robsavage** [comment]
interestingly, I tried to enter -1 in the empty conf length field. It failed to save.


Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039
