### ISSUE TITLE
add value set process causes lockup

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#624]
I was trying to add a value set.  selected import. selected version 2.7.1.  Locked application with spinning ball.  I had been working in QPD segment, right clicked the value sets to add value set.  I am pretty sure I had saved before I did this.  I got Server Error message.
[1 add table.pdf](https://github.com/haffonist/igamt/files/452363/1.add.table.pdf)

**Comment by haffonist** [comment]
@robsavage is this fixed for you ?

**Comment by robsavage** [comment]
looks fixed to me
