### ISSUE TITLE
table import from .csv has some issues

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#635]
When I loaded a value set from a .csv file, it shows up in the value set list (red box below), but when I click on it I get an error saying "Cannot find the table specified" (black arrow below). Plus the CodeSystem values are not populated.
![image](https://cloud.githubusercontent.com/assets/17408249/18350931/c315f3ec-759d-11e6-8333-8816f3eaaf4f.png)

The codeSystem not being populated probably has to do with code system not populated on the MetaData tab. 

I updated the MetaData (coding system, open/closed, etc) but when I clicked on "save" nothing happened. When I tried to navigate away from the table I go the usual warning about unsaved data. Even when I said to save and move away, nothing seemed to happen. 

Plus, it doesn't seem to be possible to delete the table. When I try, I get the same "cannot find the table specified" error.

So in general, the table appears to load but doesn't behave like it is a real table

**Comment by csnewman88** [comment]
Note that when I close the IG and open it back up, the table is no longer there

**Comment by robsavage** [comment]
I have occasionally experienced similar behavior, but haven’t dealt with data set imports.

Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by Healthedata1** [comment]
My csv table saved once but displayed twice.   Also that last line was empty in the csv but the tool recognized it as populated complained about the lack of code system.  
Other things:

-  the button are too small and subtle   make em big like they are here on GIST.

![image](https://cloud.githubusercontent.com/assets/7410922/18354201/92da07a8-7599-11e6-8c93-d0bbf3f65771.png)

**Comment by haffonist** [comment]
Woo,

i know you are dedicated for TCAMT this week and the next. But this is critical issue and in such situation we will have to fix this ASAP.



________________________________

**Comment by Jungyubw** [comment]
Sorry for inconvenience. It is critical issue. I will look at it as soon as possible.
I will fix it by today.

**Comment by Jungyubw** [comment]
@csnewman88 
Could you send me the CSV file that you used?

Thanks.

**Comment by Jungyubw** [comment]
Fixed.
