### ISSUE TITLE
Need more feedback when uploading a .csv file for table imports

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#636]
After a user chooses a .csv file to import, there should be some indication that it was successful (like put the file name in the pop up window or have the "save" button only light up after a file has been selected). As it is now, there is no way for the user to be confident the right file will be used.

![image](https://cloud.githubusercontent.com/assets/17408249/18351564/4df4326a-75a0-11e6-9b62-15030d402f95.png)

**Comment by csnewman88** [comment]
Similarly, if the user clicks "Save" without having first selected a file to upload, nothing happens other than the button turning a darker shade of blue. There should be something indicating that a file has not been selected, so there is nothing to save/import

**Comment by haffonist** [comment]
@Jungyubw please fix.

**Comment by Jungyubw** [comment]
I will fix.

**Comment by Jungyubw** [comment]
Now, the tool shows warning when the file is empty. 

Of course, we need to validate CSV file. I have created new ticket for CSV validation. I will do it later.

**Comment by Jungyubw** [comment]
#641 ticket has been created for CSV validation functionality.

**Comment by haffonist** [comment]
When upload is successful, we should close the dialog and load the new value set. If it is not successful we need to show error in the dialog to the user.

**Comment by Jungyubw** [comment]
Done
