### ISSUE TITLE
display has some quirks

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#637]
I opened up the RXA segment and the display is all wonky. The "definition pre-text" is off, there are no column headers and the gridlines aren't synced up with the content.

![image](https://cloud.githubusercontent.com/assets/17408249/18352634/c9e9ff90-75a4-11e6-8fce-48285398dde2.png)

**Comment by haffonist** [comment]
Yes, had did too. After updating my chrome no more issue. I haven't seen this on other browser though.
