### ISSUE TITLE
still seeing an error when searching for a PHINVADS value set

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#639]
![image](https://cloud.githubusercontent.com/assets/17408249/18358748/40c6cbea-75bc-11e6-9b9f-ed29efe1842e.png)

**Comment by haffonist** [comment]
@Jungyubw, Is this on PHINVADS's end or our end ?

**Comment by Jungyubw** [comment]
"Import PHINVADs" function is using PHINVADs(External)  web service. Unfortunately it is not unstable sometime.
I have just tried to check this, but it is working correctly. (Criteria is 'm', then not found. No error.)

We cannot handle PHINVADs web service so we will gather all of PHINVADs value set in our server.
It is new feature planned. I think we will provide this by next milestone.

Thanks.

**Comment by haffonist** [comment]
@Jungyubw fixed, correct ?
