### ISSUE TITLE
Value sets missing

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#640]
I'm pretty sure I created separate Race and Ethnic Group value sets from CDCREC (CDCREC_01 and CDCREC_02 respectively). CDCREC_01 seems to be missing (purple box below) and PID-10 doesn't list the CDCREC_01 value set until you click on the pencil icon (red box) (which exists even though there is no value set listed in the table) at which point CDCREC_01 is now listed in the pop up (green box). 

I'm less concerned about losing the CDCREC_01 value set (although losing value sets is never good), but it's not good that the reference to CDCREC_01 wasn't cleaned up when the value set disappeared.

![image](https://cloud.githubusercontent.com/assets/17408249/18359805/23f7ac96-75c1-11e6-84d0-88e7aaf152f4.png)

**Comment by csnewman88** [comment]
PS - I also lost the 0001_01 value set for PID-8

![image](https://cloud.githubusercontent.com/assets/17408249/18359889/7a92533a-75c1-11e6-975d-9bdd02e43e80.png)

**Comment by haffonist** [comment]
No it is not lost. Just wait for us to redeploy the tool this afternoon and it should be there. Yesterday we didn't update the data as planned as another issue came up.


Harold


________________________________

**Comment by csnewman88** [comment]
sounds good. Thanks

**Comment by haffonist** [comment]
@csnewman88 Is this fixed for you ?

**Comment by csnewman88** [comment]
Nope. Still missing a few value sets (0001_01 and CDCREC_01) and the PID segment still defaults to the base tables. Do I need to go and recreate these?

![image](https://cloud.githubusercontent.com/assets/17408249/18879126/cb2b89c0-8498-11e6-8dda-156aa5f2b6d9.png)

**Comment by haffonist** [comment]
Yes please recreate. We really can't find the cause of this issue.  So we have to handle this case by case.


Thanks


Harold


________________________________
