### ISSUE TITLE
Can't add segment to profile

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#644]
I tried to add a segment to RSP. (OBX) The search does not find the existing OBX segment. I had added that segment to the list of segments earlier.

[11 ADD OBX.pdf](https://github.com/haffonist/igamt/files/467336/11.ADD.OBX.pdf)

**Comment by csnewman88** [comment]
I have the same problem

![image](https://cloud.githubusercontent.com/assets/17408249/18447463/5c6500fa-78ec-11e6-92ad-1d7c6493b401.png)

**Comment by haffonist** [comment]
This will be fixed on the next deployment which is tomorrow afternoon.

Thanks

**Comment by robsavage** [comment]
I suspect that it has not been released.  problem persists
Thanks
R
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by haffonist** [comment]
This is fixed now.



________________________________
