### ISSUE TITLE
Adding segments to a segment group

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#645]
It's not obvious (maybe not possible) to add a new segment to an existing segment group. I added a new group and then went to add a segment to it, but wasn't sure how to select the "Position". In the example below, if I select a position of 9, will it put it under the Patient Identifier List group or will it put it in the main part of the message just above the DSC segment?

![image](https://cloud.githubusercontent.com/assets/17408249/18447598/f32a114c-78ec-11e6-8dc7-811d9794ed02.png)

![image](https://cloud.githubusercontent.com/assets/17408249/18447535/b30073ae-78ec-11e6-9ff4-2aa9abee3f0a.png)

**Comment by haffonist** [comment]
it will put it under Patient Identifier List. DSC will become 10.

**Comment by haffonist** [comment]
The feature is there, not perfect though. Right click the name of the group and select the options.
