### ISSUE TITLE
new problem adding segment

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#652]
[22 add seg.pdf](https://github.com/haffonist/igamt/files/474852/22.add.seg.pdf)

**Comment by haffonist** [comment]
Can't reproduce. So the issue happens when you hit ENTER ?  Same issue when you click on ADD button ?

**Comment by robsavage** [comment]
only when I hit add
I fill and hit enter, it sticks
I complete form and hit add and it disappears. and you can’t add.
If I cancel and try to return, I get the weird numbering. If i close IG and reopen, numbering back to normal (with big gap between 7 and 8).
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by haffonist** [comment]
ENTER on the keyboard is not going to do anything. You need to click ADD. 
If you click ADD, the new segment will be added and the dialog is closed.

If you click cancel then no segment is added. 

When you click cancel isn't the dialog closed ?

**Comment by haffonist** [comment]
Is the dialog closed when you click ADD ? If not then we have an issue.

**Comment by robsavage** [comment]
I can’t connect at this moment
R
Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by robsavage** [comment]
dialog closed

the 8 shows after moving to Usage and cardinality.  

click Add and screen flickers and 8 disappears.

When I go to select 8, there are many spaces below 7 and before 8.

I just tried typing 8, it selects 8. I pressed enter, rather than tabbing away and it disappeared.


Rob Savage
Rob Savage Informatics Consulting

rob.savage50@gmail.com

Phone: (608) 233-6129
Cell: (608) 215-8039

**Comment by robsavage** [comment]
SCREEN SHOT
with log

[23 ADD SEG.pdf](https://github.com/haffonist/igamt/files/476912/23.ADD.SEG.pdf)
