### ISSUE TITLE
Profile level CS not published

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#653]
It is possible (and sometimes desirable) to add conformance statements at the profile level. However, it doesn't look like these conformance statements are published as part of the Word document export. Note the existence of CS (red box) but they don't show up in the profile definition (green box) or anywhere in the document (blue box)

![image](https://cloud.githubusercontent.com/assets/17408249/18588398/e65e5a2a-7beb-11e6-9c02-4498b614c82b.png)

![image](https://cloud.githubusercontent.com/assets/17408249/18588443/153fbb86-7bec-11e6-9999-446ab4bc4a85.png)

**Comment by haffonist** [comment]
@olivier-m-mr this is urgent. Can you fix this quick ?
