### ISSUE TITLE
option to publish segments as part of a profile

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#654]
Currently, the profile section of the exported Word document only contains the message definition. Will there be an option to also include the segment definitions too so that it's easier for a reader to understand the whole profile? I think this is a necessary option

![image](https://cloud.githubusercontent.com/assets/17408249/18588557/9b81a614-7bec-11e6-88e6-ac3ebed570ed.png)

**Comment by haffonist** [comment]
the segment definition is below under "segments and field definitions"

**Comment by csnewman88** [comment]
I know it's there, but I think it will be easier for readers to consume if the segments which make up a profile are included in the profile definition. Previous versions of the immunization IG were organized as te export is now, but I, for one, was happy when Release 1.5 moved to having each segment in the profile definition, even though it means that some segments are repeated. 

We can discuss this at one our Wednesday morning calls.

**Comment by haffonist** [comment]
ok.
thanks
