### ISSUE TITLE
Profile order is not reflected in the Word export

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#655]
When exporting into a Word document, the order of the conformance profiles in IGAMT (red box below) is not reflected in the Word document (green box below)

![image](https://cloud.githubusercontent.com/assets/17408249/18588829/b0dbd90c-7bed-11e6-9b6c-c5707b70be40.png)

![image](https://cloud.githubusercontent.com/assets/17408249/18588759/69d7ee7e-7bed-11e6-950c-d9ec5a300ae2.png)

**Comment by haffonist** [comment]
@Abdelghani90  Please fix this.

**Comment by haffonist** [comment]
Fixed in next deployment
