### ISSUE TITLE
Can't remove Conformance Statements added at the profile level

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#656]
I added a conformance statement to an RCP field in the profile editor. I realized I should add it in the segment editor instead. I tried to delete the CS (green arrow) but the 'save" button didn't light up (red box) and when I closed the CS editor, the CS was still there (blue box)

![image](https://cloud.githubusercontent.com/assets/17408249/18590480/96dc6808-7bf4-11e6-98b3-ec2c6b9f02ca.png)

![image](https://cloud.githubusercontent.com/assets/17408249/18590500/b10c9bbc-7bf4-11e6-8c6a-d481058de1dd.png)

![image](https://cloud.githubusercontent.com/assets/17408249/18590517/c4cbbdd6-7bf4-11e6-8a6c-846d4ba0ab1f.png)

**Comment by haffonist** [comment]
Fixing this

**Comment by Jungyubw** [comment]
Fixed
