### ISSUE TITLE
Can't seem to add new complex CS

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#657]
I've created complex CS in the past (see IZ-31 below) but I can't seem to know. I wanted to replace the IZ-31 that exists now because it references the wrong value set. I can create the necessary simple CS and I can build the complex CS, but clicking the "add" button to add the new complex CS doesn't seem to do anything.

![image](https://cloud.githubusercontent.com/assets/17408249/18595971/b45f1688-7c0c-11e6-8159-86174b1d138b.png)

**Comment by Jungyubw** [comment]
@csnewman88 Can you let me know your IG document full name.

I will copy your IG at my side.

**Comment by csnewman88** [comment]
Implementation Guide for Immunization Messaging 2.8.2

**Comment by Jungyubw** [comment]
Fixed
