### ISSUE TITLE
data types missing in word export

### ISSUE THREAD

**Issue by robsavage** [haffonist/igamt#661]
Seq	Element name	Data type	Usage	Cardinality	Length	Value Set	Comment
1	Set ID - OBX		   X	[ 0 .. 0 ]	[ 1 .. 4 ]		
2	Value Type		R	[ 1 .. 1 ]	[ 2 .. 3 ]		
3	Observation Identifier		R	[ 1 .. 1 ]	[ 0 .. 0 ]		
4	Observation Sub-ID		R	[ 1 .. 1 ]	[ 0 .. 0 ]		
5	Observation Value	ED_7106662	R	[ 1 .. 1 ]	[ 1 .. 29999 ]		

NOTE THAT DATA TYPES ARE MISSING EXCEPT IN OBX-5.

**Comment by haffonist** [comment]
Hi Rob, 
This should now be fixed.  

Thanks
