### ISSUE TITLE
Questions about the Delta guide and Values Set

### ISSUE THREAD

**Issue by ctdph** [haffonist/igamt#667]
Hi,

We would like to have a better understanding in the below topics.

1. How the delta guide works? How does it looks in the exportation? Is it necessary to define all the chapters related with the introduction and use cases?

2. What is the difference between HL7 and USR values set in IGAMT tool?

3. How should we interpret the relationship between HL7 and PHVs tables? 
for example: the IGAMT tool has the HL70064 Financial Class table that is empty, but exist PHVS_ImmunizationServiceFundingEligibility_HL7_2x__56964191 table that containing values and system code equal to HL70064
Which table should be associate in the segment?
How can the user identify the values and the correct table?

Thanks,

**Comment by haffonist** [comment]
@robnist I am adding you for reference.

**Comment by Jungyubw** [comment]
Hello, 

1. For now, current tool does not provide delta guide document. User can see the what difference for two profiles/Segments/DT/Tables, but we didn't provide document for that. We will implement that feature.

2. HL7 Table is from the HLT Base standard. So User can import the HL7 Table into the IGDocument , but user cannot change it and just read only. If user delete HL7 table, it means just HL7 reference is removed from your IG document. Whenever you want, you can import it.

The User Table is created by user. User can create user's table to copy from another table or to define from the scratch. User's table is just own table. You can modify it and delete it. When you delete the user table, the Table will be removed from our DB. So you cannot restore it.

3. For this milestone, we will add new feature for PHINVADs importing. Then you can add PHINVADs table into your IG document. PHINVADs table is also not editable like HL7 Table. When CDC updates the table, the table will be updated automatically.  You can import PHINVADs table and then bind it to your Segment and Datatype.

Thanks.
