### ISSUE TITLE
Unshare IG Document

### ISSUE THREAD

**Issue by haffonist** [haffonist/igamt#676]

**Comment by haffonist** [comment]
find and search userby username 
Select found username - Should display user full name 
Send email to newly added participants only - Accept or Reject 
Send response to creator of Ig document to acknowledge participant response 
Display status of request

**Comment by jperugini** [comment]
Done:
find and search userby username 
Select found username - Should display user full name 
Send email to newly added participants only - Accept or Reject 

In progress:
Send response to creator of Ig document to acknowledge participant response 
Send email for unshare
