### ISSUE TITLE
Can't change Value Set Name

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#697]
I copied a value set to create a new one but the Name carries over from the previous value set and can't be changed. For example, below, I created a new "ethnicity" value set from one for "race" and now in the ethnicity value set, I can't change the name from "race"

![image](https://cloud.githubusercontent.com/assets/17408249/18883770/312be16e-84aa-11e6-9067-269518a488fa.png)

**Comment by haffonist** [comment]
I don't think this is a bug.Since this is a flavor the name should not be editable, same with datatype and segment.  
@Jungyubw was there any othe reason behind that decision?

**Comment by haffonist** [comment]
We can't edit the name for flavors. You can edit the name for newly created and Imported VS. 
Will that word for you ?

**Comment by csnewman88** [comment]
If Name is not going to be editable, can you do a one time change to the CDCREC_02 value set to change the name from Race to Ethnicity?

**Comment by Jungyubw** [comment]
@csnewman88 Now we allowed to change the name for value set. You can do it after next deployment.

Thanks.
