### ISSUE TITLE
[WORD/HTML] Remove Length/conf.length for complex DT in the Definition Table

### ISSUE THREAD

**Issue by Jungyubw** [haffonist/igamt#734]

**Comment by maxence-lefort** [comment]
Fixed (See pull request #765).
Before:
<img width="1173" alt="before" src="https://cloud.githubusercontent.com/assets/13853131/19090086/f1f225e8-8a4a-11e6-9e8c-57e35c23dbe8.png">
After:
<img width="1173" alt="after" src="https://cloud.githubusercontent.com/assets/13853131/19090087/f1f4b3b2-8a4a-11e6-9126-02ac4683bcd6.png">

<img width="676" alt="after word" src="https://cloud.githubusercontent.com/assets/13853131/19092163/7c5e5a3c-8a53-11e6-92cc-7ce5cdccbc1b.png">
