### ISSUE TITLE
Display Basic Template Table of Contents - 11/20 - 11/24

### ISSUE THREAD

**Issue by haffonist** [haffonist/igamt#74]
Using the template in this file. 
[V251_IG_SIF_LABRESULTS_R1_DSTUR2_2015SEP.pdf](https://files.zenhub.io/564b90ede5b473fe074b1994)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by gcr-nist** [comment]
Done.  ToC is implemented as an interface into the profile.  It is ready to be enhanced.
