### ISSUE TITLE
DT Library selection

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#749]
What is the radio box indicate? When I select it I expect to go to the place where I can profile. Instead I have to click on the long name?

Is it for publishing? If so, we need to talk. In many cases we just want to create a library and then use them and never finalize (that is, make immutable).

![image](https://cloud.githubusercontent.com/assets/14874904/19051094/8540800a-897f-11e6-80e6-4910df816335.png)

**Comment by Abdelghani90** [comment]
It Is to filter value sets by datatype. Please tell me if you need that or if you think there is  a best way to do it.
