### ISSUE TITLE
Add Right Click Features 11/25-11/27

### ISSUE THREAD

**Issue by haffonist** [haffonist/igamt#75]
- User must be able to right click on root element (Datatypes, Segments....) to add more children
- User must be able to right click on a child to clone, delete.

**Comment by gcr-nist** [comment]
Right click context menu(s) are done.  Minor questions remain wrt clone and add implementations in the service.

**Comment by haffonist** [comment]
@gcr-nist  I am reopening since it has not been QA yet. It needs to be moved to Waiting for QA first.

Thanks

**Comment by gcr-nist** [comment]
Sorry my mistake.  Didn’t see a QA flag.
