### ISSUE TITLE
New Value Set Model and Binding Logic

### ISSUE THREAD

**Issue by haffonist** [haffonist/igamt#757]
- Single value set binding: 
- Multiple Value Set binding  
- Single code binding

**Comment by haffonist** [comment]
- Use Tabs (or Select Button) 
- Add icon to indicate which type of value set.
- Add single code binding to  the conformance statement

**Comment by Jungyubw** [comment]
Duplicated

**Comment by Jungyubw** [comment]
Merged to EPCI #1345
