### ISSUE TITLE
Stylesheet optimization and merge for the export

### ISSUE THREAD

**Issue by maxence-lefort** [haffonist/igamt#787]
Split the templates into different files and have only one stylesheet that takes parameters to export all we need. It will save us a lot of time in the future, especially when we'll want to only export some parts of the IG document.

**Comment by maxence-lefort** [comment]
@olivier-m-mr @Abdelghani90 What's your input on the estimated effort? (That would also include testing all the current exports to check for eventual regression).

**Comment by Abdelghani90** [comment]
I agree with you 21
