### ISSUE TITLE
Usage  not outputting correctly

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#789]
The Usage in the Word output of a profile is not being populated correctly

![image](https://cloud.githubusercontent.com/assets/17408249/19167996/b5a5a95e-8bd3-11e6-8e40-0f8306741f17.png)

**Comment by haffonist** [comment]
@Abdelghani90 fix this asap. Does it mean that your QA did not check this first before validating ?

**Comment by Abdelghani90** [comment]
@haffo please approve
