### ISSUE TITLE
Co-constraints table sorting doesn't seem to work

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#797]
I'm assuming you should be able to sort the co-constraints table by a column, but it doesn't seem to be working. The order doesn't change regardless of whether or not the arrow is up (red circle below) or down (green circle below)

![image](https://cloud.githubusercontent.com/assets/17408249/19197649/9581f062-8c80-11e6-8edc-7ca2ced67b6c.png)
![image](https://cloud.githubusercontent.com/assets/17408249/19197666/aa48195e-8c80-11e6-9a08-90d72a4690b3.png)

**Comment by haffonist** [comment]
@Jungyubw  anything on this ?
