### ISSUE TITLE
Word export is running words together

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#803]
When I export my IG to Word, some of the words are running together even though there are spaces in IGAMT.

![image](https://cloud.githubusercontent.com/assets/17408249/19270557/3df3b14c-8f86-11e6-9e0e-3898811faa18.png)

![image](https://cloud.githubusercontent.com/assets/17408249/19270625/8e875686-8f86-11e6-9585-88dfc1f9ba48.png)

![image](https://cloud.githubusercontent.com/assets/17408249/19270650/b5150fbe-8f86-11e6-9124-cfbdd3a3ed66.png)

![image](https://cloud.githubusercontent.com/assets/17408249/19270696/e6c05b9a-8f86-11e6-8009-34c53aad43de.png)

**Comment by haffonist** [comment]
@olivier-m-mr please fix this,

**Comment by haffonist** [comment]
@olivier-m-mr any update ?
