### ISSUE TITLE
Need to be able to order Conformance Statements

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#805]
Sometimes CS aren't entered (or numbered) in the order they should be in the final document. There needs to be a way to order these as the author wants. For example, below, the PID CS (red box) should be below all the MSH CS. And the MSH-15 and 16 CS (green box) need to be integrated in to the other MSH CS

![image](https://cloud.githubusercontent.com/assets/17408249/19275375/2322a5ea-8f99-11e6-988a-3c8d1aa77b5b.png)

**Comment by Jungyubw** [comment]
This is working by OrderBy ID. Please click Header "ID" on the Table.
