### ISSUE TITLE
Label is wrong

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#813]
On the IG Document Metadata page the date label is not displaying correctly (red box below).

On a related note, I thought we were going to update this date/time every time we saved the IG so that it represented the currently date of the document.

![image](https://cloud.githubusercontent.com/assets/17408249/19439202/dddbda98-9442-11e6-90c2-b9ee1999351b.png)

**Comment by haffonist** [comment]
Fixed and will be deploy soon.
