### ISSUE TITLE
Don't publish Cardinality and Usage for End of Segment Group

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#821]
When outputting the conformance profile, it makes sense to publish the segment group usage and cardinality at the beginning of the segment group (green boxes below) but not at the end of the segment group (red boxes below)

![image](https://cloud.githubusercontent.com/assets/17408249/19491164/8a0175a4-9537-11e6-9f0e-8b3776076435.png)

**Comment by haffonist** [comment]
@olivier-m-mr  is this already merged ?
