### ISSUE TITLE
Exported Word document has trouble opening

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#836]
I exported my IG to Word but when I tried to open it, I got warning errors (see below). Ultimately, it did open and look OK, but I'm assuming there is an error in there somewhere.

![image](https://cloud.githubusercontent.com/assets/17408249/19686707/02e7d7c4-9a88-11e6-83a6-4c8bccf1e8d0.png)

![image](https://cloud.githubusercontent.com/assets/17408249/19686712/082806b4-9a88-11e6-9467-dd4c33cc65e2.png)

![image](https://cloud.githubusercontent.com/assets/17408249/19686741/26ae032c-9a88-11e6-8f25-feff65055f6d.png)

**Comment by haffonist** [comment]
@olivier-m-mr does that mean anything to you ?

**Comment by haffonist** [comment]
Fixed
