### ISSUE TITLE
Impossible to create new IG document

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#838]
I tried to create a new IG, but there is no event when I expend the message type
![igamt impossible create](https://cloud.githubusercontent.com/assets/13591511/19694391/238e2d64-9aad-11e6-9532-01e7e9eefeff.JPG)

This is on the production tool.

**Comment by carolinerosin** [comment]
dev tool seems to work - so this is only a problem on production

**Comment by haffonist** [comment]
Fixed and redeploying
