### ISSUE TITLE
Content from Value Set section not in the export

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#847]
I added content to the Value Set section to explain value sets in general, but when I exported the document, it wasn't present.

![image](https://cloud.githubusercontent.com/assets/17408249/19819573/f9111478-9d1a-11e6-852c-b6361c2a1d42.png)

![image](https://cloud.githubusercontent.com/assets/17408249/19819596/0d53e3e8-9d1b-11e6-943e-b7b52ec1e107.png)

**Comment by haffonist** [comment]
fixed.
