### ISSUE TITLE
files won't open

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#882]
We're having another problem with exporting to a Word file. When I try to do this, I get the following errors when i try to open the Word document:

![image](https://cloud.githubusercontent.com/assets/17408249/20435253/089de5fe-ad71-11e6-815b-2cba63d16e31.png)

This is the case not only for my newer versions of the IG, but also for a copy saved on 10/19 before I exported document to add the manual formatting and circulate for review, so I know versions of the IG have exported successfully in the past.

**Comment by haffonist** [comment]
This is a content issue. Please check the content.  Last time you had that issue it was because an html content was copied to the editor. You could open your last changed sections and see if there is any weird displayed content.

**Comment by csnewman88** [comment]
The problem is that I can't open it this time. Plus this is happening with versions of documents I haven't changed recently (or ever such as the OML_O21 IG). 

When I look at the downloaded files, I'm seeking that the recently downloaded files are all 1 KB while ones that opened fine in late October are all much larger (compare the red and green boxes below). I'm wondering if the files are being incompletely exported.

![image](https://cloud.githubusercontent.com/assets/17408249/20497589/547113a4-afef-11e6-91a2-5be1c6ae3f4c.png)

**Comment by csnewman88** [comment]
Plus, I've created a new IG (with only one conformance profile and only a single section modified by typing a small amount of text  - no cut and paste, no formatting) and that document will not open either. I'll share this IG with you so you can check it out or you can try the same experiment.

**Comment by haffonist** [comment]
Yes there are incompletely exported. Our code was broken. We are fixing this now

**Comment by haffonist** [comment]
Fixed.
