### ISSUE TITLE
unable to change datatype for element in segment

### ISSUE THREAD

**Issue by Healthedata1** [haffonist/igamt#884]
Unable to edit a datatype where needed.  The choice box does not offer any choices and since we "pre-adopt" other datatype from futre version the can change.  For example,  CE --> CWE.

**Comment by Healthedata1** [comment]
examples LOI OBR 4 and 13

**Comment by haffonist** [comment]
You should be able to do so. Have you created a flavor of the primary datatype first ?

**Comment by Healthedata1** [comment]
The flavor of a CE is still a CE ? right or am i missing something.   The change is datatype occurs at the field level and is based on a future version  ie guse a 2.8.2 dataype in a 2.5.1 field.   Also need to do this for message types where we pull in a 2.8.2  message type into a v 2.5.1 IG

**Comment by haffonist** [comment]
Yes a flavor or CE is CE_XXX where XXX is an extension you give. 
Since the change is a field level, you should create a flavor of the segment. Then you can select the field datatype flavor 
The functionality is already there. May be we should do a video conf so I can show you how this work ??

**Comment by RikiMerrick** [comment]
We have to change the primary datatype from CE to CWE (has more elements than just the first 6 elements)
Also OBR-13 changed from ST to CWE.

**Comment by carolinerosin** [comment]
@haffo I think IGAMT may be too restrictive. Right now we can only change a datatype to a flavor of the original datatype. There are other cases that should be allowed, for example a field that is a "CE" datatype in the standard can be profiled to a CWE flavor. I can work on a list of what is allowed
