### ISSUE TITLE
For DTM need to be able to define compoents as R, RE, O also

### ISSUE THREAD

**Issue by RikiMerrick** [haffonist/igamt#887]
In LRI we have TS flavors that describe use of the DTM components.

Also for the TZO need to be able to indicate varies based on a profile ID in MSH-21, unless that is done some other way in IGAMT.

**Comment by Healthedata1** [comment]
Specfically we are asking that the DTM datatype allow a drop down for R, RE, C etc for each level of precision (yyyy, mm,dd, etc)  even though not in base standard.

**Comment by Jungyubw** [comment]
Closed because this ticket merged into #726
