### ISSUE TITLE
HTML export doesn't work at all

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#892]
The HMTL export seems to produce a completely empty file. As of right now, none of the exports work

**Comment by haffonist** [comment]
@maxence-lefort please fix.

**Comment by haffonist** [comment]
Also the HTML content are missing froala style. Those were there before. May sure whatever was working before still works.

**Comment by maxence-lefort** [comment]
@haffonist Should be fixed, see pull request #895

**Comment by haffonist** [comment]
Fixed.
