### ISSUE TITLE
images won't load

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#893]
I'm having trouble getting images integrated into IGAMT. A few of the images I've tried will load, but most of them give the error seen below. There is no indication of what went wrong.

Note that in this example, I'm trying to load the same file as what is above it (so I know this file has been OK before). The image file type, doesn't seem to consistently predict success or failure
![image](https://cloud.githubusercontent.com/assets/17408249/20492070/fd5279d4-afd8-11e6-85e0-bb5aefb79289.png)

**Comment by haffonist** [comment]
Fixed
