### ISSUE TITLE
Conformance profile level constraints are not displayed

### ISSUE THREAD

**Issue by maxence-lefort** [haffonist/igamt#906]

**Comment by olivier-m-mr** [comment]
I did a fresh pull from all-lib and it seems to me that https://github.com/haffonist/igamt/pull/904 
took care of it. Please let me know if you still the issue.
Note: I used IG id 57c8371a84ae6827fcec5488

[ig_test.html.zip](https://github.com/haffonist/igamt/files/607550/ig_test.html.zip)
