### ISSUE TITLE
updating the "Date Updated" value doesn't seem to work

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#911]
When copying a whole IG, I would expect the "date updated" column for the new IG to be updated with the current date, but it doesn't seem to be.
Before the copy:
![image](https://cloud.githubusercontent.com/assets/17408249/20564211/cec8cd0a-b151-11e6-85ab-2b67b1fb6ca6.png)
After the copy:
![image](https://cloud.githubusercontent.com/assets/17408249/20564232/e2fb36e6-b151-11e6-950f-29d82b961959.png)

And then when the document is actually updated (note the new title in the example below), the Date Updated isn't updated either.
![image](https://cloud.githubusercontent.com/assets/17408249/20564280/264bf516-b152-11e6-876c-64254780644a.png)

**Comment by haffonist** [comment]
Fixed
