### ISSUE TITLE
Issues with Date Updated

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#912]
There seems to be some trouble with the individual Date Updated field of the IG components.

On the Metadata tab, the Date Updated value has a couple of issues:
1) it doesn't update, even when data is changed (see example below)
2) the field doesn't seem to be editable (which makes sense), but it isn't greyed out (like HL7 Version is), so it seems like an author should be able to update it.

![image](https://cloud.githubusercontent.com/assets/17408249/20564396/ba4c365e-b152-11e6-8443-890e2c959587.png)

In other tabs, the Date Updated field starts out OK (in the example below, it starts out as the date/time when I copied the IG), but when I update the Contents, the Date Updated reverts to an earlier date (the one on the Metadata tab presumably) rather than updating to the current date/time
Before the change:
![image](https://cloud.githubusercontent.com/assets/17408249/20564455/07f837ae-b153-11e6-9e12-ac2ac49c8787.png)

After the change:
![image](https://cloud.githubusercontent.com/assets/17408249/20564488/234537dc-b153-11e6-80a5-890a43cf4468.png)

**Comment by haffonist** [comment]
FIXED
