### ISSUE TITLE
export gets truncated

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#913]
Even though the text in IGAMT looks OK, there are two places in my IG where the export gets truncated.

The first spot is in section 1.4.5 which looks like this in IGAMT:
![image](https://cloud.githubusercontent.com/assets/17408249/20566994/b1f6c334-b15c-11e6-9ed4-b19525b7b5cc.png)
And the export ends here:
![image](https://cloud.githubusercontent.com/assets/17408249/20567035/dcb13a3c-b15c-11e6-8883-b6b3ff5d1e0b.png)

If you go into IGAMT and replace the current text between the tables with an identical copy, then the export works:
![image](https://cloud.githubusercontent.com/assets/17408249/20567238/a0b51700-b15d-11e6-97c3-523b5afce13c.png)

![image](https://cloud.githubusercontent.com/assets/17408249/20567258/afff5acc-b15d-11e6-81a2-70b016c37fde.png)

The second place where the export truncates is in section 2.3.7.11 in the middle of the word "Local". In IGAMT it looks like this:
![image](https://cloud.githubusercontent.com/assets/17408249/20567359/fcabff7e-b15d-11e6-9ad5-d2978b93ab90.png)
And the export looks like this:
![image](https://cloud.githubusercontent.com/assets/17408249/20567385/17eefb24-b15e-11e6-92ae-c079339299eb.png)

If you go into IGAMT and replace the word "Local" the issue is fixed:
![image](https://cloud.githubusercontent.com/assets/17408249/20567474/6ed348a0-b15e-11e6-99a4-505bd1091d9d.png)

![image](https://cloud.githubusercontent.com/assets/17408249/20567456/62214a76-b15e-11e6-8273-3243d12846d0.png)

My guess is that there are unprintable characters in there that are causing the export to truncate without an error but I sure can't find them.

I've created copies of my IG so that the development team can take a look and will share them with Harold. They will be labeled "before" and "after". "before" has the truncating issue, the "after" has been fixed and successfully exported.

**Comment by maxence-lefort** [comment]
@csnewman88 Now we remove any non printable character before exporting, so it should fix your issue. I'll let you know when it's available on the dev server so that you can try exporting your document again.

**Comment by maxence-lefort** [comment]
@csnewman88 Can you please give it a try? It should be fixed on both the development and production servers now.

**Comment by csnewman88** [comment]
Looks like I don't have the original documents anymore. I'll keep an eye out for the issue to arise again and let you know if I see it.
