### ISSUE TITLE
Images aren't exporting again

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#914]
The Word document exports have reverted to a previous issue where images in IGAMT are not being included in the export document.

![image](https://cloud.githubusercontent.com/assets/17408249/20567898/09d59b68-b160-11e6-85f9-d3d8565240bf.png)

**Comment by csnewman88** [comment]
I checked .png, .gif and .jpg files and none of them seem to work.

**Comment by haffonist** [comment]
We refactored the export code lately. That must be the cause of this. we will fix this. Sorry for the inconvenience.

**Comment by haffonist** [comment]
@maxence-lefort fix this.  

Harold
