### ISSUE TITLE
"Global" seems like the wrong word

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#915]
When describing Conformance Statements or Conditional Predicates that only apply to a given Conformance Profile, the word "Global" seems inaccurate. "global" makes me think that these apply to the entire IG and not just the Conformance Profile. Could you just use "Profile" instead? Or is the scope of these "global" statements and predicates bigger than I think?

![image](https://cloud.githubusercontent.com/assets/17408249/20568757/20506d66-b163-11e6-8c31-7c5fff2e3144.png)

**Comment by haffonist** [comment]
You are right. we will change this to something else.
