### ISSUE TITLE
Global Conformance Statements missing from the Export

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#916]
The Word Export doesn't seem to include any of the Global Conformance statements. For example, the ADT conformance profile below has a number of CS, but when I search the Word export, I don't find them.

![image](https://cloud.githubusercontent.com/assets/17408249/20568892/97eaaf26-b163-11e6-930e-a55a2708937e.png)

![image](https://cloud.githubusercontent.com/assets/17408249/20568910/b19d5608-b163-11e6-8d10-921cc501bccc.png)

**Comment by haffonist** [comment]
Yes, the export has not been updated to support this yet. We will let you know when this is done.

**Comment by maxence-lefort** [comment]
@haffonist Should be fixed with pull request #923
