### ISSUE TITLE
Usage for value set when no values are listed

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#938]
In those cases where a value set doesn't contain any suggested values, it probably doesn't make sense to default a Usage (see blue circle below). I think leaving it blank would be better.

![image](https://cloud.githubusercontent.com/assets/17408249/20898198/10867d80-baeb-11e6-93cb-eca14d4aec29.png)

**Comment by haffonist** [comment]
@maxence-lefort  update ?

**Comment by maxence-lefort** [comment]
@haffonist I'll take a look when I'll be done with the cover image
