### ISSUE TITLE
Uniqueness of Conformance Statement IDs is no longer checked

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#945]
There used to be a check on the conformance statement ID to make sure it wasn't already in use. That doesn't seem to happen anymore.

This CS existed:
![image](https://cloud.githubusercontent.com/assets/17408249/20973380/0aa94d1a-bc5e-11e6-9f46-e6683cd94987.png)

But I was still able to create this in another part of the IG:
![image](https://cloud.githubusercontent.com/assets/17408249/20973412/25b82d92-bc5e-11e6-878e-d8037a80558e.png)

**Comment by Jungyubw** [comment]
Yes we removed that logic. User can make duplicated ID intentionally.
