### ISSUE TITLE
Deleting a Conformance Statement doesn't light up the "save" button

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#946]
I'm trying to delete a Conformance Statement associated with the MSA segment:
![image](https://cloud.githubusercontent.com/assets/17408249/20973510/6da35820-bc5e-11e6-821f-ef51b97d6f2f.png)

But when I click the delete button, the CS goes away, but there is no way to save the change as the "save" button doesn't light up:
![image](https://cloud.githubusercontent.com/assets/17408249/20973550/9d333524-bc5e-11e6-99c6-7167823ab264.png)

And if you move away from the segment, there is no pop up asking to save changes.

And then when you go back to the MSA segment, the deleted CS is still there:
![image](https://cloud.githubusercontent.com/assets/17408249/20973599/d3138036-bc5e-11e6-97ad-0b332bf759c2.png)

**Comment by Jungyubw** [comment]
Fixed
