### ISSUE TITLE
Can seem to add a condition predicate

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#948]
I'm trying to add a Conditional Predicate to a segment. I can add the requirement, but I don't see a way to specify the true/false usages and the "save" button (green box below) doesn't light up. Am I missing something?

![image](https://cloud.githubusercontent.com/assets/17408249/21026566/d4e88c90-bd52-11e6-99fc-e22596646708.png)

**Comment by Jungyubw** [comment]
@csnewman88  Harold will give a demo for new constraint UI later.

**Comment by Jungyubw** [comment]
In addition I will make simple tutorial document for this.

Thanks.
