### ISSUE TITLE
complex conformance statement ID is wrong

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#950]
When a complex conformance statement is created, the ID is not transferred correctly when the CS is added. When I added the CS in the example below, the default ID was replaced by the "IFTHEN" statement highlighted by the green box. Oddly, the simple conformance statement IDs seem to work.

![image](https://cloud.githubusercontent.com/assets/17408249/21027150/34fed0f6-bd55-11e6-8e6a-d438bb0c3e36.png)

**Comment by Jungyubw** [comment]
Okay I will fix it to use simple ID.

Before my modification, you can type ID and change it in the UI.

Thanks.

**Comment by Jungyubw** [comment]
Done
