### ISSUE TITLE
Export Style: T2 - Content issue

### ISSUE THREAD

**Issue by haffonist** [haffonist/igamt#953]
17 Contents part of value set (highest part) for section is not exported.
18 There are a handful of value sets in the export that aren’t in IGAMT. For example, this empty Administrative Sex value is not in IGAMT

**Comment by olivier-m-mr** [comment]
Trying unsuccessfully to reproduce bugs:
DB produces same number of value sets as export.
Value set contents is exported

[mongo tbl lib.pdf](https://github.com/haffonist/igamt/files/647191/mongo.tbl.lib.pdf)

[Implementation Guide.pdf](https://github.com/haffonist/igamt/files/647198/Implementation.Guide.pdf)

**Comment by olivier-m-mr** [comment]
[ig_test.docx](https://github.com/haffonist/igamt/files/649975/ig_test.docx)
Export of ig with id 57c8371a84ae6827fcec5488 via test class
