### ISSUE TITLE
Export Style: T3 - Display issues

### ISSUE THREAD

**Issue by haffonist** [haffonist/igamt#954]
3 Bold text is not exported as bold and white space after each bolded area is being lost
4 Resize figures
5 Formatting of “code” in Igamt => no line breaks in export
7 White space is lost between code samples
10 Characters aren’t translating correctly in the export e.g. dashes => â€"

**Comment by maxence-lefort** [comment]
@olivier-m-mr what's the status on this issue? Is everything fixed?

**Comment by olivier-m-mr** [comment]
I had not found solution for the image resizing as the library was not allowing resizing images. 
The other issues were html5/html4 (strong vs bold) and missing encoding.
I'll double check but it should have been fixed and pushed.

**Comment by olivier-m-mr** [comment]
These are included in the pull request to fix #1030 ( #1055  )
