### ISSUE TITLE
Export Style: T4 - Content re-organization

### ISSUE THREAD

**Issue by haffonist** [haffonist/igamt#955]
8 In the message infrastructure, within the conformance profile section, all the conformance statements are grouped in one table for each profile. The ID column has to be wide enough so that the ID doesn’t wrap.
9 Each segment definition contained within a profile is copied into the profile definition section. This means that common segments which are the same between profiles (like MSH) are duplicated, but it also means that each profile section is more stand-alone.
11 No more segment and field descriptions (it is moved within profile)
12 [comment 13] needs clarification: should optional segments remains is a separate section?
13 For any optional elements in the segment tables, remove the value set, cardinality and length
Note1: for any optional element, the reader should refer back to the base standard. As a consequence, value set, cardinality and length are removed in segment table. Note2: in the conformance profile tables, cardinality for optional segments is kept.
16 Datatype: remove datatype which are not flavours
21 Remove value sets that are not specific to immunization

**Comment by olivier-m-mr** [comment]
@haffonist : I think this was included in Maxence's refactor.
