### ISSUE TITLE
CWE version 2.7.1 missing information

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#960]
There is no length, conformance length and no datatype in the HL7 v2.7.1 definition of CWE (I did not check other datatype
![cwe 2 7 1](https://cloud.githubusercontent.com/assets/13591511/21158014/a06d2692-c149-11e6-8e54-b899b0e7e751.JPG)
s)

**Comment by haffonist** [comment]
It seems to be view issue and not a data issue. It should be fixed in next deployment 01/13
