### ISSUE TITLE
IGAMT Delta Feature does not show most recently added elements when comparing versions

### ISSUE THREAD

**Issue by Healthedata1** [haffonist/igamt#962]
For example looking at the OBX segment and comparing between 2.5.1 and 2.8.2 there are several new segments after field 25 (the number of fields in v2.5.1) that are absent in the delta view.

Include the new elements in the comparison view.

**Comment by haffonist** [comment]
ok, we will fix this. 
Thanks

**Comment by haffonist** [comment]
fixed.
