### ISSUE TITLE
copied profiles don't save

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#972]
I'm trying to copy an existing profile (the Z34 profile).

I can copy it (and modify it) - see red arrow below

![image](https://cloud.githubusercontent.com/assets/17408249/21278415/ac9cd1b6-c3a0-11e6-89dc-c99fccf97985.png)

But when I close the document and then go back in, it's not there (note that the number of profiles when from 10 to 9):
![image](https://cloud.githubusercontent.com/assets/17408249/21278458/e7f41a30-c3a0-11e6-9e97-370227184275.png)

**Comment by haffonist** [comment]
Copied profile does not save.
