### ISSUE TITLE
Can't add a profile

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#973]
when I right click on "conformance profiles" to add a new profile, I can't select an event to add:

![image](https://cloud.githubusercontent.com/assets/17408249/21278513/3f7ad438-c3a1-11e6-8971-3c4a5ba065f9.png)

Combine this with the issue about copying and saving profiles (see issue 972), there is no way to add a new conformance profile in the production IGAMT.

**Comment by haffonist** [comment]
This is the data issue I was talking about at our last meeting. Next week, we will fix that. sorry for inconvenience

**Comment by csnewman88** [comment]
Has this been fixed yet? If not, any idea on when we'll be able to add new profiles?

**Comment by haffonist** [comment]
Hi Craig,

Yes by tomorrow meeting.


Harold


________________________________

**Comment by haffonist** [comment]
Still working on this. 
Will keep you updated. 

Harold
