### ISSUE TITLE
IGAMT delta feature for datatype representation does not match pdf

### ISSUE THREAD

**Issue by RikiMerrick** [haffonist/igamt#984]
Assuming the published pdf documents are the source of truth for the respective HL7 versions, there are instances where the datatype displayed in the delta analysis for a version does not match the base - reported by Caroline - can you provide an example

**Comment by haffonist** [comment]
The issue might be in the data. We are looking into it.

**Comment by haffo** [comment]
@carolinerosin  is this fixed for you ?

**Comment by RikiMerrick** [comment]
Sorry I have not had a chance to test it - not sure I will get to test it
today either...

Riki

Riki Merrick
Vernetzt, LLC
rikimerrick@gmail.com
cell: 916.216.0052
skype: riki.merrick

**Comment by haffonist** [comment]
No prob. any time you can.
